//! A CCSDS 121.0-B Adaptive Entropy Coding (AEC) decoder, the coder behind
//! GRIB2 template 5.42 and the HDF5 szip filter.
//!
//! The reference is libaec 1.1.7: this crate accepts the parameter sets libaec's
//! decoder accepts, and is checked against libaec's own output byte for byte,
//! over a committed corpus of streams libaec's encoder wrote
//! (`tests/fixtures/`, generated by `tools/build_aec_fixtures.py` in the
//! repository). Where it departs from libaec it is stricter, and says so
//! ([ADR-0012]).
//!
//! # Status
//!
//! This release carries the parameter surface, [`Params`] and [`Flags`], and
//! the error type. The decoder that uses them lands next, followed by the
//! libsz-compatible szip layer; no reader depends on this crate yet.
//!
//! ```
//! use fieldglass_aec::{AecError, Flags, Params};
//!
//! // A GRIB2 5.42 message's `ccsdsFlags` octet maps straight onto `Flags`.
//! let flags = Flags::from_bits_truncate(14);
//! assert!(flags.contains(Flags::PREPROCESS | Flags::MSB));
//!
//! let params = Params::new(24, 32, 128, flags)?;
//! assert_eq!(params.bytes_per_sample(), 3);
//!
//! // libaec refuses the restricted set from 5 to 8 bits, and so does this.
//! assert_eq!(
//!     Params::new(6, 32, 128, Flags::RESTRICTED),
//!     Err(AecError::Restricted(6))
//! );
//! # Ok::<(), AecError>(())
//! ```
//!
//! Reference: CCSDS 121.0-B-3, *Lossless Data Compression* (2020); behaviour
//! checked against libaec 1.1.7 (`aec_decode_init`, `decode.c:692-754`).
//!
//! [ADR-0012]: https://github.com/D0ubleD0uble/fieldglass/blob/master/docs/decisions/0012-own-the-aec-decoder.md

#![forbid(unsafe_code)]

mod error;
mod params;

pub use error::AecError;
pub use params::{Flags, Params};
