//! A CCSDS 121.0-B Adaptive Entropy Coding (AEC) decoder, the coder behind
//! GRIB2 template 5.42 and the HDF5 szip filter.
//!
//! The goal is to decode correctly per the standard, CCSDS 121.0-B-3. libaec
//! 1.1.7 is the reference it is checked against: this crate accepts the
//! parameter sets libaec's decoder accepts, and matches libaec's output byte
//! for byte wherever libaec is correct, over a committed corpus of streams
//! libaec's encoder wrote (`tests/fixtures/`, generated by
//! `tools/build_aec_fixtures.py` in the repository). Where libaec departs from
//! the standard or accepts a broken stream, this crate follows the standard
//! instead. [ADR-0012] lists each divergence with its evidence:
//!
//! - **Second-extension codewords past libaec's table.** libaec's decoder stops
//!   at a pair sum of 12 and refuses larger codewords, which its own encoder
//!   writes. The standard sets no such bound, and this crate reads them.
//! - **Truncated input** is an error, [`AecError::Truncated`], where libaec
//!   returns success with short output. Nothing is zero-filled.
//! - **A value of 2^n or more before postprocessing** is an error,
//!   [`AecError::InvalidCode`], where libaec wraps it silently.
//! - **A second-extension pair beside a reference sample must start with 0.**
//!   The standard puts a 0 there; libaec ignores whatever the codeword says.
//!   Any other first value is [`AecError::InvalidCode`].
//! - **A zero-block run longer than 63 blocks** is [`AecError::InvalidCode`]:
//!   the standard's table of run codes ends there, and libaec accepts any
//!   length that fits the interval.
//! - **Trailing bytes are never read.** Decoding stops at the requested count,
//!   so fill after the last sample that libaec misparses as a zero-block run is
//!   not an error here.
//!
//! # Decoding
//!
//! [`decode`] hands samples to a [`Sink`], one block or one run of zero blocks
//! at a time, so a consumer can convert them straight into its own output.
//! [`decode_to_bytes`] writes libaec's byte layout. Neither allocates: the
//! block buffer is on the stack, and the caller owns the output, and with it
//! any cap on its size.
//!
//! ```
//! use fieldglass_aec::{AecError, Flags, Params, decode_to_bytes};
//!
//! // A GRIB2 5.42 message's `ccsdsFlags` octet maps straight onto `Flags`.
//! let flags = Flags::from_bits_truncate(14);
//! assert!(flags.contains(Flags::PREPROCESS | Flags::MSB));
//! let params = Params::new(24, 32, 128, flags)?;
//! assert_eq!(params.bytes_per_sample(), 3);
//!
//! // libaec refuses the restricted set from 5 to 8 bits, and so does this.
//! assert_eq!(
//!     Params::new(6, 32, 128, Flags::RESTRICTED),
//!     Err(AecError::Restricted(6))
//! );
//!
//! // 8-bit samples in blocks of 2: a zero block (id 0b000, selector 0,
//! // one block), which without preprocessing is two zero samples.
//! let params = Params::new(8, 2, 1, Flags::empty())?;
//! let mut out = [0xFF; 2];
//! decode_to_bytes(&[0b0000_1000], &params, &mut out)?;
//! assert_eq!(out, [0, 0]);
//!
//! // A stream that ends early is an error, never zero-filled output.
//! let mut out = [0; 4];
//! assert!(matches!(
//!     decode_to_bytes(&[0b0000_1000], &params, &mut out),
//!     Err(AecError::Truncated { decoded: 2, requested: 4 })
//! ));
//! # Ok::<(), AecError>(())
//! ```
//!
//! The libsz-compatible szip layer follows; no reader depends on this crate
//! yet.
//!
//! Reference: CCSDS 121.0-B-3, *Lossless Data Compression* (2020); behaviour
//! checked against libaec 1.1.7 (`decode.c`).
//!
//! [ADR-0012]: https://github.com/D0ubleD0uble/fieldglass/blob/master/docs/decisions/0012-own-the-aec-decoder.md

#![forbid(unsafe_code)]

mod bits;
mod decode;
mod error;
mod params;
mod sink;

pub use decode::{decode, decode_to_bytes};
pub use error::AecError;
pub use params::{Flags, Params};
pub use sink::Sink;
