//! NCEP local GRIB2 parameters, generated from wgrib2.
//!
//! Do not edit: regenerate with `python3 tools/gen_ncep_tables.py`.
//! Source: wgrib2 v3.8.0, `wgrib2/gribtables/ncep/gribtable.dat`, itself
//! produced by wgrib2's `get_gribtab.sh` from the NCO GRIB2 documentation.
//! Both are works of the U.S. federal government and in the public domain.
//!
//! 479 parameters, none gated on the local table version and none
//! ambiguous. See the generator's module docs for why wgrib2 rather than
//! eccodes, and for what the centre-0 rows in the same file are not.

/// The local table versions this centre gates entries on: none, and it cannot
/// be otherwise — [`lookup`] below takes no version to gate on. That is the
/// structural reason, not a claim about today's data; gating NCEP would mean
/// changing the signature, which changes this line with it (#476).
pub(crate) const GATED_VERSIONS: &[u8] = &[];

/// Look up a local NCEP parameter, or `None` when this table does not define
/// the triple.
pub(crate) fn lookup(
    discipline: u8,
    category: u8,
    number: u8,
) -> Option<(&'static str, &'static str, &'static str)> {
    let entry = match (discipline, category, number) {
        (0, 0, 192) => ("SNOHF", "Snow Phase Change Heat Flux", "W/m^2"),
        (0, 0, 193) => ("TTRAD", "Temperature Tendency by All Radiation", "K/s"),
        (0, 0, 194) => ("REV", "Relative Error Variance", "-"),
        (0, 0, 195) => ("LRGHR", "Large Scale Condensate Heating Rate", "K/s"),
        (0, 0, 196) => ("CNVHR", "Deep Convective Heating Rate", "K/s"),
        (0, 0, 197) => ("THFLX", "Total Downward Heat Flux at Surface", "W/m^2"),
        (0, 0, 198) => ("TTDIA", "Temperature Tendency by All Physics", "K/s"),
        (0, 0, 199) => (
            "TTPHY",
            "Temperature Tendency by Non-radiation Physics",
            "K/s",
        ),
        (0, 0, 200) => ("TSD1D", "Standard Dev. of IR Temp. over 1x1 deg. area", "K"),
        (0, 0, 201) => ("SHAHR", "Shallow Convective Heating Rate", "K/s"),
        (0, 0, 202) => ("VDFHR", "Vertical Diffusion Heating rate", "K/s"),
        (0, 0, 203) => (
            "THZ0",
            "Potential Temperature at Top of Viscous Sublayer",
            "K",
        ),
        (0, 0, 204) => ("TCHP", "Tropical Cyclone Heat Potential", "J/m^2*K"),
        (0, 0, 205) => ("ELMELT", "Effective Layer (EL) Temperature", "C"),
        (0, 0, 206) => ("WETGLBT", "Wet Bulb Globe Temperature", "K"),
        (0, 1, 192) => ("CRAIN", "Categorical Rain", "-"),
        (0, 1, 193) => ("CFRZR", "Categorical Freezing Rain", "-"),
        (0, 1, 194) => ("CICEP", "Categorical Ice Pellets", "-"),
        (0, 1, 195) => ("CSNOW", "Categorical Snow", "-"),
        (0, 1, 196) => ("CPRAT", "Convective Precipitation Rate", "kg/m^2/s"),
        (0, 1, 197) => ("MDIV", "Horizontal Moisture Divergence", "kg/kg/s"),
        (0, 1, 198) => ("MINRH", "Minimum Relative Humidity", "%"),
        (0, 1, 199) => ("PEVAP", "Potential Evaporation", "kg/m^2"),
        (0, 1, 200) => ("PEVPR", "Potential Evaporation Rate", "W/m^2"),
        (0, 1, 201) => ("SNOWC", "Snow Cover", "%"),
        (0, 1, 202) => ("FRAIN", "Rain Fraction of Total Liquid Water", "non-dim"),
        (0, 1, 203) => ("RIME", "Rime Factor", "non-dim"),
        (0, 1, 204) => ("TCOLR", "Total Column Integrated Rain", "kg/m^2"),
        (0, 1, 205) => ("TCOLS", "Total Column Integrated Snow", "kg/m^2"),
        (0, 1, 206) => ("TIPD", "Total Icing Potential Diagnostic", "non-dim"),
        (0, 1, 207) => ("NCIP", "Number concentration for ice particles", "non-dim"),
        (0, 1, 208) => ("SNOT", "Snow temperature", "K"),
        (0, 1, 209) => (
            "TCLSW",
            "Total column-integrated supercooled liquid water",
            "kg/m^2",
        ),
        (0, 1, 210) => ("TCOLM", "Total column-integrated melting ice", "kg/m^2"),
        (0, 1, 211) => ("EMNP", "Evaporation - Precipitation", "cm/day"),
        (0, 1, 212) => ("SBSNO", "Sublimation (evaporation from snow)", "W/m^2"),
        (0, 1, 213) => ("CNVMR", "Deep Convective Moistening Rate", "kg/kg/s"),
        (0, 1, 214) => ("SHAMR", "Shallow Convective Moistening Rate", "kg/kg/s"),
        (0, 1, 215) => ("VDFMR", "Vertical Diffusion Moistening Rate", "kg/kg/s"),
        (0, 1, 216) => (
            "CONDP",
            "Condensation Pressure of Parcali Lifted From Indicate Surface",
            "Pa",
        ),
        (0, 1, 217) => ("LRGMR", "Large scale moistening rate", "kg/kg/s"),
        (0, 1, 218) => (
            "QZ0",
            "Specific humidity at top of viscous sublayer",
            "kg/kg",
        ),
        (0, 1, 219) => ("QMAX", "Maximum specific humidity at 2m", "kg/kg"),
        (0, 1, 220) => ("QMIN", "Minimum specific humidity at 2m", "kg/kg"),
        (0, 1, 221) => ("ARAIN", "Liquid precipitation (Rainfall)", "kg/m^2"),
        (0, 1, 222) => ("SNOWT", "Snow temperature, depth-avg", "K"),
        (0, 1, 223) => (
            "APCPN",
            "Total precipitation (nearest grid point)",
            "kg/m^2",
        ),
        (0, 1, 224) => (
            "ACPCPN",
            "Convective precipitation (nearest grid point)",
            "kg/m^2",
        ),
        (0, 1, 225) => ("FRZR", "Freezing Rain", "kg/m^2"),
        (0, 1, 226) => ("PWTHER", "Predominant Weather", "Numeric"),
        (0, 1, 227) => ("FROZR", "Frozen Rain", "kg/m^2"),
        (0, 1, 228) => ("FICEAC", "Flat Ice Accumulation (FRAM)", "kg/m^2"),
        (0, 1, 229) => ("LICEAC", "Line Ice Accumulation (FRAM)", "kg/m^2"),
        (0, 1, 230) => ("SLACC", "Sleet Accumulation", "kg/m^2"),
        (0, 1, 231) => ("PPINDX", "Precipitation Potential Index", "%"),
        (0, 1, 232) => ("PROBCIP", "Probability Cloud Ice Present", "%"),
        (0, 1, 233) => ("SNOWLR", "Snow Liquid ratio", "kg/kg"),
        (0, 1, 234) => ("PCPDUR", "Precipitation Duration", "hour"),
        (0, 1, 235) => ("CLLMR", "Cloud Liquid Mixing Ratio", "kg/kg"),
        (0, 1, 241) => ("TSNOW", "Total Snow", "kg/m^2"),
        (0, 1, 242) => (
            "RHPW",
            "Relative Humidity with Respect to Precipitable Water",
            "%",
        ),
        (0, 1, 245) => (
            "MAXVIG",
            "Hourly Maximum of Column Vertical Integrated Graupel on Entire Atmosphere",
            "kg/m^2",
        ),
        (0, 2, 192) => ("VWSH", "Vertical Speed Shear", "1/s"),
        (0, 2, 193) => ("MFLX", "Horizontal Momentum Flux", "N/m^2"),
        (0, 2, 194) => ("USTM", "U-Component Storm Motion", "m/s"),
        (0, 2, 195) => ("VSTM", "V-Component Storm Motion", "m/s"),
        (0, 2, 196) => ("CD", "Drag Coefficient", "non-dim"),
        (0, 2, 197) => ("FRICV", "Frictional Velocity", "m/s"),
        (0, 2, 198) => ("LAUV", "Latitude of U Wind Component of Velocity", "deg"),
        (0, 2, 199) => ("LOUV", "Longitude of U Wind Component of Velocity", "deg"),
        (0, 2, 200) => ("LAVV", "Latitude of V Wind Component of Velocity", "deg"),
        (0, 2, 201) => ("LOVV", "Longitude of V Wind Component of Velocity", "deg"),
        (0, 2, 202) => ("LAPP", "Latitude of Presure Point", "deg"),
        (0, 2, 203) => ("LOPP", "Longitude of Presure Point", "deg"),
        (0, 2, 204) => ("VEDH", "Vertical Eddy Diffusivity Heat exchange", "m^2/s"),
        (0, 2, 205) => (
            "COVMZ",
            "Covariance between Meridional and Zonal Components of the wind",
            "m^2/s^2",
        ),
        (0, 2, 206) => (
            "COVTZ",
            "Covariance between Temperature and Zonal Components of the wind",
            "K*m/s",
        ),
        (0, 2, 207) => (
            "COVTM",
            "Covariance between Temperature and Meridional Components of the wind",
            "K*m/s",
        ),
        (0, 2, 208) => ("VDFUA", "Vertical Diffusion Zonal Acceleration", "m/s^2"),
        (0, 2, 209) => (
            "VDFVA",
            "Vertical Diffusion Meridional Acceleration",
            "m/s^2",
        ),
        (0, 2, 210) => ("GWDU", "Gravity wave drag zonal acceleration", "m/s^2"),
        (0, 2, 211) => ("GWDV", "Gravity wave drag meridional acceleration", "m/s^2"),
        (0, 2, 212) => (
            "CNVU",
            "Convective zonal momentum mixing acceleration",
            "m/s^2",
        ),
        (0, 2, 213) => (
            "CNVV",
            "Convective meridional momentum mixing acceleration",
            "m/s^2",
        ),
        (0, 2, 214) => ("WTEND", "Tendency of vertical velocity", "m/s^2"),
        (0, 2, 215) => ("OMGALF", "Omega (Dp/Dt) divide by density", "K"),
        (0, 2, 216) => (
            "CNGWDU",
            "Convective Gravity wave drag zonal acceleration",
            "m/s^2",
        ),
        (0, 2, 217) => (
            "CNGWDV",
            "Convective Gravity wave drag meridional acceleration",
            "m/s^2",
        ),
        (0, 2, 218) => ("LMV", "Velocity Point Model Surface", "-"),
        (0, 2, 219) => ("PVMWW", "Potential Vorticity (Mass-Weighted)", "1/s/m"),
        (0, 2, 220) => (
            "MAXUVV",
            "Hourly Maximum of Upward Vertical Velocity",
            "m/s",
        ),
        (0, 2, 221) => (
            "MAXDVV",
            "Hourly Maximum of Downward Vertical Velocity",
            "m/s",
        ),
        (0, 2, 222) => (
            "MAXUW",
            "U Component of Hourly Maximum 10m Wind Speed",
            "m/s",
        ),
        (0, 2, 223) => (
            "MAXVW",
            "V Component of Hourly Maximum 10m Wind Speed",
            "m/s",
        ),
        (0, 2, 224) => ("VRATE", "Ventilation Rate", "m^2/s"),
        (0, 2, 225) => ("TRWSPD", "Transport Wind Speed", "m/s"),
        (0, 2, 226) => ("TRWDIR", "Transport Wind Direction", "deg"),
        (0, 2, 227) => (
            "TOA10",
            "Earliest Reasonable Arrival Time (10% exceedance)",
            "s",
        ),
        (0, 2, 228) => ("TOA50", "Most Likely Arrival Time (50% exceedance)", "s"),
        (0, 2, 229) => ("TOD50", "Most Likely Departure Time (50% exceedance)", "s"),
        (0, 2, 230) => (
            "TOD90",
            "Latest Reasonable Departure Time (90% exceedance)",
            "s",
        ),
        (0, 2, 231) => ("TPWDIR", "Tropical Wind Direction", "deg"),
        (0, 2, 232) => ("TPWSPD", "Tropical Wind Speed", "m/s"),
        (0, 2, 233) => (
            "ESHR",
            "Inflow Based (ESFC) to 50% EL Shear Magnitude",
            "kt",
        ),
        (0, 2, 234) => (
            "UESH",
            "U Component Inflow Based to 50% EL Shear Vector",
            "kt",
        ),
        (0, 2, 235) => (
            "VESH",
            "V Component Inflow Based to 50% EL Shear Vector",
            "kt",
        ),
        (0, 2, 236) => ("UEID", "U Component Bunkers Effective Right Motion", "kt"),
        (0, 2, 237) => ("VEID", "V Component Bunkers Effective Right Motion", "kt"),
        (0, 3, 192) => ("MSLET", "MSLP (Eta model reduction)", "Pa"),
        (0, 3, 193) => ("5WAVH", "5-Wave Geopotential Height", "gpm"),
        (0, 3, 194) => ("U-GWD", "Zonal Flux of Gravity Wave Stress", "N/m^2"),
        (0, 3, 195) => ("V-GWD", "Meridional Flux of Gravity Wave Stress", "N/m^2"),
        (0, 3, 196) => ("HPBL", "Planetary Boundary Layer Height", "m"),
        (0, 3, 197) => ("5WAVA", "5-Wave Geopotential Height Anomaly", "gpm"),
        (0, 3, 198) => ("MSLMA", "MSLP (MAPS System Reduction)", "Pa"),
        (0, 3, 199) => (
            "TSLSA",
            "3-hr pressure tendency (Std. Atmos. Reduction)",
            "Pa/s",
        ),
        (0, 3, 200) => (
            "PLPL",
            "Pressure of level from which parcel was lifted",
            "Pa",
        ),
        (0, 3, 201) => ("LPSX", "X-gradient of Log Pressure", "1/m"),
        (0, 3, 202) => ("LPSY", "Y-gradient of Log Pressure", "1/m"),
        (0, 3, 203) => ("HGTX", "X-gradient of Height", "1/m"),
        (0, 3, 204) => ("HGTY", "Y-gradient of Height", "1/m"),
        (0, 3, 205) => ("LAYTH", "Layer Thickness", "m"),
        (0, 3, 206) => ("NLGSP", "Natural Log of Surface Pressure", "ln(kPa)"),
        (0, 3, 207) => ("CNVUMF", "Convective updraft mass flux", "kg/m^2/s"),
        (0, 3, 208) => ("CNVDMF", "Convective downdraft mass flux", "kg/m^2/s"),
        (0, 3, 209) => ("CNVDEMF", "Convective detrainment mass flux", "kg/m^2/s"),
        (0, 3, 210) => ("LMH", "Mass Point Model Surface", "-"),
        (0, 3, 211) => ("HGTN", "Geopotential Height (nearest grid point)", "gpm"),
        (0, 3, 212) => ("PRESN", "Pressure (nearest grid point)", "Pa"),
        (0, 3, 213) => ("ORCONV", "Orographic Convexity", "-"),
        (0, 3, 214) => ("ORASW", "Orographic Asymmetry, W Component", "-"),
        (0, 3, 215) => ("ORASS", "Orographic Asymmetry, S Component", "-"),
        (0, 3, 216) => ("ORASSW", "Orographic Asymmetry, SW Component", "-"),
        (0, 3, 217) => ("ORASNW", "Orographic Asymmetry, NW Component", "-"),
        (0, 3, 218) => ("ORLSW", "Orographic Length Scale, W Component", "-"),
        (0, 3, 219) => ("ORLSS", "Orographic Length Scale, S Component", "-"),
        (0, 3, 220) => ("ORLSSW", "Orographic Length Scale, SW Component", "-"),
        (0, 3, 221) => ("ORLSNW", "Orographic Length Scale, NW Component", "-"),
        (0, 3, 222) => ("EFSH", "Effective Surface Height", "m"),
        (0, 4, 192) => ("DSWRF", "Downward Short-Wave Radiation Flux", "W/m^2"),
        (0, 4, 193) => ("USWRF", "Upward Short-Wave Radiation Flux", "W/m^2"),
        (0, 4, 194) => ("DUVB", "UV-B Downward Solar Flux", "W/m^2"),
        (0, 4, 195) => ("CDUVB", "Clear sky UV-B Downward Solar Flux", "W/m^2"),
        (0, 4, 196) => ("CSDSF", "Clear Sky Downward Solar Flux", "W/m^2"),
        (0, 4, 197) => ("SWHR", "Solar Radiative Heating Rate", "K/s"),
        (0, 4, 198) => ("CSUSF", "Clear Sky Upward Solar Flux", "W/m^2"),
        (0, 4, 199) => ("CFNSF", "Cloud Forcing Net Solar Flux", "W/m^2"),
        (0, 4, 200) => ("VBDSF", "Visible Beam Downward Solar Flux", "W/m^2"),
        (0, 4, 201) => ("VDDSF", "Visible Diffuse Downward Solar Flux", "W/m^2"),
        (0, 4, 202) => ("NBDSF", "Near IR Beam Downward Solar Flux", "W/m^2"),
        (0, 4, 203) => ("NDDSF", "Near IR Diffuse Downward Solar Flux", "W/m^2"),
        (0, 4, 204) => ("DTRF", "Downward Total Radiation Flux", "W/m^2"),
        (0, 4, 205) => ("UTRF", "Upward Total Radiation Flux", "W/m^2"),
        (0, 5, 192) => ("DLWRF", "Downward Long-Wave Rad. Flux", "W/m^2"),
        (0, 5, 193) => ("ULWRF", "Upward Long-Wave Rad. Flux", "W/m^2"),
        (0, 5, 194) => ("LWHR", "Long-Wave Radiative Heating Rate", "K/s"),
        (0, 5, 195) => ("CSULF", "Clear Sky Upward Long Wave Flux", "W/m^2"),
        (0, 5, 196) => ("CSDLF", "Clear Sky Downward Long Wave Flux", "W/m^2"),
        (0, 5, 197) => ("CFNLF", "Cloud Forcing Net Long Wave Flux", "W/m^2"),
        (0, 6, 192) => ("CDLYR", "Non-Convective Cloud Cover", "%"),
        (0, 6, 193) => ("CWORK", "Cloud Work Function", "J/kg"),
        (0, 6, 194) => ("CUEFI", "Convective Cloud Efficiency", "non-dim"),
        (0, 6, 195) => ("TCOND", "Total Condensate", "kg/kg"),
        (0, 6, 196) => ("TCOLW", "Total Column-Integrated Cloud Water", "kg/m^2"),
        (0, 6, 197) => ("TCOLI", "Total Column-Integrated Cloud Ice", "kg/m^2"),
        (0, 6, 198) => ("TCOLC", "Total Column-Integrated Condensate", "kg/m^2"),
        (0, 6, 199) => ("FICE", "Ice fraction of total condensate", "non-dim"),
        (0, 6, 200) => ("MFLUX", "Convective Cloud Mass Flux", "Pa/s"),
        (0, 6, 201) => ("SUNSD", "Sunshine Duration", "s"),
        (0, 7, 192) => ("LFTX", "Surface Lifted Index", "K"),
        (0, 7, 193) => ("4LFTX", "Best (4 layer) Lifted Index", "K"),
        (0, 7, 194) => ("RI", "Richardson Number", "Numeric"),
        (0, 7, 195) => ("CWDI", "Convective Weather Detection Index", "-"),
        (0, 7, 196) => ("UVI", "Ultra Violet Index", "W/m^2"),
        (0, 7, 197) => ("UPHL", "Updraft Helicity", "m^2/s^2"),
        (0, 7, 198) => ("LAI", "Leaf Area Index", "Numeric"),
        (0, 7, 199) => ("MXUPHL", "Hourly Maximum of Updraft Helicity", "m^2/s^2"),
        (0, 7, 200) => ("MNUPHL", "Hourly Minimum of Updraft Helicity", "m^2/s^2"),
        (0, 7, 201) => (
            "BNEGELAY",
            "Bourgoiun Negative Energy Layer (surface to freezing level)",
            "J/kg",
        ),
        (0, 7, 202) => (
            "BPOSELAY",
            "Bourgoiun Positive Energy Layer (2k ft AGL to 400 hPa)",
            "J/kg",
        ),
        (0, 7, 203) => ("DCAPE", "Downdraft CAPE", "J/kg"),
        (0, 7, 204) => ("EFHL", "Effective Storm Relative Helicity", "m^2/s^2"),
        (0, 7, 205) => ("ESP", "Enhanced Stretching Potential", "Numeric"),
        (0, 7, 206) => ("CANGLE", "Critical Angle", "degree"),
        (0, 7, 207) => ("E3KH", "Effective Surface Helicity", "m^2/s^2"),
        (0, 7, 208) => (
            "STPC",
            "Significant Tornado Parameter with CIN-Effective Layer",
            "Numeric",
        ),
        (0, 7, 209) => ("SIGH", "Significant Hail Parameter", "Numeric"),
        (0, 7, 210) => (
            "SCCP",
            "Supercell Composite Parameter-Effective Layer",
            "Numeric",
        ),
        (0, 7, 211) => (
            "SIGT",
            "Significant Tornado parameter-Fixed Layer",
            "Numeric",
        ),
        (0, 7, 212) => ("MLFC", "Mixed Layer (100 mb) Virtual LFC", "Numeric"),
        (0, 13, 192) => ("PMTC", "Particulate matter (coarse)", "10^-6g/m^3"),
        (0, 13, 193) => ("PMTF", "Particulate matter (fine)", "10^-6g/m^3"),
        (0, 13, 194) => ("LPMTF", "Particulate matter (fine)", "log10(10^-6g/m^3)"),
        (0, 13, 195) => (
            "LIPMF",
            "Integrated column particulate matter (fine)",
            "log10(10^-6g/m^3)",
        ),
        (0, 14, 192) => ("O3MR", "Ozone Mixing Ratio", "kg/kg"),
        (0, 14, 193) => ("OZCON", "Ozone Concentration", "ppb"),
        (0, 14, 194) => ("OZCAT", "Categorical Ozone Concentration", "non-dim"),
        (0, 14, 195) => ("VDFOZ", "Ozone Vertical Diffusion", "kg/kg/s"),
        (0, 14, 196) => ("POZ", "Ozone Production", "kg/kg/s"),
        (0, 14, 197) => ("TOZ", "Ozone Tendency", "kg/kg/s"),
        (0, 14, 198) => ("POZT", "Ozone Production from Temperature Term", "kg/kg/s"),
        (0, 14, 199) => ("POZO", "Ozone Production from Column Ozone Term", "kg/kg/s"),
        (0, 14, 200) => ("OZMAX1", "Ozone Daily Max from 1-hour Average", "ppbV"),
        (0, 14, 201) => ("OZMAX8", "Ozone Daily Max from 8-hour Average", "ppbV"),
        (0, 14, 202) => (
            "PDMAX1",
            "PM 2.5 Daily Max from 1-hour Average",
            "10^-6g/m^3",
        ),
        (0, 14, 203) => (
            "PDMAX24",
            "PM 2.5 Daily Max from 24-hour Average",
            "10^-6g/m^3",
        ),
        (0, 14, 204) => ("ALD2", "Acetaldehyde & Higher Aldehydes", "ppbV"),
        (0, 16, 192) => (
            "REFZR",
            "Equivalent radar reflectivity factor for rain",
            "mm^6/m^3",
        ),
        (0, 16, 193) => (
            "REFZI",
            "Equivalent radar reflectivity factor for snow",
            "mm^6/m^3",
        ),
        (0, 16, 194) => (
            "REFZC",
            "Equivalent radar reflectivity factor for parameterized convection",
            "mm^6/m^3",
        ),
        (0, 16, 195) => ("REFD", "Reflectivity", "dB"),
        (0, 16, 196) => ("REFC", "Composite reflectivity", "dB"),
        (0, 16, 197) => ("RETOP", "Echo Top", "m"),
        (0, 16, 198) => ("MAXREF", "Hourly Maximum of Simulated Reflectivity", "dB"),
        (0, 17, 192) => ("LTNG", "Lightning", "non-dim"),
        (0, 19, 192) => ("MXSALB", "Maximum Snow Albedo", "%"),
        (0, 19, 193) => ("SNFALB", "Snow-Free Albedo", "%"),
        (0, 19, 194) => ("SRCONO", "Slight risk convective outlook", "Categorical"),
        (0, 19, 195) => ("MRCONO", "Moderate risk convective outlook", "Categorical"),
        (0, 19, 196) => ("HRCONO", "High risk convective outlook", "Categorical"),
        (0, 19, 197) => ("TORPROB", "Tornado probability", "%"),
        (0, 19, 198) => ("HAILPROB", "Hail probability", "%"),
        (0, 19, 199) => ("WINDPROB", "Wind probability", "%"),
        (0, 19, 200) => ("STORPROB", "Significant Tornado probability", "%"),
        (0, 19, 201) => ("SHAILPRO", "Significant Hail probability", "%"),
        (0, 19, 202) => ("SWINDPRO", "Significant Wind probability", "%"),
        (0, 19, 203) => ("TSTMC", "Categorical Thunderstorm", "-"),
        (0, 19, 204) => ("MIXLY", "Number of mixed layers next to surface", "Integer"),
        (0, 19, 205) => ("FLGHT", "Flight Category", "-"),
        (0, 19, 206) => ("CICEL", "Confidence - Ceiling", "-"),
        (0, 19, 207) => ("CIVIS", "Confidence - Visibility", "-"),
        (0, 19, 208) => ("CIFLT", "Confidence - Flight Category", "-"),
        (0, 19, 209) => ("LAVNI", "Low-Level aviation interest", "-"),
        (0, 19, 210) => ("HAVNI", "High-Level aviation interest", "-"),
        (0, 19, 211) => ("SBSALB", "Visible, Black Sky Albedo", "%"),
        (0, 19, 212) => ("SWSALB", "Visible, White Sky Albedo", "%"),
        (0, 19, 213) => ("NBSALB", "Near IR, Black Sky Albedo", "%"),
        (0, 19, 214) => ("NWSALB", "Near IR, White Sky Albedo", "%"),
        (0, 19, 215) => (
            "PRSVR",
            "Total Probability of Severe Thunderstorms (Days 2,3)",
            "%",
        ),
        (0, 19, 216) => (
            "PRSIGSVR",
            "Total Probability of Extreme Severe Thunderstorms (Days 2,3)",
            "%",
        ),
        (0, 19, 217) => ("SIPD", "Supercooled Large Droplet (SLD) Icing", "-"),
        (0, 19, 218) => ("EPSR", "Radiative emissivity", "-"),
        (0, 19, 219) => ("TPFI", "Turbulence Potential Forecast Index", "-"),
        (0, 19, 220) => ("SVRTS", "Categorical Severe Thunderstorm", "-"),
        (0, 19, 221) => ("PROCON", "Probability of Convection", "%"),
        (0, 19, 222) => ("CONVP", "Convection Potential", "-"),
        (0, 19, 232) => (
            "VAFTD",
            "Volcanic Ash Forecast Transport and Dispersion",
            "log10(kg/m^3)",
        ),
        (0, 19, 233) => ("ICPRB", "Icing probability", "non-dim"),
        (0, 19, 234) => ("ICSEV", "Icing Severity", "non-dim"),
        (0, 19, 235) => ("JFWPRB", "Joint Fire Weather Probability", "%"),
        (0, 19, 236) => ("SNOWLVL", "Snow Level", "m"),
        (0, 19, 237) => ("DRYTPROB", "Dry Thunderstorm Probability", "%"),
        (0, 19, 238) => ("ELLINX", "Ellrod Index", "-"),
        (0, 19, 239) => (
            "CWASP",
            "Craven-Wiedenfeld Aggregate Severe Parameter",
            "Numeric",
        ),
        (0, 19, 240) => ("ICESEVCON", "Continuous Icing Severity", "non-dim"),
        (0, 191, 192) => ("NLAT", "Latitude (-90 to 90)", "deg"),
        (0, 191, 193) => ("ELON", "East Longitude (0 to 360)", "deg"),
        (0, 191, 194) => ("RTSEC", "Seconds prior to initial reference time", "s"),
        (0, 191, 195) => ("MLYNO", "Model Layer number (From bottom up)", "-"),
        (0, 191, 196) => ("NLATN", "Latitude (nearest neighbor) (-90 to 90)", "deg"),
        (0, 191, 197) => (
            "ELONN",
            "East Longitude (nearest neighbor) (0 to 360)",
            "deg",
        ),
        (0, 192, 1) => (
            "COVMZ",
            "Covariance between zonal and meridional components of the wind. Defined as [uv]-[u][v], where [] indicates the mean over the indicated time span",
            "m^2/s^2",
        ),
        (0, 192, 2) => (
            "COVTZ",
            "Covariance between zonal component of the wind and temperature. Defined as [uT]-[u][T], where [] indicates the mean over the indicated time span",
            "K*m/s",
        ),
        (0, 192, 3) => (
            "COVTM",
            "Covariance between meridional component of the wind and temperature. Defined as [vT]-[v][T], where [] indicates the mean over the indicated time span",
            "K*m/s",
        ),
        (0, 192, 4) => (
            "COVTW",
            "Covariance between temperature and vertical component of the wind. Defined as [wT]-[w][T], where [] indicates the mean over the indicated time span",
            "K*m/s",
        ),
        (0, 192, 5) => (
            "COVZZ",
            "Covariance between zonal and zonal components of the wind. Defined as [uu]-[u][u], where [] indicates the mean over the indicated time span",
            "m^2/s^2",
        ),
        (0, 192, 6) => (
            "COVMM",
            "Covariance between meridional and meridional components of the wind. Defined as [vv]-[v][v], where [] indicates the mean over the indicated time span",
            "m^2/s^2",
        ),
        (0, 192, 7) => (
            "COVQZ",
            "Covariance between specific humidity and zonal components of the wind. Defined as [uq]-[u][q], where [] indicates the mean over the indicated time span",
            "kg/kg*m/s",
        ),
        (0, 192, 8) => (
            "COVQM",
            "Covariance between specific humidity and meridional components of the wind. Defined as [vq]-[v][q], where [] indicates the mean over the indicated time span",
            "kg/kg*m/s",
        ),
        (0, 192, 9) => (
            "COVTVV",
            "Covariance between temperature and vertical components of the wind. Defined as [OmegaT]-[Omega][T], where [] indicates the mean over the indicated time span",
            "K*Pa/s",
        ),
        (0, 192, 10) => (
            "COVQVV",
            "Covariance between specific humidity and vertical components of the wind. Defined as [Omegaq]-[Omega][q], where [] indicates the mean over the indicated time span",
            "kg/kg*Pa/s",
        ),
        (0, 192, 11) => (
            "COVPSPS",
            "Covariance between surface pressure and surface pressure. Defined as [Psfc]-[Psfc][Psfc], where [] indicates the mean over the indicated time span",
            "Pa*Pa",
        ),
        (0, 192, 12) => (
            "COVQQ",
            "Covariance between specific humidity and specific humidy. Defined as [qq]-[q][q], where [] indicates the mean over the indicated time span",
            "kg/kg*kg/kg",
        ),
        (0, 192, 13) => (
            "COVVVVV",
            "Covariance between vertical and vertical components of the wind. Defined as [OmegaOmega]-[Omega][Omega], where [] indicates the mean over the indicated time span",
            "Pa^2/s^2",
        ),
        (0, 192, 14) => (
            "COVTT",
            "Covariance between temperature and temperature. Defined as [TT]-[T][T], where [] indicates the mean over the indicated time span",
            "K*K",
        ),
        (1, 0, 192) => ("BGRUN", "Baseflow-Groundwater Runoff", "kg/m^2"),
        (1, 0, 193) => ("SSRUN", "Storm Surface Runoff", "kg/m^2"),
        (1, 0, 194) => ("FHO", "Flood Hazard Outlook", "-"),
        (1, 0, 196) => ("AHD", "Area Hydrologic Discussion", "-"),
        (1, 1, 192) => ("CPOZP", "Probability of Freezing Precipitation", "%"),
        (1, 1, 193) => ("CPOFP", "Percent of Frozen Precipitation", "%"),
        (1, 1, 194) => (
            "PPFFG",
            "Probability of precipitation exceeding flash flood guidance values",
            "%",
        ),
        (1, 1, 195) => (
            "CWR",
            "Probability of Wetting Rain, exceeding in 0.10 in a given time period",
            "%",
        ),
        (1, 1, 196) => (
            "QPFARI",
            "Binary Probability of precipitation exceeding average recurrence intervals (ARI)",
            "-",
        ),
        (1, 1, 197) => (
            "QPFFFG",
            "Binary Probability of precipitation exceeding flash flood guidance values",
            "-",
        ),
        (2, 0, 192) => ("SOILW", "Volumetric Soil Moisture Content", "Fraction"),
        (2, 0, 193) => ("GFLUX", "Ground Heat Flux", "W/m^2"),
        (2, 0, 194) => ("MSTAV", "Moisture Availability", "%"),
        (2, 0, 195) => ("SFEXC", "Exchange Coefficient", "kg/m^2/s"),
        (2, 0, 196) => ("CNWAT", "Plant Canopy Surface Water", "kg/m^2"),
        (2, 0, 197) => ("BMIXL", "Blackadars Mixing Length Scale", "m"),
        (2, 0, 198) => ("VGTYP", "Vegetation Type", "Integer(0-13)"),
        (2, 0, 199) => ("CCOND", "Canopy Conductance", "m/s"),
        (2, 0, 200) => ("RSMIN", "Minimal Stomatal Resistance", "s/m"),
        (2, 0, 201) => ("WILT", "Wilting Point", "Fraction"),
        (2, 0, 202) => ("RCS", "Solar parameter in canopy conductance", "Fraction"),
        (2, 0, 203) => (
            "RCT",
            "Temperature parameter in canopy conductance",
            "Fraction",
        ),
        (2, 0, 204) => (
            "RCQ",
            "Humidity parameter in canopy conductance",
            "Fraction",
        ),
        (2, 0, 205) => (
            "RCSOL",
            "Soil moisture parameter in canopy conductance",
            "Fraction",
        ),
        (2, 0, 206) => ("RDRIP", "Rate of water dropping from canopy to ground", "-"),
        (2, 0, 207) => ("ICWAT", "Ice-free water surface", "%"),
        (2, 0, 208) => (
            "AKHS",
            "Surface exchange coefficients for T and Q divided by delta z",
            "m/s",
        ),
        (2, 0, 209) => (
            "AKMS",
            "Surface exchange coefficients for U and V divided by delta z",
            "m/s",
        ),
        (2, 0, 210) => ("VEGT", "Vegetation canopy temperature", "K"),
        (2, 0, 211) => ("SSTOR", "Surface water storage", "kg/m^2"),
        (2, 0, 212) => (
            "LSOIL",
            "Liquid soil moisture content (non-frozen)",
            "kg/m^2",
        ),
        (2, 0, 213) => ("EWATR", "Open water evaporation (standing water)", "W/m^2"),
        (2, 0, 214) => ("GWREC", "Groundwater recharge", "kg/m^2"),
        (2, 0, 215) => ("QREC", "Flood plain recharge", "kg/m^2"),
        (2, 0, 216) => ("SFCRH", "Roughness length for heat", "m"),
        (2, 0, 217) => ("NDVI", "Normalized Difference Vegetation Index", "-"),
        (2, 0, 218) => (
            "LANDN",
            "Land-sea coverage (nearest neighbor) [land=1,sea=0]",
            "-",
        ),
        (2, 0, 219) => ("AMIXL", "Asymptotic mixing length scale", "m"),
        (2, 0, 220) => (
            "WVINC",
            "Water vapor added by precip assimilation",
            "kg/m^2",
        ),
        (2, 0, 221) => (
            "WCINC",
            "Water condensate added by precip assimilation",
            "kg/m^2",
        ),
        (2, 0, 222) => (
            "WVCONV",
            "Water Vapor Flux Convergance (Vertical Int)",
            "kg/m^2",
        ),
        (2, 0, 223) => (
            "WCCONV",
            "Water Condensate Flux Convergance (Vertical Int)",
            "kg/m^2",
        ),
        (2, 0, 224) => ("WVUFLX", "Water Vapor Zonal Flux (Vertical Int)", "kg/m^2"),
        (2, 0, 225) => (
            "WVVFLX",
            "Water Vapor Meridional Flux (Vertical Int)",
            "kg/m^2",
        ),
        (2, 0, 226) => (
            "WCUFLX",
            "Water Condensate Zonal Flux (Vertical Int)",
            "kg/m^2",
        ),
        (2, 0, 227) => (
            "WCVFLX",
            "Water Condensate Meridional Flux (Vertical Int)",
            "kg/m^2",
        ),
        (2, 0, 228) => ("ACOND", "Aerodynamic conductance", "m/s"),
        (2, 0, 229) => ("EVCW", "Canopy water evaporation", "W/m^2"),
        (2, 0, 230) => ("TRANS", "Transpiration", "W/m^2"),
        (2, 0, 231) => (
            "VEGMIN",
            "Seasonally Minimum Green Vegetation Fraction (over 1-year period)",
            "%",
        ),
        (2, 0, 232) => (
            "VEGMAX",
            "Seasonally Maximum Green Vegetation Fraction (over 1-year period)",
            "%",
        ),
        (2, 0, 233) => ("LANDFRC", "Land Fraction", "Fraction"),
        (2, 0, 234) => ("LAKEFRC", "Lake Fraction", "Fraction"),
        (2, 0, 235) => ("PAHFLX", "Precipitation Advected Heat Flux", "W/m^2"),
        (2, 0, 236) => ("WATERSA", "Water Storage in Aquifer", "kg/m^2"),
        (2, 0, 237) => ("EIWATER", "Evaporation of Intercepted Water", "kg/m^2"),
        (2, 0, 238) => ("PLANTTR", "Plant Transpiration", "kg/m^2"),
        (2, 0, 239) => ("SOILSE", "Soil Surface Evaporation", "kg/m^2"),
        (2, 1, 192) => ("CANL", "Cold Advisory for Newborn Livestock", "-"),
        (2, 3, 192) => (
            "SOILL",
            "Liquid Volumetric Soil Moisture (non Frozen)",
            "Proportion",
        ),
        (2, 3, 193) => ("RLYRS", "Number of Soil Layers in Root Zone", "non-dim"),
        (2, 3, 194) => ("SLTYP", "Surface Slope Type", "Index"),
        (2, 3, 195) => (
            "SMREF",
            "Transpiration Stress-onset (soil moisture)",
            "Proportion",
        ),
        (2, 3, 196) => (
            "SMDRY",
            "Direct Evaporation Cease (soil moisture)",
            "Proportion",
        ),
        (2, 3, 197) => ("POROS", "Soil Porosity", "Proportion"),
        (2, 3, 198) => ("EVBS", "Direct Evaporation from Bare Soil", "W/m^2"),
        (2, 3, 199) => ("LSPA", "Land Surface Precipitation Accumulation", "kg/m^2"),
        (2, 3, 200) => ("BARET", "Bare Soil Surface Skin temperature", "K"),
        (2, 3, 201) => ("AVSFT", "Average Surface Skin Temperature", "K"),
        (2, 3, 202) => ("RADT", "Effective Radiative Skin Temperature", "K"),
        (2, 3, 203) => ("FLDCP", "Field Capacity", "Fraction"),
        (2, 3, 204) => (
            "MSTAV",
            "Soil Moisture Availability In The Top Soil Layer",
            "%",
        ),
        (3, 1, 192) => ("USCT", "Scatterometer Estimated U Wind Component", "m/s"),
        (3, 1, 193) => ("VSCT", "Scatterometer Estimated V Wind Component", "m/s"),
        (3, 1, 194) => ("SWQI", "Scatterometer Wind Quality", "-"),
        (3, 192, 0) => (
            "SBT122",
            "Simulated Brightness Temperature for GOES 12, Channel 2",
            "K",
        ),
        (3, 192, 1) => (
            "SBT123",
            "Simulated Brightness Temperature for GOES 12, Channel 3",
            "K",
        ),
        (3, 192, 2) => (
            "SBT124",
            "Simulated Brightness Temperature for GOES 12, Channel 4",
            "K",
        ),
        (3, 192, 3) => (
            "SBT126",
            "Simulated Brightness Temperature for GOES 12, Channel 6",
            "K",
        ),
        (3, 192, 4) => (
            "SBC123",
            "Simulated Brightness Counts for GOES 12, Channel 3",
            "Byte",
        ),
        (3, 192, 5) => (
            "SBC124",
            "Simulated Brightness Counts for GOES 12, Channel 4",
            "Byte",
        ),
        (3, 192, 6) => (
            "SBT112",
            "Simulated Brightness Temperature for GOES 11, Channel 2",
            "K",
        ),
        (3, 192, 7) => (
            "SBT113",
            "Simulated Brightness Temperature for GOES 11, Channel 3",
            "K",
        ),
        (3, 192, 8) => (
            "SBT114",
            "Simulated Brightness Temperature for GOES 11, Channel 4",
            "K",
        ),
        (3, 192, 9) => (
            "SBT115",
            "Simulated Brightness Temperature for GOES 11, Channel 5",
            "K",
        ),
        (3, 192, 10) => (
            "AMSRE9",
            "Simulated Brightness Temperature for AMSRE on Aqua, Channel 9",
            "K",
        ),
        (3, 192, 11) => (
            "AMSRE10",
            "Simulated Brightness Temperature for AMSRE on Aqua, Channel 10",
            "K",
        ),
        (3, 192, 12) => (
            "AMSRE11",
            "Simulated Brightness Temperature for AMSRE on Aqua, Channel 11",
            "K",
        ),
        (3, 192, 13) => (
            "AMSRE12",
            "Simulated Brightness Temperature for AMSRE on Aqua, Channel 12",
            "K",
        ),
        (3, 192, 14) => (
            "SRFA161",
            "Simulated Reflectance Factor for ABI GOES-16, Band-1",
            "-",
        ),
        (3, 192, 15) => (
            "SRFA162",
            "Simulated Reflectance Factor for ABI GOES-16, Band-2",
            "-",
        ),
        (3, 192, 16) => (
            "SRFA163",
            "Simulated Reflectance Factor for ABI GOES-16, Band-3",
            "-",
        ),
        (3, 192, 17) => (
            "SRFA164",
            "Simulated Reflectance Factor for ABI GOES-16, Band-4",
            "-",
        ),
        (3, 192, 18) => (
            "SRFA165",
            "Simulated Reflectance Factor for ABI GOES-16, Band-5",
            "-",
        ),
        (3, 192, 19) => (
            "SRFA166",
            "Simulated Reflectance Factor for ABI GOES-16, Band-6",
            "-",
        ),
        (3, 192, 20) => (
            "SBTA167",
            "Simulated Brightness Temperature for ABI GOES-16, Band-7",
            "K",
        ),
        (3, 192, 21) => (
            "SBTA168",
            "Simulated Brightness Temperature for ABI GOES-16, Band-8",
            "K",
        ),
        (3, 192, 22) => (
            "SBTA169",
            "Simulated Brightness Temperature for ABI GOES-16, Band-9",
            "K",
        ),
        (3, 192, 23) => (
            "SBTA1610",
            "Simulated Brightness Temperature for ABI GOES-16, Band-10",
            "K",
        ),
        (3, 192, 24) => (
            "SBTA1611",
            "Simulated Brightness Temperature for ABI GOES-16, Band-11",
            "K",
        ),
        (3, 192, 25) => (
            "SBTA1612",
            "Simulated Brightness Temperature for ABI GOES-16, Band-12",
            "K",
        ),
        (3, 192, 26) => (
            "SBTA1613",
            "Simulated Brightness Temperature for ABI GOES-16, Band-13",
            "K",
        ),
        (3, 192, 27) => (
            "SBTA1614",
            "Simulated Brightness Temperature for ABI GOES-16, Band-14",
            "K",
        ),
        (3, 192, 28) => (
            "SBTA1615",
            "Simulated Brightness Temperature for ABI GOES-16, Band-15",
            "K",
        ),
        (3, 192, 29) => (
            "SBTA1616",
            "Simulated Brightness Temperature for ABI GOES-16, Band-16",
            "K",
        ),
        (3, 192, 30) => (
            "SRFA171",
            "Simulated Reflectance Factor for ABI GOES-17, Band-1",
            "-",
        ),
        (3, 192, 31) => (
            "SRFA172",
            "Simulated Reflectance Factor for ABI GOES-17, Band-2",
            "-",
        ),
        (3, 192, 32) => (
            "SRFA173",
            "Simulated Reflectance Factor for ABI GOES-17, Band-3",
            "-",
        ),
        (3, 192, 33) => (
            "SRFA174",
            "Simulated Reflectance Factor for ABI GOES-17, Band-4",
            "-",
        ),
        (3, 192, 34) => (
            "SRFA175",
            "Simulated Reflectance Factor for ABI GOES-17, Band-5",
            "-",
        ),
        (3, 192, 35) => (
            "SRFA176",
            "Simulated Reflectance Factor for ABI GOES-17, Band-6",
            "-",
        ),
        (3, 192, 36) => (
            "SBTA177",
            "Simulated Brightness Temperature for ABI GOES-17, Band-7",
            "K",
        ),
        (3, 192, 37) => (
            "SBTA178",
            "Simulated Brightness Temperature for ABI GOES-17, Band-8",
            "K",
        ),
        (3, 192, 38) => (
            "SBTA179",
            "Simulated Brightness Temperature for ABI GOES-17, Band-9",
            "K",
        ),
        (3, 192, 39) => (
            "SBTA1710",
            "Simulated Brightness Temperature for ABI GOES-17, Band-10",
            "K",
        ),
        (3, 192, 40) => (
            "SBTA1711",
            "Simulated Brightness Temperature for ABI GOES-17, Band-11",
            "K",
        ),
        (3, 192, 41) => (
            "SBTA1712",
            "Simulated Brightness Temperature for ABI GOES-17, Band-12",
            "K",
        ),
        (3, 192, 42) => (
            "SBTA1713",
            "Simulated Brightness Temperature for ABI GOES-17, Band-13",
            "K",
        ),
        (3, 192, 43) => (
            "SBTA1714",
            "Simulated Brightness Temperature for ABI GOES-17, Band-14",
            "K",
        ),
        (3, 192, 44) => (
            "SBTA1715",
            "Simulated Brightness Temperature for ABI GOES-17, Band-15",
            "K",
        ),
        (3, 192, 45) => (
            "SBTA1716",
            "Simulated Brightness Temperature for ABI GOES-17, Band-16",
            "K",
        ),
        (3, 192, 46) => (
            "SRFAGR1",
            "Simulated Reflectance Factor for nadir ABI GOES-R, Band-1",
            "-",
        ),
        (3, 192, 47) => (
            "SRFAGR2",
            "Simulated Reflectance Factor for nadir ABI GOES-R, Band-2",
            "-",
        ),
        (3, 192, 48) => (
            "SRFAGR3",
            "Simulated Reflectance Factor for nadir ABI GOES-R, Band-3",
            "-",
        ),
        (3, 192, 49) => (
            "SRFAGR4",
            "Simulated Reflectance Factor for nadir ABI GOES-R, Band-4",
            "-",
        ),
        (3, 192, 50) => (
            "SRFAGR5",
            "Simulated Reflectance Factor for nadir ABI GOES-R, Band-5",
            "-",
        ),
        (3, 192, 51) => (
            "SRFAGR6",
            "Simulated Reflectance Factor for nadir ABI GOES-R, Band-6",
            "-",
        ),
        (3, 192, 52) => (
            "SBTAGR7",
            "Simulated Brightness Temperature for nadir ABI GOES-R, Band-7",
            "-",
        ),
        (3, 192, 53) => (
            "SBTAGR8",
            "Simulated Brightness Temperature for nadir ABI GOES-R, Band-8",
            "-",
        ),
        (3, 192, 54) => (
            "SBTAGR9",
            "Simulated Brightness Temperature for nadir ABI GOES-R, Band-9",
            "-",
        ),
        (3, 192, 55) => (
            "SBTAGR10",
            "Simulated Brightness Temperature for nadir ABI GOES-R, Band-10",
            "-",
        ),
        (3, 192, 56) => (
            "SBTAGR11",
            "Simulated Brightness Temperature for nadir ABI GOES-R, Band-11",
            "-",
        ),
        (3, 192, 57) => (
            "SBTAGR12",
            "Simulated Brightness Temperature for nadir ABI GOES-R, Band-12",
            "-",
        ),
        (3, 192, 58) => (
            "SBTAGR13",
            "Simulated Brightness Temperature for nadir ABI GOES-R, Band-13",
            "-",
        ),
        (3, 192, 59) => (
            "SBTAGR14",
            "Simulated Brightness Temperature for nadir ABI GOES-R, Band-14",
            "-",
        ),
        (3, 192, 60) => (
            "SBTAGR15",
            "Simulated Brightness Temperature for nadir ABI GOES-R, Band-15",
            "-",
        ),
        (3, 192, 61) => (
            "SBTAGR16",
            "Simulated Brightness Temperature for nadir ABI GOES-R, Band-16",
            "-",
        ),
        (3, 192, 62) => (
            "SSMS1715",
            "Simulated Brightness Temperature for SSMIS-F17, Channel 15",
            "K",
        ),
        (3, 192, 63) => (
            "SSMS1716",
            "Simulated Brightness Temperature for SSMIS-F17, Channel 16",
            "K",
        ),
        (3, 192, 64) => (
            "SSMS1717",
            "Simulated Brightness Temperature for SSMIS-F17, Channel 17",
            "K",
        ),
        (3, 192, 65) => (
            "SSMS1718",
            "Simulated Brightness Temperature for SSMIS-F17, Channel 18",
            "K",
        ),
        (3, 192, 66) => (
            "SBTAHI7",
            "Simulated Brightness Temperature for Himawari-8, Band-7",
            "K",
        ),
        (3, 192, 67) => (
            "SBTAHI8",
            "Simulated Brightness Temperature for Himawari-8, Band-8",
            "K",
        ),
        (3, 192, 68) => (
            "SBTAHI9",
            "Simulated Brightness Temperature for Himawari-8, Band-9",
            "K",
        ),
        (3, 192, 69) => (
            "SBTAHI10",
            "Simulated Brightness Temperature for Himawari-8, Band-10",
            "K",
        ),
        (3, 192, 70) => (
            "SBTAHI11",
            "Simulated Brightness Temperature for Himawari-8, Band-11",
            "K",
        ),
        (3, 192, 71) => (
            "SBTAHI12",
            "Simulated Brightness Temperature for Himawari-8, Band-12",
            "K",
        ),
        (3, 192, 72) => (
            "SBTAHI13",
            "Simulated Brightness Temperature for Himawari-8, Band-13",
            "K",
        ),
        (3, 192, 73) => (
            "SBTAHI14",
            "Simulated Brightness Temperature for Himawari-8, Band-14",
            "K",
        ),
        (3, 192, 74) => (
            "SBTAHI15",
            "Simulated Brightness Temperature for Himawari-8, Band-15",
            "K",
        ),
        (3, 192, 75) => (
            "SBTAHI16",
            "Simulated Brightness Temperature for Himawari-8, Band-16",
            "K",
        ),
        (3, 192, 76) => (
            "SBTA187",
            "Simulated Brightness Temperature for ABI GOES-18, Band-7",
            "K",
        ),
        (3, 192, 77) => (
            "SBTA188",
            "Simulated Brightness Temperature for ABI GOES-18, Band-8",
            "K",
        ),
        (3, 192, 78) => (
            "SBTA189",
            "Simulated Brightness Temperature for ABI GOES-18, Band-9",
            "K",
        ),
        (3, 192, 79) => (
            "SBTA1810",
            "Simulated Brightness Temperature for ABI GOES-18, Band-10",
            "K",
        ),
        (3, 192, 80) => (
            "SBTA1811",
            "Simulated Brightness Temperature for ABI GOES-18, Band-11",
            "K",
        ),
        (3, 192, 81) => (
            "SBTA1812",
            "Simulated Brightness Temperature for ABI GOES-18, Band-12",
            "K",
        ),
        (3, 192, 82) => (
            "SBTA1813",
            "Simulated Brightness Temperature for ABI GOES-18, Band-13",
            "K",
        ),
        (3, 192, 83) => (
            "SBTA1814",
            "Simulated Brightness Temperature for ABI GOES-18, Band-14",
            "K",
        ),
        (3, 192, 84) => (
            "SBTA1815",
            "Simulated Brightness Temperature for ABI GOES-18, Band-15",
            "K",
        ),
        (3, 192, 85) => (
            "SBTA1816",
            "Simulated Brightness Temperature for ABI GOES-18, Band-16",
            "K",
        ),
        (10, 0, 192) => ("WSTP", "Wave Steepness", "Proportion"),
        (10, 0, 193) => ("WLENG", "Wave Length", "-"),
        (10, 1, 192) => ("OMLU", "Ocean Mixed Layer U Velocity", "m/s"),
        (10, 1, 193) => ("OMLV", "Ocean Mixed Layer V Velocity", "m/s"),
        (10, 1, 194) => ("UBARO", "Barotropic U velocity", "m/s"),
        (10, 1, 195) => ("VBARO", "Barotropic V velocity", "m/s"),
        (10, 3, 192) => ("SURGE", "Hurricane Storm Surge", "m"),
        (10, 3, 193) => ("ETSRG", "Extra Tropical Storm Surge", "m"),
        (10, 3, 194) => ("ELEV", "Ocean Surface Elevation Relative to Geoid", "m"),
        (10, 3, 195) => ("SSHG", "Sea Surface Height Relative to Geoid", "m"),
        (10, 3, 196) => (
            "P2OMLT",
            "Ocean Mixed Layer Potential Density (Reference 2000m)",
            "kg/m^3",
        ),
        (10, 3, 197) => ("AOHFLX", "Net Air-Ocean Heat Flux", "W/m^2"),
        (10, 3, 198) => ("ASHFL", "Assimilative Heat Flux", "W/m^2"),
        (10, 3, 199) => ("SSTT", "Surface Temperature Trend", "K/day"),
        (10, 3, 200) => ("SSST", "Surface Salinity Trend", "psu/day"),
        (10, 3, 201) => ("KENG", "Kinetic Energy", "J/kg"),
        (10, 3, 202) => ("SLTFL", "Salt Flux", "kg/m^2/s"),
        (10, 3, 203) => ("LCH", "Heat Exchange Coefficient", "-"),
        (10, 3, 204) => ("FRZSPR", "Freezing Spray", "-"),
        (10, 3, 205) => (
            "TWLWAV",
            "Total Water Level Accounting for Tide, Wind and Waves",
            "m",
        ),
        (10, 3, 206) => ("RUNUP", "Total Water Level Increase due to Waves", "m"),
        (10, 3, 207) => ("SETUP", "Mean Increase in Water Level due to Waves", "m"),
        (10, 3, 208) => (
            "SWASH",
            "Time-varying Increase in Water Level due to Waves",
            "m",
        ),
        (10, 3, 209) => ("TWLDT", "Total Water Level Above Dune Toe", "m"),
        (10, 3, 210) => ("TWLDC", "Total Water Level Above Dune Crest", "m"),
        (10, 3, 242) => (
            "TCSRG20",
            "20% Tropical Cyclone Storm Surge Exceedance",
            "m",
        ),
        (10, 3, 243) => (
            "TCSRG30",
            "30% Tropical Cyclone Storm Surge Exceedance",
            "m",
        ),
        (10, 3, 244) => (
            "TCSRG40",
            "40% Tropical Cyclone Storm Surge Exceedance",
            "m",
        ),
        (10, 3, 245) => (
            "TCSRG50",
            "50% Tropical Cyclone Storm Surge Exceedance",
            "m",
        ),
        (10, 3, 246) => (
            "TCSRG60",
            "60% Tropical Cyclone Storm Surge Exceedance",
            "m",
        ),
        (10, 3, 247) => (
            "TCSRG70",
            "70% Tropical Cyclone Storm Surge Exceedance",
            "m",
        ),
        (10, 3, 248) => (
            "TCSRG80",
            "80% Tropical Cyclone Storm Surge Exceedance",
            "m",
        ),
        (10, 3, 249) => (
            "TCSRG90",
            "90% Tropical Cyclone Storm Surge Exceedance",
            "m",
        ),
        (10, 3, 250) => (
            "ETCWL",
            "Extra Tropical Storm Surge Combined Surge and Tide",
            "m",
        ),
        (10, 3, 251) => ("TIDE", "Tide", "m"),
        (10, 3, 252) => ("EROSNP", "Erosion Occurrence Probability", "%"),
        (10, 3, 253) => ("OWASHP", "Overwash Occurrence Probability", "%"),
        (10, 4, 192) => ("WTMPC", "3-D Temperature", "degC"),
        (10, 4, 193) => ("SALIN", "3-D Salinity", "psu"),
        (10, 4, 194) => ("BKENG", "Barotropic Kinectic Energy", "J/kg"),
        (10, 4, 195) => ("DBSS", "Geometric Depth Below Sea Surface", "m"),
        (10, 4, 196) => ("INTFD", "Interface Depths", "m"),
        (10, 4, 197) => ("OHC", "Ocean Heat Content", "J/m^2"),
        _ => return None,
    };
    Some(entry)
}
