//! ECMWF GRIB1 local parameter tables (versions 128 and 129).
//!
//! WMO ON388 Table 2 (the international table, versions 1-3) only covers
//! parameter ids 1-127 with fixed meanings; centres redefine the full
//! 1-254 space in local tables 128+. ECMWF (originating centre 98) uses
//! table 128 for the bulk of IFS / ERA5 surface and single-level fields
//! (2t, 10u, 10v, msl, z, …). Table 129, in eccodes 2.34.1, holds the
//! gradient counterparts of those fields. Without these, ECMWF GRIB1 fields
//! all show as "Unknown".
//!
//! Data generated from eccodes' `definitions/grib1/2.98.128.table` and
//! `2.98.129.table` (Apache-2.0; the parameter definitions are factual data
//! from the ECMWF parameter database). Regenerate after an eccodes upgrade:
//! `python3 tools/gen_ecmwf_tables.py > crates/fieldglass-grib1/src/tables_ecmwf.rs && cargo fmt`.

use crate::tables::ParameterEntry;

/// Look up an ECMWF local-table parameter. Returns `None` when the table
/// version is not an ECMWF local table we carry, or the id is undefined in
/// it (so the caller can fall back to "Unknown").
pub fn lookup(table_version: u8, id: u8) -> Option<ParameterEntry> {
    match table_version {
        128 => ecmwf_128(id),
        129 => ecmwf_129(id),
        _ => None,
    }
}

/// ECMWF local parameter table 128 (centre 98). Generated from
/// eccodes' `definitions/grib1/2.98.128.table`.
fn ecmwf_128(id: u8) -> Option<ParameterEntry> {
    let (name, abbreviation, units) = match id {
        1 => ("Stream function", "strf", "m**2 s**-1"),
        2 => ("Velocity potential", "vp", "m**2 s**-1"),
        3 => ("Potential temperature", "pt", "K"),
        4 => ("Equivalent potential temperature", "eqpt", "K"),
        5 => ("Saturated equivalent potential temperature", "sept", "K"),
        6 => ("Soil sand fraction", "ssfr", "(0 - 1)"),
        7 => ("Soil clay fraction", "scfr", "(0 - 1)"),
        8 => ("Surface runoff", "sro", "m"),
        9 => ("Sub-surface runoff", "ssro", "m"),
        10 => ("Wind speed", "ws", "m s**-1"),
        11 => ("U component of divergent wind", "udvw", "m s**-1"),
        12 => ("V component of divergent wind", "vdvw", "m s**-1"),
        13 => ("U component of rotational wind", "urtw", "m s**-1"),
        14 => ("V component of rotational wind", "vrtw", "m s**-1"),
        15 => ("UV visible albedo for direct radiation", "aluvp", "(0 - 1)"),
        16 => (
            "UV visible albedo for diffuse radiation",
            "aluvd",
            "(0 - 1)",
        ),
        17 => ("Near IR albedo for direct radiation", "alnip", "(0 - 1)"),
        18 => ("Near IR albedo for diffuse radiation", "alnid", "(0 - 1)"),
        19 => ("Clear sky surface UV", "uvcs", "J m**-2"),
        20 => (
            "Clear sky surface photosynthetically active radiation",
            "parcs",
            "J m**-2",
        ),
        21 => ("Unbalanced component of temperature", "uctp", "K"),
        22 => (
            "Unbalanced component of logarithm of surface pressure",
            "ucln",
            "",
        ),
        23 => ("Unbalanced component of divergence", "ucdv", "s**-1"),
        24 => ("Reserved for future unbalanced components", "", ""),
        25 => ("Reserved for future unbalanced components", "", ""),
        26 => ("Lake cover", "cl", "(0 - 1)"),
        27 => ("Low vegetation cover", "cvl", "(0 - 1)"),
        28 => ("High vegetation cover", "cvh", "(0 - 1)"),
        29 => ("Type of low vegetation", "tvl", ""),
        30 => ("Type of high vegetation", "tvh", ""),
        31 => ("Sea ice area fraction", "ci", "(0 - 1)"),
        32 => ("Snow albedo", "asn", "(0 - 1)"),
        33 => ("Snow density", "rsn", "kg m**-3"),
        34 => ("Sea surface temperature", "sst", "K"),
        35 => ("Ice temperature layer 1", "istl1", "K"),
        36 => ("Ice temperature layer 2", "istl2", "K"),
        37 => ("Ice temperature layer 3", "istl3", "K"),
        38 => ("Ice temperature layer 4", "istl4", "K"),
        39 => ("Volumetric soil water layer 1", "swvl1", "m**3 m**-3"),
        40 => ("Volumetric soil water layer 2", "swvl2", "m**3 m**-3"),
        41 => ("Volumetric soil water layer 3", "swvl3", "m**3 m**-3"),
        42 => ("Volumetric soil water layer 4", "swvl4", "m**3 m**-3"),
        43 => ("Soil type", "slt", ""),
        44 => ("Snow evaporation", "es", "m of water equivalent"),
        45 => ("Snowmelt", "smlt", "m of water equivalent"),
        46 => ("Solar duration", "sdur", "s"),
        47 => ("Direct solar radiation", "dsrp", "J m**-2"),
        48 => (
            "Magnitude of turbulent surface stress",
            "magss",
            "N m**-2 s",
        ),
        49 => (
            "10 metre wind gust since previous post-processing",
            "10fg",
            "m s**-1",
        ),
        50 => ("Large-scale precipitation fraction", "lspf", "s"),
        51 => (
            "Maximum temperature at 2 metres in the last 24 hours",
            "mx2t24",
            "K",
        ),
        52 => (
            "Minimum temperature at 2 metres in the last 24 hours",
            "mn2t24",
            "K",
        ),
        53 => ("Montgomery potential", "mont", "m**2 s**-2"),
        54 => ("Pressure", "pres", "Pa"),
        55 => (
            "Mean temperature at 2 metres in the last 24 hours",
            "mean2t24",
            "K",
        ),
        56 => (
            "Mean 2 metre dewpoint temperature in the last 24 hours",
            "mn2d24",
            "K",
        ),
        57 => ("Downward UV radiation at the surface", "uvb", "J m**-2"),
        58 => (
            "Photosynthetically active radiation at the surface",
            "par",
            "J m**-2",
        ),
        59 => ("Convective available potential energy", "cape", "J kg**-1"),
        60 => ("Potential vorticity", "pv", "K m**2 kg**-1 s**-1"),
        62 => ("Observation count", "obct", ""),
        63 => ("Start time for skin temperature difference", "stsktd", "s"),
        64 => ("Finish time for skin temperature difference", "ftsktd", "s"),
        65 => ("Skin temperature difference", "sktd", "K"),
        66 => ("Leaf area index, low vegetation", "lai_lv", "m**2 m**-2"),
        67 => ("Leaf area index, high vegetation", "lai_hv", "m**2 m**-2"),
        68 => (
            "Minimum stomatal resistance, low vegetation",
            "msr_lv",
            "s m**-1",
        ),
        69 => (
            "Minimum stomatal resistance, high vegetation",
            "msr_hv",
            "s m**-1",
        ),
        70 => ("Biome cover, low vegetation", "bc_lv", "(0 - 1)"),
        71 => ("Biome cover, high vegetation", "bc_hv", "(0 - 1)"),
        72 => (
            "Instantaneous surface solar radiation downwards",
            "issrd",
            "W m**-2",
        ),
        73 => (
            "Instantaneous surface thermal radiation downwards",
            "istrd",
            "W m**-2",
        ),
        74 => (
            "Standard deviation of filtered subgrid orography",
            "sdfor",
            "m",
        ),
        75 => ("Specific rain water content", "crwc", "kg kg**-1"),
        76 => ("Specific snow water content", "cswc", "kg kg**-1"),
        77 => ("Eta-coordinate vertical velocity", "etadot", "s**-1"),
        78 => ("Total column cloud liquid water", "tclw", "kg m**-2"),
        79 => ("Total column cloud ice water", "tciw", "kg m**-2"),
        80 => ("Experimental product", "", ""),
        81 => ("Experimental product", "", ""),
        82 => ("Experimental product", "", ""),
        83 => ("Experimental product", "", ""),
        84 => ("Experimental product", "", ""),
        85 => ("Experimental product", "", ""),
        86 => ("Experimental product", "", ""),
        87 => ("Experimental product", "", ""),
        88 => ("Experimental product", "", ""),
        89 => ("Experimental product", "", ""),
        90 => ("Experimental product", "", ""),
        91 => ("Experimental product", "", ""),
        92 => ("Experimental product", "", ""),
        93 => ("Experimental product", "", ""),
        94 => ("Experimental product", "", ""),
        95 => ("Experimental product", "", ""),
        96 => ("Experimental product", "", ""),
        97 => ("Experimental product", "", ""),
        98 => ("Experimental product", "", ""),
        99 => ("Experimental product", "", ""),
        100 => ("Experimental product", "", ""),
        101 => ("Experimental product", "", ""),
        102 => ("Experimental product", "", ""),
        103 => ("Experimental product", "", ""),
        104 => ("Experimental product", "", ""),
        105 => ("Experimental product", "", ""),
        106 => ("Experimental product", "", ""),
        107 => ("Experimental product", "", ""),
        108 => ("Experimental product", "", ""),
        109 => ("Experimental product", "", ""),
        110 => ("Experimental product", "", ""),
        111 => ("Experimental product", "", ""),
        112 => ("Experimental product", "", ""),
        113 => ("Experimental product", "", ""),
        114 => ("Experimental product", "", ""),
        115 => ("Experimental product", "", ""),
        116 => ("Experimental product", "", ""),
        117 => ("Experimental product", "", ""),
        118 => ("Experimental product", "", ""),
        119 => ("Experimental product", "", ""),
        120 => ("Experimental product", "", ""),
        121 => (
            "Maximum temperature at 2 metres in the last 6 hours",
            "mx2t6",
            "K",
        ),
        122 => (
            "Minimum temperature at 2 metres in the last 6 hours",
            "mn2t6",
            "K",
        ),
        123 => ("10 metre wind gust in the last 6 hours", "10fg6", "m s**-1"),
        124 => ("Surface emissivity", "emis", "dimensionless"),
        125 => ("Vertically integrated total energy", "vite", "J m**-2"),
        126 => (
            "Generic parameter for sensitive area prediction",
            "",
            "Various",
        ),
        127 => ("Atmospheric tide", "at", ""),
        128 => ("Budget values", "bv", ""),
        129 => ("Geopotential", "z", "m**2 s**-2"),
        130 => ("Temperature", "t", "K"),
        131 => ("U component of wind", "u", "m s**-1"),
        132 => ("V component of wind", "v", "m s**-1"),
        133 => ("Specific humidity", "q", "kg kg**-1"),
        134 => ("Surface pressure", "sp", "Pa"),
        135 => ("Vertical velocity", "w", "Pa s**-1"),
        136 => ("Total column water", "tcw", "kg m**-2"),
        137 => ("Total column water vapour", "tcwv", "kg m**-2"),
        138 => ("Vorticity (relative)", "vo", "s**-1"),
        139 => ("Soil temperature level 1", "stl1", "K"),
        140 => ("Soil wetness level 1", "swl1", "m of water equivalent"),
        141 => ("Snow depth", "sd", "m of water equivalent"),
        142 => ("Large-scale precipitation", "lsp", "m"),
        143 => ("Convective precipitation", "cp", "m"),
        144 => ("Snowfall", "sf", "m of water equivalent"),
        145 => ("Boundary layer dissipation", "bld", "J m**-2"),
        146 => ("Surface sensible heat flux", "sshf", "J m**-2"),
        147 => ("Surface latent heat flux", "slhf", "J m**-2"),
        148 => ("Charnock", "chnk", ""),
        149 => ("Surface net radiation", "snr", "J m**-2"),
        150 => ("Top net radiation", "tnr", "J m**-2"),
        151 => ("Mean sea level pressure", "msl", "Pa"),
        152 => ("Logarithm of surface pressure", "lnsp", ""),
        153 => ("Short-wave heating rate", "swhr", "K"),
        154 => ("Long-wave heating rate", "lwhr", "K"),
        155 => ("Divergence", "d", "s**-1"),
        156 => ("Geopotential Height", "gh", "gpm"),
        157 => ("Relative humidity", "r", "%"),
        158 => ("Tendency of surface pressure", "tsp", "Pa s**-1"),
        159 => ("Boundary layer height", "blh", "m"),
        160 => ("Standard deviation of orography", "sdor", "m"),
        161 => ("Anisotropy of sub-gridscale orography", "isor", ""),
        162 => ("Angle of sub-gridscale orography", "anor", "radians"),
        163 => ("Slope of sub-gridscale orography", "slor", ""),
        164 => ("Total cloud cover", "tcc", "(0 - 1)"),
        165 => ("10 metre U wind component", "10u", "m s**-1"),
        166 => ("10 metre V wind component", "10v", "m s**-1"),
        167 => ("2 metre temperature", "2t", "K"),
        168 => ("2 metre dewpoint temperature", "2d", "K"),
        169 => ("Surface solar radiation downwards", "ssrd", "J m**-2"),
        170 => ("Soil temperature level 2", "stl2", "K"),
        171 => ("Soil wetness level 2", "swl2", "m of water equivalent"),
        172 => ("Land-sea mask", "lsm", "(0 - 1)"),
        173 => ("Surface roughness", "sr", "m"),
        174 => ("Albedo", "al", "(0 - 1)"),
        175 => ("Surface thermal radiation downwards", "strd", "J m**-2"),
        176 => ("Surface net solar radiation", "ssr", "J m**-2"),
        177 => ("Surface net thermal radiation", "str", "J m**-2"),
        178 => ("Top net solar radiation", "tsr", "J m**-2"),
        179 => ("Top net thermal radiation", "ttr", "J m**-2"),
        180 => ("Eastward turbulent surface stress", "ewss", "N m**-2 s"),
        181 => ("Northward turbulent surface stress", "nsss", "N m**-2 s"),
        182 => ("Evaporation", "e", "m of water equivalent"),
        183 => ("Soil temperature level 3", "stl3", "K"),
        184 => ("Soil wetness level 3", "swl3", "m of water equivalent"),
        185 => ("Convective cloud cover", "ccc", "(0 - 1)"),
        186 => ("Low cloud cover", "lcc", "(0 - 1)"),
        187 => ("Medium cloud cover", "mcc", "(0 - 1)"),
        188 => ("High cloud cover", "hcc", "(0 - 1)"),
        189 => ("Sunshine duration", "sund", "s"),
        190 => (
            "East-West component of sub-gridscale orographic variance",
            "ewov",
            "m**2",
        ),
        191 => (
            "North-South component of sub-gridscale orographic variance",
            "nsov",
            "m**2",
        ),
        192 => (
            "North-West/South-East component of sub-gridscale orographic variance",
            "nwov",
            "m**2",
        ),
        193 => (
            "North-East/South-West component of sub-gridscale orographic variance",
            "neov",
            "m**2",
        ),
        194 => ("Brightness temperature", "btmp", "K"),
        195 => ("Eastward gravity wave surface stress", "lgws", "N m**-2 s"),
        196 => ("Northward gravity wave surface stress", "mgws", "N m**-2 s"),
        197 => ("Gravity wave dissipation", "gwd", "J m**-2"),
        198 => ("Skin reservoir content", "src", "m of water equivalent"),
        199 => ("Vegetation fraction", "veg", "(0 - 1)"),
        200 => ("Variance of sub-gridscale orography", "vso", "m**2"),
        201 => (
            "Maximum temperature at 2 metres since previous post-processing",
            "mx2t",
            "K",
        ),
        202 => (
            "Minimum temperature at 2 metres since previous post-processing",
            "mn2t",
            "K",
        ),
        203 => ("Ozone mass mixing ratio", "o3", "kg kg**-1"),
        204 => ("Precipitation analysis weights", "paw", ""),
        205 => ("Runoff", "ro", "m"),
        206 => ("Total column ozone", "tco3", "kg m**-2"),
        207 => ("10 metre wind speed", "10si", "m s**-1"),
        208 => ("Top net solar radiation, clear sky", "tsrc", "J m**-2"),
        209 => ("Top net thermal radiation, clear sky", "ttrc", "J m**-2"),
        210 => ("Surface net solar radiation, clear sky", "ssrc", "J m**-2"),
        211 => (
            "Surface net thermal radiation, clear sky",
            "strc",
            "J m**-2",
        ),
        212 => ("TOA incident solar radiation", "tisr", "J m**-2"),
        213 => (
            "Vertically integrated moisture divergence",
            "vimd",
            "kg m**-2",
        ),
        214 => ("Diabatic heating by radiation", "dhr", "K"),
        215 => ("Diabatic heating by vertical diffusion", "dhvd", "K"),
        216 => ("Diabatic heating by cumulus convection", "dhcc", "K"),
        217 => ("Diabatic heating large-scale condensation", "dhlc", "K"),
        218 => ("Vertical diffusion of zonal wind", "vdzw", "m s**-1"),
        219 => ("Vertical diffusion of meridional wind", "vdmw", "m s**-1"),
        220 => ("East-West gravity wave drag tendency", "ewgd", "m s**-1"),
        221 => ("North-South gravity wave drag tendency", "nsgd", "m s**-1"),
        222 => ("Convective tendency of zonal wind", "ctzw", "m s**-1"),
        223 => ("Convective tendency of meridional wind", "ctmw", "m s**-1"),
        224 => ("Vertical diffusion of humidity", "vdh", "kg kg**-1"),
        225 => (
            "Humidity tendency by cumulus convection",
            "htcc",
            "kg kg**-1",
        ),
        226 => (
            "Humidity tendency by large-scale condensation",
            "htlc",
            "kg kg**-1",
        ),
        227 => (
            "Tendency due to removal of negative humidity",
            "crnh",
            "kg kg**-1",
        ),
        228 => ("Total precipitation", "tp", "m"),
        229 => (
            "Instantaneous eastward turbulent surface stress",
            "iews",
            "N m**-2",
        ),
        230 => (
            "Instantaneous northward turbulent surface stress",
            "inss",
            "N m**-2",
        ),
        231 => (
            "Instantaneous surface sensible heat flux",
            "ishf",
            "W m**-2",
        ),
        232 => ("Instantaneous moisture flux", "ie", "kg m**-2 s**-1"),
        233 => ("Apparent surface humidity", "asq", "kg kg**-1"),
        234 => ("Logarithm of surface roughness length for heat", "lsrh", ""),
        235 => ("Skin temperature", "skt", "K"),
        236 => ("Soil temperature level 4", "stl4", "K"),
        237 => ("Soil wetness level 4", "swl4", "m"),
        238 => ("Temperature of snow layer", "tsn", "K"),
        239 => ("Convective snowfall", "csf", "m of water equivalent"),
        240 => ("Large-scale snowfall", "lsf", "m of water equivalent"),
        241 => ("Accumulated cloud fraction tendency", "acf", "(-1 to 1)"),
        242 => ("Accumulated liquid water tendency", "alw", "(-1 to 1)"),
        243 => ("Forecast albedo", "fal", "(0 - 1)"),
        244 => ("Forecast surface roughness", "fsr", "m"),
        245 => (
            "Forecast logarithm of surface roughness for heat",
            "flsr",
            "",
        ),
        246 => ("Specific cloud liquid water content", "clwc", "kg kg**-1"),
        247 => ("Specific cloud ice water content", "ciwc", "kg kg**-1"),
        248 => ("Fraction of cloud cover", "cc", "(0 - 1)"),
        249 => ("Accumulated ice water tendency", "aiw", "(-1 to 1)"),
        250 => ("Ice age", "ice", "(0 - 1)"),
        251 => ("Adiabatic tendency of temperature", "atte", "K"),
        252 => ("Adiabatic tendency of humidity", "athe", "kg kg**-1"),
        253 => ("Adiabatic tendency of zonal wind", "atze", "m s**-1"),
        254 => ("Adiabatic tendency of meridional wind", "atmw", "m s**-1"),
        255 => ("Indicates a missing value", "", ""),
        _ => return None,
    };
    Some(ParameterEntry {
        name,
        abbreviation,
        units,
    })
}

/// ECMWF local parameter table 129 (centre 98). Generated from
/// eccodes' `definitions/grib1/2.98.129.table`.
fn ecmwf_129(id: u8) -> Option<ParameterEntry> {
    let (name, abbreviation, units) = match id {
        1 => ("Stream function gradient", "strfgrd", "m**2 s**-1"),
        2 => ("Velocity potential gradient", "vpotgrd", "m**2 s**-1"),
        3 => ("Potential temperature gradient", "ptgrd", "K"),
        4 => ("Equivalent potential temperature gradient", "eqptgrd", "K"),
        5 => (
            "Saturated equivalent potential temperature gradient",
            "septgrd",
            "K",
        ),
        11 => (
            "U component of divergent wind gradient",
            "udvwgrd",
            "m s**-1",
        ),
        12 => (
            "V component of divergent wind gradient",
            "vdvwgrd",
            "m s**-1",
        ),
        13 => (
            "U component of rotational wind gradient",
            "urtwgrd",
            "m s**-1",
        ),
        14 => (
            "V component of rotational wind gradient",
            "vrtwgrd",
            "m s**-1",
        ),
        21 => (
            "Unbalanced component of temperature gradient",
            "uctpgrd",
            "K",
        ),
        22 => (
            "Unbalanced component of logarithm of surface pressure gradient",
            "uclngrd",
            "",
        ),
        23 => (
            "Unbalanced component of divergence gradient",
            "ucdvgrd",
            "s**-1",
        ),
        24 => ("Reserved for future unbalanced components", "", ""),
        25 => ("Reserved for future unbalanced components", "", ""),
        26 => ("Lake cover gradient", "clgrd", "(0 - 1)"),
        27 => ("Low vegetation cover gradient", "cvlgrd", "(0 - 1)"),
        28 => ("High vegetation cover gradient", "cvhgrd", "(0 - 1)"),
        29 => ("Type of low vegetation gradient", "tvlgrd", ""),
        30 => ("Type of high vegetation gradient", "tvhgrd", ""),
        31 => ("Sea-ice cover gradient", "sicgrd", "(0 - 1)"),
        32 => ("Snow albedo gradient", "asngrd", "(0 - 1)"),
        33 => ("Snow density gradient", "rsngrd", "kg m**-3"),
        34 => ("Sea surface temperature gradient", "sstkgrd", "K"),
        35 => ("Ice surface temperature layer 1 gradient", "istl1grd", "K"),
        36 => ("Ice surface temperature layer 2 gradient", "istl2grd", "K"),
        37 => ("Ice surface temperature layer 3 gradient", "istl3grd", "K"),
        38 => ("Ice surface temperature layer 4 gradient", "istl4grd", "K"),
        39 => (
            "Volumetric soil water layer 1 gradient",
            "swvl1grd",
            "m**3 m**-3",
        ),
        40 => (
            "Volumetric soil water layer 2 gradient",
            "swvl2grd",
            "m**3 m**-3",
        ),
        41 => (
            "Volumetric soil water layer 3 gradient",
            "swvl3grd",
            "m**3 m**-3",
        ),
        42 => (
            "Volumetric soil water layer 4 gradient",
            "swvl4grd",
            "m**3 m**-3",
        ),
        43 => ("Soil type gradient", "sltgrd", ""),
        44 => ("Snow evaporation gradient", "esgrd", "kg m**-2"),
        45 => ("Snowmelt gradient", "smltgrd", "kg m**-2"),
        46 => ("Solar duration gradient", "sdurgrd", "s"),
        47 => ("Direct solar radiation gradient", "dsrpgrd", "J m**-2"),
        48 => (
            "Magnitude of turbulent surface stress gradient",
            "magssgrd",
            "N m**-2 s",
        ),
        49 => ("10 metre wind gust gradient", "10fggrd", "m s**-1"),
        50 => (
            "Large-scale precipitation fraction gradient",
            "lspfgrd",
            "s",
        ),
        51 => ("Maximum 2 metre temperature gradient", "mx2t24grd", "K"),
        52 => ("Minimum 2 metre temperature gradient", "mn2t24grd", "K"),
        53 => ("Montgomery potential gradient", "montgrd", "m**2 s**-2"),
        54 => ("Pressure gradient", "presgrd", "Pa"),
        55 => (
            "Mean 2 metre temperature in the last 24 hours gradient",
            "mean2t24grd",
            "K",
        ),
        56 => (
            "Mean 2 metre dewpoint temperature in the last 24 hours gradient",
            "mn2d24grd",
            "K",
        ),
        57 => (
            "Downward UV radiation at the surface gradient",
            "uvbgrd",
            "J m**-2",
        ),
        58 => (
            "Photosynthetically active radiation at the surface gradient",
            "pargrd",
            "J m**-2",
        ),
        59 => (
            "Convective available potential energy gradient",
            "capegrd",
            "J kg**-1",
        ),
        60 => (
            "Potential vorticity gradient",
            "pvgrd",
            "K m**2 kg**-1 s**-1",
        ),
        61 => (
            "Total precipitation from observations gradient",
            "tpogrd",
            "Millimetres*100 + number of stations",
        ),
        62 => ("Observation count gradient", "obctgrd", ""),
        63 => ("Start time for skin temperature difference", "", "s"),
        64 => ("Finish time for skin temperature difference", "", "s"),
        65 => ("Skin temperature difference", "", "K"),
        66 => ("Leaf area index, low vegetation", "", "m**2 m**-2"),
        67 => ("Leaf area index, high vegetation", "", "m**2 m**-2"),
        68 => ("Minimum stomatal resistance, low vegetation", "", "s m**-1"),
        69 => (
            "Minimum stomatal resistance, high vegetation",
            "",
            "s m**-1",
        ),
        70 => ("Biome cover, low vegetation", "", "(0 - 1)"),
        71 => ("Biome cover, high vegetation", "", "(0 - 1)"),
        78 => ("Total column liquid water", "", "kg m**-2"),
        79 => ("Total column ice water", "", "kg m**-2"),
        80 => ("Experimental product", "", ""),
        81 => ("Experimental product", "", ""),
        82 => ("Experimental product", "", ""),
        83 => ("Experimental product", "", ""),
        84 => ("Experimental product", "", ""),
        85 => ("Experimental product", "", ""),
        86 => ("Experimental product", "", ""),
        87 => ("Experimental product", "", ""),
        88 => ("Experimental product", "", ""),
        89 => ("Experimental product", "", ""),
        90 => ("Experimental product", "", ""),
        91 => ("Experimental product", "", ""),
        92 => ("Experimental product", "", ""),
        93 => ("Experimental product", "", ""),
        94 => ("Experimental product", "", ""),
        95 => ("Experimental product", "", ""),
        96 => ("Experimental product", "", ""),
        97 => ("Experimental product", "", ""),
        98 => ("Experimental product", "", ""),
        99 => ("Experimental product", "", ""),
        100 => ("Experimental product", "", ""),
        101 => ("Experimental product", "", ""),
        102 => ("Experimental product", "", ""),
        103 => ("Experimental product", "", ""),
        104 => ("Experimental product", "", ""),
        105 => ("Experimental product", "", ""),
        106 => ("Experimental product", "", ""),
        107 => ("Experimental product", "", ""),
        108 => ("Experimental product", "", ""),
        109 => ("Experimental product", "", ""),
        110 => ("Experimental product", "", ""),
        111 => ("Experimental product", "", ""),
        112 => ("Experimental product", "", ""),
        113 => ("Experimental product", "", ""),
        114 => ("Experimental product", "", ""),
        115 => ("Experimental product", "", ""),
        116 => ("Experimental product", "", ""),
        117 => ("Experimental product", "", ""),
        118 => ("Experimental product", "", ""),
        119 => ("Experimental product", "", ""),
        120 => ("Experimental product", "", ""),
        121 => ("Maximum temperature at 2 metres gradient", "mx2t6grd", "K"),
        122 => ("Minimum temperature at 2 metres gradient", "mn2t6grd", "K"),
        123 => (
            "10 metre wind gust in the last 6 hours gradient",
            "10fg6grd",
            "m s**-1",
        ),
        125 => ("Vertically integrated total energy", "", "J m**-2"),
        126 => (
            "Generic parameter for sensitive area prediction",
            "",
            "Various",
        ),
        127 => ("Atmospheric tide gradient", "atgrd", ""),
        128 => ("Budget values gradient", "bvgrd", ""),
        129 => ("Geopotential gradient", "zgrd", "m**2 s**-2"),
        130 => ("Temperature gradient", "tgrd", "K"),
        131 => ("U component of wind gradient", "ugrd", "m s**-1"),
        132 => ("V component of wind gradient", "vgrd", "m s**-1"),
        133 => ("Specific humidity gradient", "qgrd", "kg kg**-1"),
        134 => ("Surface pressure gradient", "spgrd", "Pa"),
        135 => ("vertical velocity (pressure) gradient", "wgrd", "Pa s**-1"),
        136 => ("Total column water gradient", "tcwgrd", "kg m**-2"),
        137 => ("Total column water vapour gradient", "tcwvgrd", "kg m**-2"),
        138 => ("Vorticity (relative) gradient", "vogrd", "s**-1"),
        139 => ("Soil temperature level 1 gradient", "stl1grd", "K"),
        140 => ("Soil wetness level 1 gradient", "swl1grd", "kg m**-2"),
        141 => ("Snow depth gradient", "sdgrd", "m of water equivalent"),
        142 => (
            "Stratiform precipitation (Large-scale precipitation) gradient",
            "lspgrd",
            "m",
        ),
        143 => ("Convective precipitation gradient", "cpgrd", "m"),
        144 => (
            "Snowfall (convective + stratiform) gradient",
            "sfgrd",
            "m of water equivalent",
        ),
        145 => ("Boundary layer dissipation gradient", "bldgrd", "J m**-2"),
        146 => ("Surface sensible heat flux gradient", "sshfgrd", "J m**-2"),
        147 => ("Surface latent heat flux gradient", "slhfgrd", "J m**-2"),
        148 => ("Charnock gradient", "chnkgrd", ""),
        149 => ("Surface net radiation gradient", "snrgrd", "J m**-2"),
        150 => ("Top net radiation gradient", "tnrgrd", ""),
        151 => ("Mean sea level pressure gradient", "mslgrd", "Pa"),
        152 => ("Logarithm of surface pressure gradient", "lnspgrd", ""),
        153 => ("Short-wave heating rate gradient", "swhrgrd", "K"),
        154 => ("Long-wave heating rate gradient", "lwhrgrd", "K"),
        155 => ("Divergence gradient", "dgrd", "s**-1"),
        156 => ("Height gradient", "ghgrd", "m"),
        157 => ("Relative humidity gradient", "rgrd", "%"),
        158 => (
            "Tendency of surface pressure gradient",
            "tspgrd",
            "Pa s**-1",
        ),
        159 => ("Boundary layer height gradient", "blhgrd", "m"),
        160 => ("Standard deviation of orography gradient", "sdorgrd", ""),
        161 => (
            "Anisotropy of sub-gridscale orography gradient",
            "isorgrd",
            "",
        ),
        162 => (
            "Angle of sub-gridscale orography gradient",
            "anorgrd",
            "radians",
        ),
        163 => ("Slope of sub-gridscale orography gradient", "slorgrd", ""),
        164 => ("Total cloud cover gradient", "tccgrd", "(0 - 1)"),
        165 => ("10 metre U wind component gradient", "10ugrd", "m s**-1"),
        166 => ("10 metre V wind component gradient", "10vgrd", "m s**-1"),
        167 => ("2 metre temperature gradient", "2tgrd", "K"),
        168 => ("2 metre dewpoint temperature gradient", "2dgrd", "K"),
        169 => (
            "Surface solar radiation downwards gradient",
            "ssrdgrd",
            "J m**-2",
        ),
        170 => ("Soil temperature level 2 gradient", "stl2grd", "K"),
        171 => ("Soil wetness level 2 gradient", "swl2grd", "kg m**-2"),
        172 => ("Land-sea mask gradient", "lsmgrd", "(0 - 1)"),
        173 => ("Surface roughness gradient", "srgrd", "m"),
        174 => ("Albedo gradient", "algrd", "(0 - 1)"),
        175 => (
            "Surface thermal radiation downwards gradient",
            "strdgrd",
            "J m**-2",
        ),
        176 => ("Surface net solar radiation gradient", "ssrgrd", "J m**-2"),
        177 => (
            "Surface net thermal radiation gradient",
            "strgrd",
            "J m**-2",
        ),
        178 => ("Top net solar radiation gradient", "tsrgrd", "J m**-2"),
        179 => ("Top net thermal radiation gradient", "ttrgrd", "J m**-2"),
        180 => ("East-West surface stress gradient", "ewssgrd", "N m**-2 s"),
        181 => (
            "North-South surface stress gradient",
            "nsssgrd",
            "N m**-2 s",
        ),
        182 => ("Evaporation gradient", "egrd", "kg m**-2"),
        183 => ("Soil temperature level 3 gradient", "stl3grd", "K"),
        184 => ("Soil wetness level 3 gradient", "swl3grd", "kg m**-2"),
        185 => ("Convective cloud cover gradient", "cccgrd", "(0 - 1)"),
        186 => ("Low cloud cover gradient", "lccgrd", "(0 - 1)"),
        187 => ("Medium cloud cover gradient", "mccgrd", "(0 - 1)"),
        188 => ("High cloud cover gradient", "hccgrd", "(0 - 1)"),
        189 => ("Sunshine duration gradient", "sundgrd", "s"),
        190 => (
            "East-West component of sub-gridscale orographic variance gradient",
            "ewovgrd",
            "m**2",
        ),
        191 => (
            "North-South component of sub-gridscale orographic variance gradient",
            "nsovgrd",
            "m**2",
        ),
        192 => (
            "North-West/South-East component of sub-gridscale orographic variance gradient",
            "nwovgrd",
            "m**2",
        ),
        193 => (
            "North-East/South-West component of sub-gridscale orographic variance gradient",
            "neovgrd",
            "m**2",
        ),
        194 => ("Brightness temperature gradient", "btmpgrd", "K"),
        195 => (
            "Longitudinal component of gravity wave stress gradient",
            "lgwsgrd",
            "N m**-2 s",
        ),
        196 => (
            "Meridional component of gravity wave stress gradient",
            "mgwsgrd",
            "N m**-2 s",
        ),
        197 => ("Gravity wave dissipation gradient", "gwdgrd", "J m**-2"),
        198 => ("Skin reservoir content gradient", "srcgrd", "kg m**-2"),
        199 => ("Vegetation fraction gradient", "veggrd", "(0 - 1)"),
        200 => (
            "Variance of sub-gridscale orography gradient",
            "vsogrd",
            "m**2",
        ),
        201 => (
            "Maximum temperature at 2 metres since previous post-processing gradient",
            "mx2tgrd",
            "K",
        ),
        202 => (
            "Minimum temperature at 2 metres since previous post-processing gradient",
            "mn2tgrd",
            "K",
        ),
        203 => ("Ozone mass mixing ratio gradient", "o3grd", "kg kg**-1"),
        204 => ("Precipitation analysis weights gradient", "pawgrd", ""),
        205 => ("Runoff gradient", "rogrd", "m"),
        206 => ("Total column ozone gradient", "tco3grd", "kg m**-2"),
        207 => ("10 metre wind speed gradient", "10sigrd", "m s**-1"),
        208 => (
            "Top net solar radiation, clear sky gradient",
            "tsrcgrd",
            "J m**-2",
        ),
        209 => (
            "Top net thermal radiation, clear sky gradient",
            "ttrcgrd",
            "J m**-2",
        ),
        210 => (
            "Surface net solar radiation, clear sky gradient",
            "ssrcgrd",
            "J m**-2",
        ),
        211 => (
            "Surface net thermal radiation, clear sky gradient",
            "strcgrd",
            "J m**-2",
        ),
        212 => (
            "TOA incident solar radiation gradient",
            "tisrgrd",
            "J m**-2",
        ),
        214 => ("Diabatic heating by radiation gradient", "dhrgrd", "K"),
        215 => (
            "Diabatic heating by vertical diffusion gradient",
            "dhvdgrd",
            "K",
        ),
        216 => (
            "Diabatic heating by cumulus convection gradient",
            "dhccgrd",
            "K",
        ),
        217 => (
            "Diabatic heating large-scale condensation gradient",
            "dhlcgrd",
            "K",
        ),
        218 => (
            "Vertical diffusion of zonal wind gradient",
            "vdzwgrd",
            "m s**-1",
        ),
        219 => (
            "Vertical diffusion of meridional wind gradient",
            "vdmwgrd",
            "m s**-1",
        ),
        220 => (
            "East-West gravity wave drag tendency gradient",
            "ewgdgrd",
            "m s**-1",
        ),
        221 => (
            "North-South gravity wave drag tendency gradient",
            "nsgdgrd",
            "m s**-1",
        ),
        222 => (
            "Convective tendency of zonal wind gradient",
            "ctzwgrd",
            "m s**-1",
        ),
        223 => (
            "Convective tendency of meridional wind gradient",
            "ctmwgrd",
            "m s**-1",
        ),
        224 => (
            "Vertical diffusion of humidity gradient",
            "vdhgrd",
            "kg kg**-1",
        ),
        225 => (
            "Humidity tendency by cumulus convection gradient",
            "htccgrd",
            "kg kg**-1",
        ),
        226 => (
            "Humidity tendency by large-scale condensation gradient",
            "htlcgrd",
            "kg kg**-1",
        ),
        227 => (
            "Change from removal of negative humidity gradient",
            "crnhgrd",
            "kg kg**-1",
        ),
        228 => ("Total precipitation gradient", "tpgrd", "m"),
        229 => (
            "Instantaneous X surface stress gradient",
            "iewsgrd",
            "N m**-2",
        ),
        230 => (
            "Instantaneous Y surface stress gradient",
            "inssgrd",
            "N m**-2",
        ),
        231 => (
            "Instantaneous surface heat flux gradient",
            "ishfgrd",
            "J m**-2",
        ),
        232 => (
            "Instantaneous moisture flux gradient",
            "iegrd",
            "kg m**-2 s",
        ),
        233 => ("Apparent surface humidity gradient", "asqgrd", "kg kg**-1"),
        234 => (
            "Logarithm of surface roughness length for heat gradient",
            "lsrhgrd",
            "",
        ),
        235 => ("Skin temperature gradient", "sktgrd", "K"),
        236 => ("Soil temperature level 4 gradient", "stl4grd", "K"),
        237 => ("Soil wetness level 4 gradient", "swl4grd", "m"),
        238 => ("Temperature of snow layer gradient", "tsngrd", "K"),
        239 => (
            "Convective snowfall gradient",
            "csfgrd",
            "m of water equivalent",
        ),
        240 => (
            "Large scale snowfall gradient",
            "lsfgrd",
            "m of water equivalent",
        ),
        241 => (
            "Accumulated cloud fraction tendency gradient",
            "acfgrd",
            "(-1 to 1)",
        ),
        242 => (
            "Accumulated liquid water tendency gradient",
            "alwgrd",
            "(-1 to 1)",
        ),
        243 => ("Forecast albedo gradient", "falgrd", "(0 - 1)"),
        244 => ("Forecast surface roughness gradient", "fsrgrd", "m"),
        245 => (
            "Forecast logarithm of surface roughness for heat gradient",
            "flsrgrd",
            "",
        ),
        246 => (
            "Specific cloud liquid water content gradient",
            "clwcgrd",
            "kg kg**-1",
        ),
        247 => (
            "Specific cloud ice water content gradient",
            "ciwcgrd",
            "kg kg**-1",
        ),
        248 => ("Cloud cover gradient", "ccgrd", "(0 - 1)"),
        249 => (
            "Accumulated ice water tendency gradient",
            "aiwgrd",
            "(-1 to 1)",
        ),
        250 => ("Ice age gradient", "icegrd", "(0 - 1)"),
        251 => ("Adiabatic tendency of temperature gradient", "attegrd", "K"),
        252 => (
            "Adiabatic tendency of humidity gradient",
            "athegrd",
            "kg kg**-1",
        ),
        253 => (
            "Adiabatic tendency of zonal wind gradient",
            "atzegrd",
            "m s**-1",
        ),
        254 => (
            "Adiabatic tendency of meridional wind gradient",
            "atmwgrd",
            "m s**-1",
        ),
        255 => ("Indicates a missing value", "", ""),
        _ => return None,
    };
    Some(ParameterEntry {
        name,
        abbreviation,
        units,
    })
}
