// Generated by tools/gen_api_declarations.py from
// crates/fieldglass/schema/api.schema.json. Do not edit by hand; regenerate with
//   FIELDGLASS_UPDATE_SCHEMA=1 cargo test -p fieldglass --test api_rules, then python3 tools/gen_api_declarations.py
//
// A returned object carries every key, and a field with nothing to report is
// `null`, never missing (#574). An option object a host sends may leave out any
// key marked `?`.
//
// The fieldglass API's wire types, as the native addon returns them. Imported by
// native.ts.

/**
 * How a container is addressed: what a caller asks for to get a field.
 *
 * The two shapes are not a detail of the format, they are what the format
 * *is*. GRIB is a stream of self-describing messages, so a message index
 * is the whole address. NetCDF and Zarr hold named variables of two or
 * more dimensions, so a field is a variable plus which axes are the
 * horizontal pair plus where the caller is standing on the others — four
 * things, and no ordering of them is more natural than another.
 *
 * A host asks this once, on open, and then knows which half of
 * `Session` applies. Everything downstream of a decode —
 * `render`, `probe`, `contours`, `combine`, `warp`, `palette` — takes a
 * `Field` and is the same for both.
 */
export type Addressing =
  /**
   * A flat list of messages: `Session::count`,
   * `Session::message`, `Session::decode`.
   */
  | "messages"
  /**
   * Named variables over shared dimensions:
   * `Session::variables`, `Session::dimensions`,
   * `Session::decode_slice`.
   */
  | "variables";

/**
 * Units the `Georef` origin and spacing are expressed in.
 */
export type AxisUnits =
  /**
   * Degrees **in the plane `Georef::proj4` names**, which for
   * `latlon`, `gaussian` and `lookup` is geographic — `x0`/`dx` are
   * longitudes, `y0`/`dy` latitudes.
   *
   * `rotated_latlon` also reports degrees, and they are **not**
   * geographic: its CRS is a PROJ `ob_tran` and its corners are
   * rotated-frame coordinates, which is the whole reason the frame is
   * named. A host that read them as longitude and latitude would put a
   * COSMO domain in the Sahara. The unit is not enough on its own; the
   * CRS beside it is what says what the degrees measure.
   */
  | "degrees"
  /**
   * Projected families: `x0`/`y0` are the grid origin in the projection
   * plane described by `Georef::proj4`, with no false easting or
   * northing, and `dx`/`dy` are metre spacings carrying the scan sign.
   */
  | "metres";

/**
 * One axis of a variable, with the coordinate values along it (#171).
 *
 * What a host labels a cross-section's axes from: a plot of any two
 * dimensions needs the numbers down its side and along its foot, and those
 * are the 1-D coordinate array CF names after the dimension. `coordinates`
 * is `None` when the container holds no such array — an axis is then its
 * own index — and `units` is empty when it states none.
 */
export interface AxisValues {
  /**
   * The dimension's name, as the container spells it.
   */
  dimension: string;
  /**
   * How many points it has, whether or not it has coordinates.
   */
  length: number;
  /**
   * The coordinate value at each index, in index order.
   */
  coordinates: number[] | null;
  /**
   * The coordinate array's own `units`, empty when it states none. For a
   * time axis this is the CF form, `hours since 2020-01-01`.
   */
  units: string;
}

/**
 * One entry of the field-combine vocabulary: what a host's Compare picker
 * shows and what it sends back.
 *
 * `combine_ops` builds the whole list from
 * `CombineOp::ALL`, so both hosts offer
 * the same operations in the same order and an op added to the enum
 * reaches each picker without either being edited (#342).
 */
export interface CombineOpInfo {
  /**
   * The stable wire tag, which is what
   * `Session::combine`'s host wrappers parse
   * back — `"a_minus_b"`, `"ratio"`.
   */
  value: string;
  /**
   * The menu label, e.g. `"A − B"`.
   */
  label: string;
}

/**
 * How a decode should be shaped.
 */
export interface DecodeOptions {
  /**
   * Element type to decode into. `Dtype::Auto` keeps the source's own
   * width and is the only setting that never loses precision.
   */
  dtype?: Dtype;
}

/**
 * One dimension of an array dataset, as the file names it.
 *
 * Shared: two variables that name the same dimension are on the same axis,
 * which is what lets a host offer one time slider for a whole file rather
 * than one per variable.
 */
export interface DimensionInfo {
  /**
   * The dimension's name, path-qualified for a nested group.
   */
  name: string;
  /**
   * How many points it has.
   */
  length: number;
}

/**
 * Which element type a caller wants back from a decode.
 */
export type Dtype =
  /**
   * Whatever the source supports losslessly — the default, and the only
   * setting that never discards precision.
   *
   * `Values::F32` comes back **only if every present value survives the
   * round trip**, otherwise `Values::F64` does. That is stricter than
   * "the packing used 24 bits or fewer", and deliberately so. A
   * simple-packed value is `(R + X·2ᴱ)·10⁻ᴰ`: at 24 bits the *ordinals*
   * fit an `f32` mantissa, but the values need `log2(max|v| / 2ᴱ)` bits
   * once the reference value sits far from zero relative to the quantum,
   * and a non-zero decimal scale factor makes the quantum a negative
   * power of ten, which no binary float represents exactly at all.
   * Checking the decoded numbers costs one pass and answers the question
   * the bit count only approximates: does this field fit?
   *
   * Masked cells do not participate — their value is not data.
   */
  | "auto"
  /**
   * Narrow to `f32` whatever the source was. The caller has decided the
   * loss is acceptable (an `R32F` texture, say).
   */
  | "f32"
  /**
   * Widen to `f64` whatever the source was.
   */
  | "f64";

/**
 * Everything an API call can fail with.
 *
 * One enum, not a per-operation family: a host maps errors once, and
 * `code` is the stable string it maps on. The `code` is part of
 * the API — a host may branch on it — while `message` is
 * prose and may be reworded.
 */
export type ApiError =
  /**
   * The bytes are not a container this build can open.
   */
  | {
    code: "unsupported_format";
    /**
     * What was detected instead, in prose.
     */
    detail: string;
  }
  /**
   * The container opened but a section did not parse.
   */
  | {
    code: "decode";
    /**
     * The underlying `core` error, rendered.
     */
    detail: string;
  }
  /**
   * A message index outside `0..count()`.
   */
  | {
    code: "no_such_message";
    /**
     * The index that was asked for.
     */
    index: number;
    /**
     * How many messages the session actually holds.
     */
    count: number;
  }
  /**
   * The operation is defined but this message's family does not support it —
   * a grid with no geometry asked to warp, a spectral field asked to probe.
   */
  | {
    code: "unsupported";
    /**
     * Which operation, and what about this message refuses it.
     */
    detail: string;
  }
  /**
   * The call belongs to the other addressing mode: a message index asked of
   * a variable dataset, or a slice asked of a message stream.
   *
   * Distinct from `NoSuchMessage` on purpose. A NetCDF file holds no
   * messages *at all*, so answering "index 0 is outside the 0 available"
   * would tell a caller its index was wrong when its whole question was.
   * `Session::addressing` is what to ask first.
   */
  | {
    code: "wrong_addressing";
    /**
     * The mode this session is in, named as the wire value.
     */
    expected: string;
    /**
     * Which call was made, and what to call instead.
     */
    detail: string;
  }
  /**
   * A source served fewer bytes than it was asked for.
   *
   * Its own code, not `Decode`, because the two call for opposite
   * responses: a truncated transfer is worth retrying and a corrupt file is
   * not. A buffer cannot produce this — the reader bounds-checks a range
   * against the source's own size — so it means the host's transport came back
   * short, which is the one failure the host can do something about (#707).
   */
  | {
    code: "short_read";
    /**
     * Offset in the source the read began at.
     */
    at: number;
    /**
     * How many bytes came back.
     */
    got: number;
    /**
     * How many were asked for.
     */
    wanted: number;
  }
  /**
   * A caller-supplied option is out of range or self-contradictory.
   */
  | {
    code: "invalid_option";
    /**
     * Which option, and what it would have had to be.
     */
    detail: string;
  };

/**
 * One decoded field: the values, where they sit, and what they are.
 *
 * The host owns this. The façade keeps no decode cache — linear memory
 * never shrinks and an animation holds many fields — so a field is handed
 * out once and passed back by reference to every operation that consumes
 * one.
 */
export interface Field {
  /**
   * The cell values in scan order, `ni * nj` of them. Read `mask`
   * before a value: an absent cell still occupies its slot.
   */
  values: Values;
  /**
   * One byte per cell: `1` present, `0` absent. Same length as `values`.
   */
  mask: number[];
  /**
   * Grid columns.
   */
  ni: number;
  /**
   * Grid rows.
   */
  nj: number;
  /**
   * Where the cells sit on the Earth.
   */
  georef: Georef;
  /**
   * Set when the values are a spectral field band-limited to what the
   * grid can carry, below the truncation the message declares (#637);
   * `None` for every other field, including a spectral one the grid
   * carries in full. A host shows it beside the field.
   */
  truncation: SpectralTruncation | null;
  /**
   * Range and count over the present cells.
   */
  stats: Stats;
  /**
   * The parameter's name, as the table that resolved it states it.
   *
   * # The unresolved-parameter contract
   *
   * When no table in this build resolves the message's parameter codes,
   * this is `Parameter <codes>` — the numeric codes that went
   * unresolved, slash-separated, outermost first:
   *
   * | Format | Rendering | Codes |
   * |---|---|---|
   * | GRIB2 | `Parameter 209/10/0` | discipline / category / number |
   * | GRIB1 | `Parameter 98/128/210` | centre / table version / id |
   *
   * The codes rather than a bare `"Unknown"` because they are the only
   * thing that tells a user *which* table is missing, and no other field
   * carries them: a host reads the discipline as a Code Table 0.0
   * *name*, which is itself unresolved for a discipline no table
   * defines. This is the string every host shows — the umbrella, the
   * wasm binding and the napi binding all render it from the format
   * crate's own `unresolved_parameter` (#633).
   *
   * Empty only when the message has no parameter codes to name at all,
   * which is a GRIB2 product template carrying no horizontal product
   * common. `units` is empty in both cases — an
   * unresolved parameter has a name to show but no unit to state.
   */
  parameter: string;
  /**
   * The parameter's units as its table states them. Empty when the
   * parameter did not resolve, or is dimensionless.
   */
  units: string;
}

/**
 * A spectral message's full-detail value at a probed cell (#637): the sum
 * over every wavenumber the file holds, where the map shows the field
 * band-limited to what its grid carries.
 *
 * Carried beside the displayed value rather than instead of it, so a
 * readout can show both — "325.6 K at T359 (shown) · 318.4 K at T7999
 * (full detail)" — and neither disagrees with the colour under the cursor
 * without saying why.
 */
export interface FullDetail {
  /**
   * The full sum at the cell's node.
   */
  value: number;
  /**
   * The truncation `value` carries (`declared`) and the one the
   * displayed value carries (`truncated_to`).
   */
  truncation: SpectralTruncation;
}

/**
 * Where a decoded field sits on the Earth, flattened to scalars.
 *
 * A browser map library needs two things and this carries both: a CRS it
 * can name (`proj4`) and an affine placing the raster in
 * that CRS (`x0`, `y0`, `dx`, `dy`). Everything is `Option` because a
 * family that cannot state it says so rather than guessing — a Gaussian
 * grid's rows are not uniformly spaced, so its `dy` is absent, and a grid
 * this build does not model has none of it.
 */
export interface Georef {
  /**
   * The grid itself, as `core` models it.
   *
   * The scalars below are a flattened *view* of this, which is what a
   * host reads; this field is what the engine needs back to place a
   * point — `warp`, `probe`, and `contours` all invert through it, and
   * the inverse is a projection, not something four scalars reconstruct.
   * Keeping the two together means a field carries everything an
   * operation on it needs, which is the whole point of the host owning
   * the memory. It serialises, so a `Field` still survives a JSON round
   * trip whole.
   *
   * `core` does not derive `JsonSchema` (it is a decode-side crate and
   * the derive would follow it everywhere), so under the `schema`
   * feature this field is described as the tagged object it serialises
   * to. A generated `.d.ts` types it loosely and a host does not read it.
   */
  geometry: {
    kind: string;
    [key: string]: unknown;
  };
  /**
   * The family tag `core` reports: `latlon`, `gaussian`, `mercator`,
   * `rotated_latlon`, `lambert`, `polar_stereo`, `transverse_mercator`,
   * `lambert_azimuthal`, `space_view`, `lookup`, or `unsupported`.
   */
  kind: string;
  /**
   * The family name the **file** uses for its own grid — the decoder's
   * own grid-type string, and what a grid-type column should show.
   *
   * Usually `kind`, and deliberately not always. It is
   * more specific for a family this build does not place points on
   * (`spherical_harmonic`, `healpix`, `unsupported(3.99)`, all of kind
   * `unsupported`) and for the reduced families, whose rows are widened
   * onto their regular sibling's raster before anything reads them:
   * a `reduced_gg` message is `kind` `gaussian` and `label`
   * `reduced_gaussian`, which is what eccodes calls it and what the
   * other host shows (#645).
   *
   * A field's own georef reports the grid its *values* are on, so a
   * synthesised raster is `latlon` in both — see
   * `MessageInfo::grid` for the other
   * half of that split.
   */
  label: string;
  /**
   * Grid columns (west-to-east point count of one row).
   */
  ni: number;
  /**
   * Grid rows.
   */
  nj: number;
  /**
   * `[lat_min, lat_max, lon_min, lon_max]` in degrees. `lon_min` may
   * fall below -180 (or `lon_max` above 180) to describe a window
   * spanning the antimeridian; do not normalise it into range without
   * collapsing the span.
   */
  boundsLonlat: [number, number, number, number] | null;
  /**
   * The first and last scanned grid points, as
   * `[lat_first, lon_first, lat_last, lon_last]` (#726).
   *
   * The corner pair a message list shows, and **not** a bounding box:
   * these are two diagonally opposite grid points in scan order, so
   * `lat_last` may be less or greater than `lat_first`.
   * `bounds_lonlat` is the extent.
   *
   * An array for the reason `bounds_lonlat` is one, and in the order the
   * name states. `None` when the family has no raster, or when the
   * projection cannot place its far corner — reported absent rather than
   * clamped, so a host shows nothing instead of a plausible fiction.
   * `placement` says which of the two it is.
   *
   * Where the container states its corners they are reported as stated
   * (see `Georef::from_declared_corners`), so a grid can carry a
   * corner pair and still be `Placement::Unplaceable`: the file wrote
   * the numbers down, and the projection it describes cannot use them.
   */
  corners: [number, number, number, number] | null;
  /**
   * Whether this grid can be placed on the Earth, and why not — the
   * reason a `null` `corners` or
   * `bounds_lonlat` is `null` (#776).
   *
   * Computed from `geometry`, the same geometry that
   * fills `bounds_lonlat`, and never from the corners a container
   * reports. Never `Placement::PredefinedUnresolved`.
   */
  placement: Placement;
  /**
   * Whether the grid can be reprojected: a host may offer map targets
   * other than the grid's own coordinates, and the warp will place it.
   *
   * `core`'s `GridGeometry::reprojectable`, asked with
   * `scan`. **Its own field because it is not derivable
   * from `placement` and `kind`**
   * (#776). A placed grid can still decline: a lat/lon, Gaussian,
   * Mercator or rotated grid scanned east to west, because their inverse
   * maps assume columns run west to east, and a planar grid whose cell is
   * larger than the Earth radius the message declares. Deriving it in a
   * host would mean a family list and the scan rule in every host.
   */
  reprojectable: boolean;
  /**
   * Points per row for a **reduced** grid — `PL`, the number of values
   * each row really holds — and `None` for every other family (#244).
   *
   * A reduced grid's `geometry` is its regular
   * sibling's, widened to the widest row, which is what lets it reproject
   * like any other grid. The file's own points are fewer: an N32 reduced
   * Gaussian grid holds 6,114 values that the widened raster spreads over
   * 8,192 cells by repeating each short row's values. Anything that
   * reports individual points rather than painting the raster needs this
   * to report the file's.
   */
  pointsPerRow: number[] | null;
  /**
   * A PROJ string for the grid's own plane, for a map library that
   * takes one. `None` for a family this build does not name a CRS for.
   */
  proj4: string | null;
  /**
   * What `x0` / `y0` / `dx` / `dy` are measured in.
   */
  axisUnits: AxisUnits;
  /**
   * Plane coordinate of the first grid point's cell centre, along the
   * column axis. `None` when the family has no affine.
   */
  x0: number | null;
  /**
   * Plane coordinate of the first grid point's cell centre, along the
   * row axis.
   */
  y0: number | null;
  /**
   * Signed step between columns, in `Georef::axis_units`.
   */
  dx: number | null;
  /**
   * Signed step between rows. Negative for the usual north-to-south
   * scan, so `y0 + j * dy` walks the rows as stored.
   */
  dy: number | null;
  /**
   * The grid closes on itself in the column axis: one column step past
   * the last column lands back on the first. A renderer wraps rather
   * than clamping there, or the seam meridian draws as a hole.
   */
  periodicX: boolean;
  /**
   * The order `values` are in, so a consumer can walk them without
   * re-deriving it.
   *
   * This is the decoded raster's order, which is not always the order
   * the message stored: a GRIB message stored column-major is
   * transposed while decoding, so its `jConsecutive` is `false` here
   * even though its scanning-mode octet sets the bit (#792). The two
   * direction flags say which way the rows and columns run, which no
   * reader changes while decoding.
   *
   * A `core` type, like `geometry`, so it is described
   * to a schema consumer the same way — but written out property by
   * property rather than loosely, because a host reads these three and
   * #574 generates its declarations from this schema.
   * `the_scan_schema_names_every_field_scan_serialises` holds the two in
   * step.
   */
  scan: {
    iNegative: boolean;
    jPositive: boolean;
    jConsecutive: boolean;
  };
}

/**
 * One level's isoline segments, in grid coordinates.
 */
export interface Isoline {
  /**
   * The level these segments trace.
   */
  value: number;
  /**
   * `[i0, j0, i1, j1]` per segment, in fractional grid indices.
   */
  segments: ([number, number, number, number])[];
}

/**
 * One array a container holds and this build will not read, and why.
 *
 * Beside `Session::variables` rather than inside it: a host shows
 * these so a user can see *why* a name is absent from the list, instead of
 * wondering whether the file has it. Not an error — a container reads every
 * array it can and leaves the rest here (#709).
 */
export interface LeftOutArray {
  /**
   * The array's name, spelled as a readable one would be, so a host can
   * match it against the list it did get.
   */
  name: string;
  /**
   * Why, as the reader phrased it.
   */
  reason: string;
}

/**
 * One line through an array: its values along one axis, every other axis
 * held at an index (#172).
 *
 * A vertical profile or a time series at a grid point — the plot a viewer
 * draws beside a map when a user clicks a cell. The values are what
 * `Session::decode_slice` would report at that cell on each slice
 * along the axis, and a test holds the two to that.
 */
export interface Line {
  /**
   * The values along the axis, in index order. Read `mask` before a
   * value: an absent point still occupies its slot.
   */
  values: Values;
  /**
   * One byte per point: `1` present, `0` absent. Same length as `values`.
   */
  mask: number[];
  /**
   * Range and count over the present points.
   */
  stats: Stats;
  /**
   * The array's name.
   */
  variable: string;
  /**
   * The array's units, as its attributes state them.
   */
  units: string;
  /**
   * The axis the line runs along, named as the array names it.
   */
  dimension: string;
  /**
   * The axis's coordinate values, in index order — the times or levels to
   * label the line against.
   *
   * `None` when the axis has no 1-D coordinate array of its own name, or
   * when one of its values is absent: a coordinate with a hole has no
   * honest position to plot that point at, so the host falls back to
   * indices rather than being handed a gap it would have to invent across.
   */
  coordinates: number[] | null;
  /**
   * The coordinate array's units, when there are coordinates.
   */
  coordinateUnits: string | null;
}

/**
 * One message's metadata, built on demand.
 *
 * Lazy by design: a thousand-message file should not serialise a thousand
 * of these to open.
 */
export interface MessageInfo {
  /**
   * Position in `0..Session::count()`; the handle every other call
   * takes.
   */
  index: number;
  /**
   * Byte offset of the message's first byte within the container, so a
   * host can range-fetch this message alone on a later visit.
   */
  offsetBytes: number;
  /**
   * The parameter's name, under the same contract as
   * `Field::parameter`: the table's name, or `Parameter <codes>`
   * naming the codes no table in this build resolved.
   */
  parameter: string;
  /**
   * The table's short name for the parameter, e.g. `"2t"`. Empty when
   * the parameter did not resolve.
   */
  abbreviation: string;
  /**
   * Units as the parameter's table states them.
   */
  units: string;
  /**
   * The level, rendered — `"500 hPa"`, `"2 m above ground"`.
   */
  level: string;
  /**
   * The level's surface type on its own, for grouping messages that
   * share a surface at different values.
   */
  levelType: string;
  /**
   * Reference (analysis) time as RFC 3339. `None` when the message
   * carries no usable date.
   */
  referenceTime: string | null;
  /**
   * Forecast time relative to `reference_time`, rendered — `"+6h"`, or
   * `"+30 Minute"` for a unit the edition does not convert to hours.
   */
  forecast: string;
  /**
   * Which packing the data section uses, named — what decodes it, and
   * the first thing to look at when a decode is wrong.
   */
  packing: string;
  /**
   * The grid the message **declares**, not the one its field is decoded
   * onto.
   *
   * The two differ for the families that carry no raster of their own:
   * a spectral message declares a `"spherical_harmonic"` grid and a
   * HEALPix one a `"healpix"` grid, both of kind `"unsupported"` —
   * nothing places a point on either — while
   * `Session::decode` hands back a field on the synthesised
   * `"latlon"` grid (#580). This is the message list's answer, so it
   * describes the file; `Field::georef` is the field's, so it
   * describes where the values are. `size_label`
   * names the native shape beside it.
   *
   * `None` only for a GRIB1 message that carries no §2 at all and whose
   * `pds.grid_number` is not a predefined grid this build's catalogue
   * resolves — either 255, "no predefined grid", or a number outside the
   * catalogue. `placement` tells the two apart.
   */
  grid: Georef | null;
  /**
   * Whether this message's **values** can be placed on the Earth, and
   * why not (#776) — the answer a message list reads to decide whether
   * it can draw the message at all.
   *
   * Where the values land rather than what the file declares, which is
   * the difference from `grid.placement`. The two differ only for the
   * families whose values are synthesised onto a raster: a spectral or
   * HEALPix message declares a `no_raster` grid, and its values land on
   * a global lat/lon one, so this is `Placement::Placed`. Always the
   * `Georef::placement` `Session::place_message` reports when
   * that call succeeds; `place_message_agrees_with_decode.rs` holds the
   * two together over the corpus.
   *
   * With no `grid`, this is `Placement::PredefinedUnresolved` when the
   * message names a predefined grid this build cannot resolve, and
   * `Placement::NoRaster` when it names none (grid number 255).
   *
   * Placed is not decodable: a GRIB1 matrix-of-values or GRIB2
   * bi-Fourier message is refused by `Session::decode`
   * whatever this says, and the refusal names the call that reads it.
   */
  placement: Placement;
  /**
   * Whether the grid this message's values land on can be reprojected —
   * the answer a projection picker reads, and
   * `Georef::reprojectable` of the same grid
   * `placement` describes. `false` when there is no
   * grid.
   *
   * Like `placement`, it is about the values: a spectral message's
   * declared grid does not reproject and its synthesised lat/lon field
   * does, so this is `true`.
   */
  reprojectable: boolean;
  /**
   * How the file names its own grid where `Ni × Nj` is not how it is
   * described — `N32`, `O1280`, `T639`.
   */
  sizeLabel: string | null;
  /**
   * What `Session::decode` will set as
   * `Field::truncation` for this message: the map of a spectral
   * message declaring more wavenumbers than the synthesis grid carries
   * is band-limited, and says so (#637). Read from the declaration, so a
   * message list can show it before anything is decoded. `None` for
   * everything else.
   */
  truncation: SpectralTruncation | null;
  /**
   * Forecast lead time in whole hours, `None` for a template that states
   * none.
   *
   * `forecast` is the same fact rendered for display
   * ("+6 h", an averaging interval, "analysis"); this is the number, for
   * a host that sorts or animates by it.
   */
  forecastHours: number | null;
  /**
   * GRIB1's `P1` octet, when the time-range indicator is one that makes
   * it a lead time rather than the second half of an interval.
   *
   * `None` for GRIB2, which has no such octet, and for GRIB1 time range
   * 10, where `P1` is a two-octet value and not this field.
   */
  p1Octet: number | null;
  /**
   * The originating centre, named from the CCT common code table, or
   * `Centre <n>` when the table has no entry.
   */
  originatingCentre: string;
  /**
   * The sub-centre, named from the originating centre's own table, and
   * `None` when there is no entry — which is the common case.
   */
  subCentre: string | null;
  /**
   * The GRIB edition: 1 or 2.
   */
  edition: number | null;
  /**
   * The GRIB2 discipline, named. `None` for GRIB1, which has no
   * discipline.
   */
  discipline: string | null;
  /**
   * The length the message declares for itself, in bytes.
   *
   * Distinct from `offset_bytes`, which says where
   * it starts. Together they are the range a host would re-fetch.
   */
  totalLengthBytes: number | null;
  /**
   * The GRIB2 production status, named. `None` for GRIB1.
   */
  productionStatus: string | null;
  /**
   * The GRIB2 data type — analysis, forecast, reanalysis — named. `None`
   * for GRIB1.
   */
  dataType: string | null;
  /**
   * Whether this message's `u`/`v` components are resolved along the
   * grid's own axes rather than east and north (GRIB1 GDS octet 17 bit 5,
   * GRIB2 §3 Flag Table 3.3 bit 5).
   *
   * What a vector plot must know before it draws an arrow (#241): a
   * grid-relative pair drawn as east/north points wrong by the grid's
   * convergence angle, which over a continental Lambert domain is tens of
   * degrees. HRRR and NAM set it. `None` for a message whose family
   * states no resolution flags, and for a container that is not GRIB.
   */
  uvRelativeToGrid: boolean | null;
}

/**
 * One point probed out of a message by index
 * (`Session::probe_message`): the value the decoded field shows,
 * and for a band-limited spectral message the file's full-detail value at
 * the same cell.
 */
export interface MessageProbe {
  /**
   * Latitude asked for, echoed back.
   */
  lat: number;
  /**
   * Longitude asked for, echoed back.
   */
  lon: number;
  /**
   * Fractional column the point landed on.
   */
  i: number;
  /**
   * Fractional row the point landed on.
   */
  j: number;
  /**
   * The decoded field's value at the cell — what the map shows there.
   * `None` when the cell is masked.
   */
  value: number | null;
  /**
   * Set only when the decoded field is band-limited
   * (`Field::truncation` is set): the full sum at the same cell.
   */
  fullDetail: FullDetail | null;
}

/**
 * Colour, decided once in Rust and exported as data.
 */
export interface PaletteOptions {
  /**
   * A colormap name `core` knows. Unknown names are an error rather than a
   * silent fallback: a host that misspells one should hear about it.
   */
  colormap?: string | null;
  /**
   * A colormap given as its 768-byte lookup table instead of by name, as
   * `RenderOptions::colormap_table`
   * describes, and refused on the same terms.
   */
  colormapTable?: number[] | null;
  /**
   * High end of the display range. `None` takes the field's own maximum.
   */
  max?: number | null;
  /**
   * Low end of the display range. `None` takes the field's own minimum.
   */
  min?: number | null;
  /**
   * Walk the colormap high-to-low. Applied after `colormap` is resolved,
   * so a reversed unknown name is still an error.
   */
  reversed?: boolean;
  /**
   * `"linear"` (default) or `"log10"`.
   */
  scale?: string | null;
}

/**
 * Whether a grid can be placed on the Earth, and why not when it cannot
 * (#776).
 *
 * The reason `Georef::corners` alone does not give: a `null` corner pair
 * can mean there is nothing to place, or that there is a raster and the
 * projection cannot place it, and a host acts differently on the two. The
 * first has nothing to draw. The second still draws in its own grid
 * coordinates and only the map is missing.
 *
 * A sibling of the value rather than a wrapper around it (#574's decision):
 * the corners stay a plain `[f64; 4] | null`, and this says which absence
 * a `null` is.
 */
export type Placement =
  /**
   * The grid has a raster and its projection places at least part of it:
   * `Georef::bounds_lonlat` is present.
   *
   * Not a promise that every cell has a position. A full-disc satellite
   * image is placed, and its corner pixels look past the Earth, so its
   * `Georef::corners` is `null` while the disc itself is on the map.
   */
  | "placed"
  /**
   * There is genuinely nothing to place: the family carries no grid
   * points of its own (spectral coefficients, HEALPix pixels, bi-Fourier
   * coefficients), the grid declares zero columns or rows, or the
   * message states no grid at all (GRIB1 predefined grid 255).
   *
   * Not "this build cannot read the grid": a template this build does not
   * model is `Unsupported`, and a raster with no
   * usable projection is `Unplaceable`. Those two
   * have grid points; this one has none.
   *
   * On a `MessageInfo` this is about where the *values* land, so a
   * spectral or HEALPix message is `Placed` there: its
   * values are synthesised onto a global lat/lon raster, even though the
   * grid it declares is `no_raster`.
   */
  | "no_raster"
  /**
   * There is a raster, and nothing places any of it on the Earth: a
   * polar stereographic grid stating a zero grid step, a Lambert cone
   * whose standard parallels are both on the equator, a first point the
   * forward map sends to infinity, a §3.90 camera that sees no Earth, a
   * GRIB2 rotation or scale factor that is not a finite number (#823), or
   * a NetCDF, HDF5 or Zarr slice with no coordinates to place it by. The
   * grid still renders in its own grid coordinates; it has no position on
   * a map.
   */
  | "unplaceable"
  /**
   * The message declares a grid in a template this build does not model
   * (a GRIB2 §3 template such as 3.4 or 3.101, a GRIB1 data
   * representation type such as 90), so the grid has points and this
   * build knows neither their shape nor where they are.
   *
   * Kept apart from `NoRaster` because the reasons
   * differ and so does what fixes them: nothing makes a spectral field a
   * raster, and support for the template would make this one placeable.
   * Nothing decodes it today, so a host offers no render.
   */
  | "unsupported"
  /**
   * A GRIB1 message with no grid description, identified only by a
   * predefined grid number (WMO ON388 Table B) this build does not have
   * in its catalogue. The message names a grid; this build cannot say
   * which.
   *
   * Only `MessageInfo::placement` reports this. A `Georef` exists
   * only once a grid is known, so its placement is never this one.
   */
  | "predefined_unresolved";

/**
 * One point sampled out of a field.
 */
export interface Probe {
  /**
   * Latitude asked for, echoed back.
   */
  lat: number;
  /**
   * Longitude asked for, echoed back.
   */
  lon: number;
  /**
   * Fractional column / row the point landed on.
   */
  i: number;
  /**
   * Fractional row the point landed on.
   */
  j: number;
  /**
   * `None` when the cell is masked.
   */
  value: number | null;
}

/**
 * A painted raster: RGBA bytes plus the dimensions they cover.
 */
export interface Raster {
  /**
   * Non-premultiplied RGBA, `width * height * 4` bytes, row-major from the
   * top-left. Ready for `putImageData` or an `RGBA8` texture upload.
   */
  rgba: number[];
  /**
   * Raster columns.
   */
  width: number;
  /**
   * Raster rows.
   */
  height: number;
}

/**
 * How a field should be projected and painted.
 *
 * The loose strings are deliberate and are the host's wire shape: a picker
 * sends `"equirectangular"`, not an enum discriminant. `ResolvedOptions` is
 * where they become a closed vocabulary, and an unrecognised one is an error
 * there rather than a silent fallback — a typo should say so instead of
 * painting the wrong thing.
 *
 * `#[non_exhaustive]`, like every other option struct here, so start from
 * `Default` and assign the fields the call needs.
 */
export interface RenderOptions {
  /**
   * Which target to paint into: `"source"`, `"equirectangular"`,
   * `"web_mercator"`, `"orthographic"`, `"polar_stereographic"`,
   * `"mollweide"`, `"robinson"` or `"equal_earth"`.
   */
  projection: string;
  /**
   * `"nearest"` or `"bilinear"`. A grid that is a list of cell centres
   * downgrades to nearest whatever this says, since its index-adjacent cells
   * need not be spatially adjacent.
   */
  resampling: string;
  /**
   * Paint row 0 at the bottom rather than the top.
   */
  flipY: boolean;
  /**
   * North edge of the manual window — see
   * `bounds_lat_min`.
   */
  boundsLatMax?: number | null;
  /**
   * South edge of a manual render window (degrees). All four must be `Some`
   * and form a non-degenerate box, or the window falls back to the grid's
   * own extent. `lon_min`/`lon_max` may lie outside [-180, 180] to describe a
   * window that crosses the antimeridian.
   */
  boundsLatMin?: number | null;
  /**
   * East edge of the manual window — see
   * `bounds_lat_min`.
   */
  boundsLonMax?: number | null;
  /**
   * West edge of the manual window — see
   * `bounds_lat_min`.
   */
  boundsLonMin?: number | null;
  /**
   * Free-form projection centre for the azimuthal targets (degrees).
   * `"orthographic"` reads both; `"polar_stereographic"` and the three world
   * targets read only `center_lon`, as their central
   * meridian. Either field `None` falls back to the preset/default for that
   * component.
   */
  centerLat?: number | null;
  /**
   * Free-form projection-centre longitude — see
   * `center_lat`.
   */
  centerLon?: number | null;
  /**
   * A colormap name `core` knows. `None` is the default map. An unknown name
   * is an error rather than a silent fallback.
   */
  colormap?: string | null;
  /**
   * A colormap given as its lookup table instead of by name: 768 bytes, 256
   * RGB entries from the low end of the ramp to the high end. This is how an
   * imported colour table reaches the painter — a host parses the file once
   * (`fieldglass::parse_cpt`) and sends the table it compiles to — and it
   * takes `reverse_colormap` like any named map.
   *
   * Naming a `colormap` as well is an error rather than a
   * guess at which one was meant, and so is a table of any other length.
   */
  colormapTable?: number[] | null;
  /**
   * Output raster rows — the other half of `width`.
   *
   * The pair is what a map view asks for: *this window at W × H pixels*. It
   * is read by the two lat/lon-box targets (`"equirectangular"` and
   * `"web_mercator"`) and, like every option in this struct, it is read the
   * same way by the render, the overlay projection, the contour projection
   * and the pixel probe — so all four paint into one raster and a probe
   * still reads the cell the render painted.
   *
   * Three rules, each of them deliberate:
   *
   * * **Both or neither.** One alone is an `Error::InvalidOption`, not a
   *   silent fallback. The four `bounds_*` fields do fall back silently,
   *   because three edges cannot make a box and "the grid's own extent" is
   *   the natural completion; a width with no height has no such completion
   *   that is not invented.
   * * **An explicit size is the answer.** It bypasses both
   *   `MIN_REPROJECTED_LONG_EDGE` and the window-shaped sizing a
   *   coordinate-lookup grid gets, so 512 × 512 is 512 × 512. A caller that
   *   wants the floor is the caller that leaves these unset.
   * * **Ignored by every other target.** The azimuthal and world ones size
   *   themselves from the aspect their projection fixes — a square for the
   *   discs, the projection's own ratio for Mollweide, Robinson and Equal
   *   Earth — and `"source"` paints the array as stored, at `ni × nj`, which
   *   is the one view whose whole point is that nothing resampled it. Naming
   *   a size for any of them is not an error, the same way naming a
   *   `projection_preset` on a box target is not.
   *
   * Zero on either axis, and a raster past this target's allocation ceiling
   * (`isize::MAX` bytes — 2 GB on wasm32, where a pixel count well inside
   * `u32` can still be too many bytes), are refused rather than allocated. A
   * raster that merely will not fit in the memory available is the caller's
   * own budget.
   */
  height?: number | null;
  /**
   * Preset selector for the parameterised targets. `"orthographic"` reads a
   * centre preset (`"atlantic"` (0°N 0°E, default), `"indian"` (0°N 90°E),
   * `"pacific"` (0°N 180°E), `"americas"` (0°N 270°E), `"north_pole"`,
   * `"south_pole"`); `"polar_stereographic"` reads a hemisphere preset
   * (`"north"` (default), `"south"`). Ignored by the lat/lon-box targets.
   * `None`/unknown falls back to the default.
   *
   * Superseded by `center_lat` /
   * `center_lon` when those are supplied: the free-form
   * centre wins, the preset is only the fallback.
   */
  projectionPreset?: string | null;
  /**
   * High end of the manual range — see `range_min`.
   */
  rangeMax?: number | null;
  /**
   * Low end of a manual display range. When either end is `None` the caller
   * takes the computed min/max over the present cells.
   */
  rangeMin?: number | null;
  /**
   * Walk the colormap high-to-low. `None` is `false`.
   */
  reverseColormap?: boolean | null;
  /**
   * `"linear"` (default) or `"log10"`. `None` is linear; anything else is an
   * error, matching the colormap field.
   */
  scaleMode?: string | null;
  /**
   * Output raster columns for the lat/lon-box targets (#465). `None` keeps
   * the sizing described on `height`.
   */
  width?: number | null;
}

/**
 * The container a session was opened from.
 *
 * Named for the source rather than `Format` so it does not collide with
 * `core`'s detection enum, which also answers NetCDF and "unknown" — this
 * one enumerates only what a session can actually be.
 *
 * **Not gated by the format features (#552).** It is the wire vocabulary a
 * host compares strings against, and dropping a variant with its decoder
 * would change the JSON schema for every consumer of the shipped
 * declarations. A build without `grib1` simply never constructs
 * `SourceFormat::Grib1`, because it never opens a session over one.
 */
export type SourceFormat =
  /**
   * WMO FM 92 GRIB edition 1.
   */
  | "grib1"
  /**
   * WMO FM 92 GRIB edition 2.
   */
  | "grib2"
  /**
   * NetCDF, either classic (CDF-1/2/5) or NetCDF-4 over HDF5.
   *
   * Spelled `netcdf` on the wire, not the `snake_case` derive's
   * `net_cdf`: the other two variants are `grib1` and `grib2`, and a
   * host comparing strings should not have to remember that one of the
   * three grew an underscore from how the Rust identifier is
   * capitalised. Pinned rather than left to the rename rule because this
   * is the vocabulary the JSON schema publishes; #662 added the variant
   * and it has not shipped in a release, so this is the last moment
   * changing it is free.
   */
  | "netcdf"
  /**
   * A Zarr store, v2 or v3, opened from its objects with
   * `Session::open_store` (#704, behind the `zarr` feature).
   */
  | "zarr";

/**
 * That a spectral field's map shows fewer wavenumbers than the file holds
 * (#637): the truncation the message declares, and the one its values
 * were synthesised at.
 *
 * **A smoothed field is never shown silently.** A spectral message's
 * values are synthesised onto the 0.5° global grid, which carries
 * wavenumbers up to T359; a message declaring more is band-limited to
 * that, which is the correct picture at that resolution and a different,
 * smoother field from the one the file holds. This is the fact a host
 * shows beside it — "shown at T359 of T7999" — carried as data so that
 * every host has it rather than only the one that wrote the caption.
 *
 * A value read out of such a field is the smoothed one; the file's own
 * value at a point is `Session::probe_message`.
 */
export interface SpectralTruncation {
  /**
   * The truncation `T` the message declares — what its coefficients
   * hold.
   */
  declared: number;
  /**
   * The truncation the values were synthesised at, always below
   * `declared`.
   */
  truncatedTo: number;
}

/**
 * Range and count of the present cells. Absent cells are excluded, so an
 * all-masked field reports no range at all rather than `±inf`.
 */
export interface Stats {
  /**
   * Smallest present value. `None` when no cell is present.
   */
  min: number | null;
  /**
   * Largest present value. `None` when no cell is present.
   */
  max: number | null;
  /**
   * How many cells are present, i.e. the count of `1`s in the mask.
   */
  validCount: number;
}

/**
 * Decoded values, in whichever element type the source supports.
 */
export type Values =
  /**
   * Single precision — what a source packed to 32 bits or fewer decodes
   * to, and what `Dtype::F32` forces.
   */
  | {
    dtype: "f32";
    data: number[];
  }
  /**
   * Double precision — an IEEE-64 source, or `Dtype::F64`.
   */
  | {
    dtype: "f64";
    data: number[];
  };

/**
 * One renderable variable of an array dataset.
 */
export interface VariableInfo {
  /**
   * Position in `Session::variables`, and the handle
   * `Session::decode_slice` takes.
   */
  index: number;
  /**
   * The variable's name, path-qualified for a nested group.
   */
  name: string;
  /**
   * Its axes in declared (C) order — the order `y_dim` and `x_dim`
   * index into, and the order `slice_indices` is given in.
   */
  dims: DimensionInfo[];
  /**
   * The element type as the file declares it, named.
   */
  dtype: string;
  /**
   * Units from the variable's own attributes, empty when it states none.
   */
  units: string;
  /**
   * Which axis the file's own conventions say is latitude, when they say
   * so. `None` for a WRF or satellite file, whose horizontal axes are
   * projected and carry no CF axis attribute — the caller picks, which is
   * why this is a hint rather than the answer.
   */
  detectedYDim: number | null;
  /**
   * The longitude half of `detected_y_dim`, under the same rule.
   */
  detectedXDim: number | null;
  /**
   * Which axis is time: the one whose coordinate the file's conventions
   * mark as time (`axis = "T"`, `standard_name = "time"`, or units of the
   * form `hours since …`), or one named `time`. Never an image axis. What
   * a host animates along (#170).
   */
  detectedTimeDim: number | null;
}

/**
 * How to draw a vector field: which cells get an arrow, how long the arrows
 * are, and which way the components point (#241).
 */
export interface VectorOptions {
  /**
   * **Are the components along the grid's axes rather than east and north?**
   *
   * GRIB says so in its resolution flags, and the common projected files —
   * HRRR, NAM — set it. Drawn as if they were east and north, a grid-relative
   * pair points wrong by the grid's convergence angle: up to tens of degrees
   * away from the projection's central meridian. When this is set the
   * components are rotated through the grid's own north, per cell.
   */
  gridRelative?: boolean;
  /**
   * The speed the longest arrow stands for.
   *
   * `None` takes the fastest cell **that is drawn**, so the plot fills itself
   * at any spacing — which also means a sparser spacing can report a slower
   * reference, having skipped the fastest cell. State one to hold the scale
   * still across two renders a user is comparing.
   */
  referenceSpeed?: number | null;
  /**
   * Draw an arrow every `spacing` grid cells, in both directions. `None` and
   * `0` mean "about 24 arrows across the grid", which reads at any size.
   */
  spacing?: number | null;
}

/**
 * How a field should be resampled onto a geographic box.
 */
export interface WarpOptions {
  /**
   * Bilinear when true, nearest otherwise. A grid that is a list of cell
   * centres downgrades to nearest whatever this says.
   */
  bilinear?: boolean;
  /**
   * Output window `[lat_min, lat_max, lon_min, lon_max]`. `None` uses the
   * source grid's own extent.
   */
  bounds?: [number, number, number, number] | null;
  /**
   * Output raster rows — the other half of `width`. `None`
   * keeps the source grid's `nj`.
   *
   * Together with `bounds` this is the whole of what a map
   * view asks for: *this window at W × H pixels*. Send both or neither; one
   * alone is an `Error::InvalidOption`, for the reason
   * `RenderOptions::height` gives. Zero on either axis, and a raster
   * past this target's allocation ceiling, are refused rather than
   * allocated.
   */
  height?: number | null;
  /**
   * Output raster columns. `None` keeps the source grid's `ni` (#465).
   */
  width?: number | null;
}

/**
 * A resampled raster: `Session::warp` without the paint step.
 */
export interface Warped {
  /**
   * Resampled values, row-major from the north-west corner of `bounds`.
   */
  values: number[];
  /**
   * One byte per output pixel: `1` present, `0` off-grid or masked.
   */
  mask: number[];
  /**
   * Output columns.
   */
  width: number;
  /**
   * Output rows.
   */
  height: number;
  /**
   * `[lat_min, lat_max, lon_min, lon_max]` of the output window.
   */
  bounds: [number, number, number, number];
}
