//! Geolocation cross-check for the projected NetCDF grids (#168, decision 0004).
//!
//! The fixtures' coordinate geometry was generated by *independent* NumPy
//! implementations of the standard projection formulas (Snyder Lambert; GOES-R
//! PUG fixed grid) and dumped to sibling `*.oracle.json`. These tests resolve
//! the projection from the on-disk metadata exactly as the render path does,
//! rebuild the `fieldglass_core` projector, and assert it reproduces the oracle
//! geolocation — a genuine cross-language check, not a tautology.

use fieldglass_core::{
    GeostationaryParams, GeostationaryProjector, LambertParams, LambertProjector, LatLonParams,
    MercatorParams, PolarStereoParams, PolarStereoProjector, latlon_inverse, mercator_inverse,
};
use fieldglass_netcdf::{
    DatasetView, NetcdfBacking, NetcdfReader, apply_scale_offset, resolve_cf_geostationary,
    resolve_wrf_lambert, resolve_wrf_latlon, resolve_wrf_mercator, resolve_wrf_polar_stereo,
};
use serde_json::Value;

const WRF: &[u8] = include_bytes!("fixtures/wrf_lambert.nc");
const WRF_ORACLE: &str = include_str!("fixtures/wrf_lambert.nc.oracle.json");
const WRF_POLAR: &[u8] = include_bytes!("fixtures/wrf_polar.nc");
const WRF_POLAR_ORACLE: &str = include_str!("fixtures/wrf_polar.nc.oracle.json");
const WRF_MERCATOR: &[u8] = include_bytes!("fixtures/wrf_mercator.nc");
const WRF_MERCATOR_ORACLE: &str = include_str!("fixtures/wrf_mercator.nc.oracle.json");
const WRF_LATLON: &[u8] = include_bytes!("fixtures/wrf_latlon.nc");
const WRF_LATLON_ORACLE: &str = include_str!("fixtures/wrf_latlon.nc.oracle.json");
const GOES: &[u8] = include_bytes!("fixtures/goes_geostationary.nc");
const GOES_ORACLE: &str = include_str!("fixtures/goes_geostationary.nc.oracle.json");

fn view(bytes: &[u8]) -> (NetcdfReader, DatasetView) {
    let reader = NetcdfReader::from_bytes(bytes.to_vec()).expect("parse");
    let view = match &reader.backing {
        NetcdfBacking::Classic(h) => DatasetView::from_classic(h),
        NetcdfBacking::Hdf5(_) => {
            DatasetView::from_hdf5(&reader.hdf5_metadata().expect("hdf5 metadata"))
        }
    };
    (reader, view)
}

/// Decode a variable by name to dense `f64`. Coordinate fixtures carry no
/// masked cells; panicking on one (rather than skipping it) keeps every flat
/// index aligned with its `[j, i]` grid cell, which the corner reads rely on.
fn decode_named(reader: &NetcdfReader, view: &DatasetView, name: &str) -> Vec<f64> {
    let idx = view
        .vars
        .iter()
        .find(|v| v.name == name)
        .unwrap_or_else(|| panic!("{name} present"))
        .decode_index;
    reader
        .decode_variable_values(idx)
        .expect("decode")
        .into_iter()
        .map(|v| v.unwrap_or_else(|| panic!("{name} has a masked cell")))
        .collect()
}

#[test]
fn wrf_lambert_grid_reproduces_xlat_xlong() {
    let (reader, view) = view(WRF);
    let oracle: Value = serde_json::from_str(WRF_ORACLE).unwrap();
    let ni = oracle["nx"].as_u64().unwrap() as u32;
    let nj = oracle["ny"].as_u64().unwrap() as u32;

    // Grid origin = the XLAT/XLONG (0,0) corner, exactly as the render path reads it.
    let lat0 = decode_named(&reader, &view, "XLAT")[0];
    let lon0 = decode_named(&reader, &view, "XLONG")[0];
    let g =
        resolve_wrf_lambert(&view.global_attrs, lat0, lon0, ni, nj).expect("WRF Lambert resolves");

    let proj = LambertProjector::new(LambertParams {
        ni: g.ni,
        nj: g.nj,
        lat_first: g.lat_first,
        lon_first: g.lon_first,
        lad: g.lad,
        lov: g.lov,
        dx_metres: g.dx_metres,
        dy_metres: g.dy_metres,
        latin1: g.latin1,
        latin2: g.latin2,
    });

    assert_samples_invert(&oracle, |lat, lon| proj.inverse(lat, lon));
}

/// Every sampled oracle (XLAT, XLONG) must invert back to its grid index (i, j).
fn assert_samples_invert(
    oracle: &Value,
    inverse: impl Fn(f64, f64) -> Option<fieldglass_core::GridIndex>,
) {
    for s in oracle["samples"].as_array().unwrap() {
        let (i, j) = (s["i"].as_f64().unwrap(), s["j"].as_f64().unwrap());
        let (lat, lon) = (s["lat"].as_f64().unwrap(), s["lon"].as_f64().unwrap());
        let idx = inverse(lat, lon).unwrap_or_else(|| panic!("({lat},{lon}) on grid"));
        assert!(
            (idx.i - i).abs() < 1e-2 && (idx.j - j).abs() < 1e-2,
            "XLAT/XLONG ({lat},{lon}) → ({}, {}), expected ({i}, {j})",
            idx.i,
            idx.j
        );
    }
}

#[test]
fn wrf_polar_stereo_grid_reproduces_xlat_xlong() {
    let (reader, view) = view(WRF_POLAR);
    let oracle: Value = serde_json::from_str(WRF_POLAR_ORACLE).unwrap();
    let ni = oracle["nx"].as_u64().unwrap() as u32;
    let nj = oracle["ny"].as_u64().unwrap() as u32;

    let lat0 = decode_named(&reader, &view, "XLAT")[0];
    let lon0 = decode_named(&reader, &view, "XLONG")[0];
    let g = resolve_wrf_polar_stereo(&view.global_attrs, lat0, lon0, ni, nj)
        .expect("WRF polar stereographic resolves");
    assert!(!g.south_pole, "TRUELAT1 = 60 is a north-pole grid");

    let proj = PolarStereoProjector::new(PolarStereoParams {
        ni: g.ni,
        nj: g.nj,
        lat_first: g.lat_first,
        lon_first: g.lon_first,
        lov: g.lov,
        lad: g.lad,
        dx_metres: g.dx_metres,
        dy_metres: g.dy_metres,
        south_pole: g.south_pole,
    });
    assert_samples_invert(&oracle, |lat, lon| proj.inverse(lat, lon));
}

#[test]
fn wrf_mercator_grid_reproduces_xlat_xlong() {
    let (reader, view) = view(WRF_MERCATOR);
    let oracle: Value = serde_json::from_str(WRF_MERCATOR_ORACLE).unwrap();
    let ni = oracle["nx"].as_u64().unwrap() as u32;
    let nj = oracle["ny"].as_u64().unwrap() as u32;

    // Mercator is corner-pinned: both the origin and the far corner come from
    // XLAT/XLONG, exactly as the render path reads them.
    let xlat = decode_named(&reader, &view, "XLAT");
    let xlong = decode_named(&reader, &view, "XLONG");
    let far = (ni as usize * nj as usize) - 1;
    let g = resolve_wrf_mercator(
        &view.global_attrs,
        xlat[0],
        xlong[0],
        xlat[far],
        xlong[far],
        ni,
        nj,
    )
    .expect("WRF Mercator resolves");
    assert!(
        (g.lat_last - oracle["lat_last"].as_f64().unwrap()).abs() < 1e-6
            && (g.lon_last - oracle["lon_last"].as_f64().unwrap()).abs() < 1e-6,
        "far corner matches the oracle"
    );

    let p = MercatorParams {
        ni: g.ni,
        nj: g.nj,
        lat_first: g.lat_first,
        lon_first: g.lon_first,
        lat_last: g.lat_last,
        lon_last: g.lon_last,
    };
    assert_samples_invert(&oracle, |lat, lon| mercator_inverse(&p, lat, lon));
}

#[test]
fn wrf_latlon_grid_reproduces_xlat_xlong() {
    let (reader, view) = view(WRF_LATLON);
    let oracle: Value = serde_json::from_str(WRF_LATLON_ORACLE).unwrap();
    let ni = oracle["nx"].as_u64().unwrap() as u32;
    let nj = oracle["ny"].as_u64().unwrap() as u32;

    // Unrotated lat-lon is corner-pinned: both the origin and the far corner
    // come from XLAT/XLONG, exactly as the render path reads them.
    let xlat = decode_named(&reader, &view, "XLAT");
    let xlong = decode_named(&reader, &view, "XLONG");
    let far = (ni as usize * nj as usize) - 1;
    let g = resolve_wrf_latlon(
        &view.global_attrs,
        xlat[0],
        xlong[0],
        xlat[far],
        xlong[far],
        ni,
        nj,
    )
    .expect("WRF unrotated lat-lon resolves");
    assert!(
        (g.lat_last - oracle["lat_last"].as_f64().unwrap()).abs() < 1e-6
            && (g.lon_last - oracle["lon_last"].as_f64().unwrap()).abs() < 1e-6,
        "far corner matches the oracle"
    );

    let p = LatLonParams {
        ni: g.ni,
        nj: g.nj,
        lat_first: g.lat_first,
        lon_first: g.lon_first,
        lat_last: g.lat_last,
        lon_last: g.lon_last,
    };
    assert_samples_invert(&oracle, |lat, lon| latlon_inverse(&p, lat, lon));
}

#[test]
fn goes_geostationary_grid_reproduces_oracle_geolocation() {
    let (reader, view) = view(GOES);
    let oracle: Value = serde_json::from_str(GOES_ORACLE).unwrap();

    // Resolve from the grid_mapping variable + scaled x/y, as the render path does.
    let gm_attrs = view
        .vars
        .iter()
        .find(|v| v.name == "goes_imager_projection")
        .expect("grid_mapping var")
        .attrs
        .clone();
    let read_scaled = |name: &str| {
        let var = view.vars.iter().find(|v| v.name == name).unwrap();
        let raw = decode_named(&reader, &view, name);
        apply_scale_offset(&raw, &var.attrs)
    };
    let x = read_scaled("x");
    let y = read_scaled("y");
    let g = resolve_cf_geostationary(&gm_attrs, &x, &y).expect("geostationary resolves");

    let proj = GeostationaryProjector::new(GeostationaryParams {
        ni: g.ni,
        nj: g.nj,
        h_metres: g.h_metres,
        r_eq: g.r_eq,
        r_pol: g.r_pol,
        sub_lon_deg: g.sub_lon_deg,
        sweep_x: g.sweep_x,
        x0: g.x0,
        dx_rad: g.dx_rad,
        y0: g.y0,
        dy_rad: g.dy_rad,
    });

    // Each on-disk pixel's scan angles forward-project to the oracle lat/lon, and
    // those invert back to the pixel index. Tolerances absorb the int16
    // quantization of x/y (~7e-7 rad ≈ tens of metres on the ground).
    for s in oracle["samples"].as_array().unwrap() {
        let (i, j) = (
            s["i"].as_u64().unwrap() as f64,
            s["j"].as_u64().unwrap() as f64,
        );
        let (olat, olon) = (s["lat"].as_f64().unwrap(), s["lon"].as_f64().unwrap());
        // Every on-disk pixel's scan angles forward-project to the oracle lat/lon.
        let xs = g.x0 + i * g.dx_rad;
        let ys = g.y0 + j * g.dy_rad;
        let (lat, lon) = proj
            .scan_to_lonlat(xs, ys)
            .unwrap_or_else(|| panic!("pixel ({i},{j}) on disk"));
        assert!(
            (lat - olat).abs() < 2e-2 && (lon - olon).abs() < 2e-2,
            "scan ({xs},{ys}) → ({lat},{lon}), oracle ({olat},{olon})",
        );
        // …and the lat/lon inverts back to the pixel index. Skip the grid edge:
        // int16 quantization can nudge a boundary pixel a hair outside the
        // strict bounds (the render warp samples the interior).
        let edge = i == 0.0 || j == 0.0 || i == (g.ni - 1) as f64 || j == (g.nj - 1) as f64;
        if !edge {
            let idx = proj.inverse(olat, olon).expect("oracle lat/lon on grid");
            assert!(
                (idx.i - i).abs() < 5e-2 && (idx.j - j).abs() < 5e-2,
                "({olat},{olon}) → index ({}, {}), expected ({i}, {j})",
                idx.i,
                idx.j
            );
        }
    }

    // The nadir (sub-satellite point) sits where x = y = 0.
    let nadir = proj.scan_to_lonlat(0.0, 0.0).expect("nadir on disk");
    assert!(nadir.0.abs() < 1e-6, "nadir latitude ≈ 0");
    assert!(
        (nadir.1 - g.sub_lon_deg).abs() < 1e-6,
        "nadir longitude = sub-sat"
    );
}
