//! The ECMWF local parameter table, cross-checked against eccodes (#424).
//!
//! `tables_ecmf.rs` is generated by parsing eccodes' concept-file *text*.
//! `fixtures/localconcepts_ecmf.ref.json` is what eccodes' own concept
//! *engine* answers for the same triples, collected by driving `grib_set` and
//! `grib_get` over a committed fixture. Two independent transcriptions of one
//! source agreeing is the point — a regex over definition files is exactly the
//! kind of thing that silently mis-joins a table, and #415 showed what an
//! unverified table costs.
//!
//! Committed, so the suite needs no eccodes at runtime. Regenerate both with
//! `python3 tools/gen_localconcepts_tables.py ecmf --oracle && cargo fmt`.

use fieldglass_grib2::{Originator, lookup_parameter};
use std::collections::BTreeMap;

const ORACLE: &str = include_str!("fixtures/localconcepts_ecmf.ref.json");

/// WMO Common Code Table C-11 code for ECMWF.
const ECMWF: u16 = 98;

/// `"<local tables version>/<discipline>/<category>/<number>"` -> what
/// `grib_get -p shortName,name,units` printed.
fn oracle() -> BTreeMap<String, String> {
    let parsed: serde_json::Value = serde_json::from_str(ORACLE).expect("oracle is valid JSON");
    assert_eq!(
        parsed["eccodes"].as_str(),
        Some("2.34.1"),
        "the oracle was built with a different eccodes than the repo pins"
    );
    parsed["resolved"]
        .as_object()
        .expect("resolved section")
        .iter()
        .map(|(k, v)| (k.clone(), v.as_str().expect("string").to_string()))
        .collect()
}

fn key(part: &str) -> (u8, u8, u8, u8) {
    let mut it = part
        .split('/')
        .map(|n| n.parse::<u8>().expect("numeric key part"));
    (
        it.next().unwrap(),
        it.next().unwrap(),
        it.next().unwrap(),
        it.next().unwrap(),
    )
}

/// eccodes prints `~` where a concept leaves a field unset; the generator
/// stores that as an empty string.
fn as_eccodes(value: &str) -> &str {
    if value.is_empty() { "~" } else { value }
}

/// Every entry the table ships resolves to exactly what eccodes reports.
///
/// Compared as the whole `shortName name units` line rather than field by
/// field: names contain spaces and so do units (`m of water equivalent`), so
/// splitting eccodes' output back into three fields cannot be done reliably —
/// but rebuilding the line from our three fields can.
#[test]
fn every_entry_matches_what_eccodes_reports() {
    let oracle = oracle();
    assert!(
        oracle.len() > 2_500,
        "only {} oracle entries — it is not loaded, so this proves nothing",
        oracle.len()
    );
    for (raw, expected) in &oracle {
        let (version, discipline, category, number) = key(raw);
        let (short, name, units) = lookup_parameter(
            Originator::new(ECMWF, 0, version),
            discipline,
            category,
            number,
        )
        .unwrap_or_else(|| panic!("{raw} is in the eccodes oracle but does not resolve"));
        assert_eq!(
            format!("{} {} {}", as_eccodes(short), name, as_eccodes(units)),
            *expected,
            "{raw} disagrees with eccodes"
        );
    }
}

/// eccodes resolved every triple the table ships — no entry was emitted that
/// eccodes itself cannot reach from the centre, table version and triple alone.
///
/// This is what makes the skip rule in the generator load-bearing rather than
/// cosmetic: an entry constrained by §4 keys would show up here as `unknown`.
#[test]
fn the_oracle_contains_no_unresolved_entries() {
    let unresolved: Vec<_> = oracle()
        .iter()
        .filter(|(_, v)| v.starts_with("unknown"))
        .map(|(k, _)| k.clone())
        .collect();
    assert!(
        unresolved.is_empty(),
        "eccodes could not resolve {} shipped triples from the triple alone, so the \
         generator emitted entries it should have skipped: {unresolved:?}",
        unresolved.len()
    );
}

/// A spot-check with the values written out, so a reader can see what the
/// table actually contains without decoding a 2,826-entry fixture. These are
/// real ECMWF parameters chosen across three disciplines.
#[test]
fn well_known_ecmwf_parameters_resolve() {
    let ecmwf = Originator::new(ECMWF, 0, 0);
    for (discipline, category, number, expected) in [
        (
            192u8,
            128u8,
            4u8,
            ("eqpt", "Equivalent potential temperature", "K"),
        ),
        (
            192,
            128,
            11,
            ("udvw", "U component of divergent wind", "m s**-1"),
        ),
        (
            192,
            211,
            70,
            ("ch4fdiff", "Methane Surface Fluxes", "kg m**-2 s**-1"),
        ),
        (
            192,
            217,
            71,
            ("cfc11", "Trichlorofluoromethane", "kg kg**-1"),
        ),
        (
            192,
            221,
            4,
            ("dv_ch4", "Methane deposition velocity", "m s**-1"),
        ),
    ] {
        assert_eq!(
            lookup_parameter(ecmwf, discipline, category, number),
            Some(expected),
            "{discipline}/{category}/{number}"
        );
    }
}

/// The 13 entries ECMWF defines only for a revision of its own table resolve
/// under that revision and not otherwise — which is the whole reason the
/// dispatch seam carries `local_tables_version` (#439).
#[test]
fn version_gated_entries_need_their_version() {
    // `lcc` is defined at localTablesVersion 1 only.
    let gated = |version| lookup_parameter(Originator::new(ECMWF, 0, version), 0, 6, 193);
    assert_eq!(gated(1), Some(("lcc", "Low cloud cover", "(0 - 1)")));
    assert_eq!(
        gated(0),
        None,
        "a file declaring no local table version must not pick up a version-1 entry"
    );

    // The gated entries are a real, non-empty set — if a regeneration dropped
    // the gating this test would otherwise pass vacuously.
    let mut gated_count = 0;
    for (raw, _) in oracle() {
        if key(&raw).0 != 0 {
            gated_count += 1;
        }
    }
    assert!(
        gated_count >= 10,
        "only {gated_count} version-gated entries in the oracle"
    );
}

/// Placeholder names are absent by construction. `Experimental product` is 635
/// identical entries with no short name and no units; showing that instead of
/// the numeric triple would be strictly worse for the reader.
#[test]
fn placeholder_names_are_not_shipped() {
    for (raw, line) in oracle() {
        let (_, discipline, category, number) = key(&raw);
        let lowered = line.to_lowercase();
        assert!(
            !lowered.contains("experimental product") && !lowered.contains("reserved"),
            "{discipline}/{category}/{number} ships a placeholder name: {line:?}"
        );
    }
}

/// The table only ever answers for ECMWF, and only inside local code space.
#[test]
fn the_table_is_scoped_to_ecmwf_and_local_codes() {
    // A triple ECMWF defines means nothing coming from another centre.
    assert!(lookup_parameter(Originator::new(ECMWF, 0, 0), 192, 128, 4).is_some());
    for other in [0u16, 7, 34, 78, 173] {
        assert_eq!(
            lookup_parameter(Originator::new(other, 0, 0), 192, 128, 4),
            None,
            "centre {other} must not read ECMWF's table"
        );
    }
    // And the sub-centre does not gate ECMWF's table, which is centre-wide.
    assert_eq!(
        lookup_parameter(Originator::new(ECMWF, 0, 0), 192, 128, 4),
        lookup_parameter(Originator::new(ECMWF, 99, 0), 192, 128, 4),
    );
}
