//! The ECMWF local parameter table, cross-checked against eccodes (#424).
//!
//! `tables_ecmf.rs` is generated by parsing eccodes' concept-file *text*;
//! `fixtures/localconcepts_ecmf.ref.json` is what eccodes' own concept *engine*
//! answers for the same triples. See `local_concepts/mod.rs` for why the two
//! being independent is the whole point, and `dwd_local_parameters.rs` for the
//! same checks against DWD (#425).
//!
//! Regenerate both with
//! `python3 tools/gen_localconcepts_tables.py ecmf --oracle && cargo fmt`.

mod local_concepts;

use fieldglass_grib2::{Originator, lookup_parameter};
use local_concepts::{Oracle, key};

const ORACLE: &str = include_str!("fixtures/localconcepts_ecmf.ref.json");

/// WMO Common Code Table C-11 code for ECMWF.
const ECMWF: u16 = 98;

fn oracle() -> Oracle {
    let oracle = Oracle::load(ORACLE);
    assert_eq!(
        oracle.centre_code, ECMWF,
        "the snapshot was collected for a different centre than this table dispatches on"
    );
    oracle
}

#[test]
fn every_entry_matches_what_eccodes_reports() {
    oracle().assert_every_entry_matches(2_500);
}

#[test]
fn the_oracle_contains_no_unresolved_entries() {
    oracle().assert_nothing_unresolved();
}

#[test]
fn placeholder_names_are_not_shipped() {
    oracle().assert_no_placeholder_names();
}

/// The table only ever answers for ECMWF, and only inside local code space.
#[test]
fn the_table_is_scoped_to_ecmwf_and_local_codes() {
    oracle().assert_scoped_to_its_centre((192, 128, 4), &[0, 7, 34, 78, 173]);
}

/// A spot-check with the values written out, so a reader can see what the
/// table actually contains without decoding a 2,826-entry fixture. These are
/// real ECMWF parameters chosen across three disciplines.
#[test]
fn well_known_ecmwf_parameters_resolve() {
    let ecmwf = Originator::new(ECMWF, 0, 0);
    for (discipline, category, number, expected) in [
        (
            192u8,
            128u8,
            4u8,
            ("eqpt", "Equivalent potential temperature", "K"),
        ),
        (
            192,
            128,
            11,
            ("udvw", "U component of divergent wind", "m s**-1"),
        ),
        (
            192,
            211,
            70,
            ("ch4fdiff", "Methane Surface Fluxes", "kg m**-2 s**-1"),
        ),
        (
            192,
            217,
            71,
            ("cfc11", "Trichlorofluoromethane", "kg kg**-1"),
        ),
        (
            192,
            221,
            4,
            ("dv_ch4", "Methane deposition velocity", "m s**-1"),
        ),
    ] {
        assert_eq!(
            lookup_parameter(ecmwf, discipline, category, number),
            Some(expected),
            "{discipline}/{category}/{number}"
        );
    }
}

/// The 13 entries ECMWF defines only for a revision of its own table resolve
/// under that revision and not otherwise — which is the whole reason the
/// dispatch seam carries `local_tables_version` (#439).
#[test]
fn version_gated_entries_need_their_version() {
    // `lcc` is defined at localTablesVersion 1 only.
    let gated = |version| lookup_parameter(Originator::new(ECMWF, 0, version), 0, 6, 193);
    assert_eq!(gated(1), Some(("lcc", "Low cloud cover", "(0 - 1)")));
    assert_eq!(
        gated(0),
        None,
        "a file declaring no local table version must not pick up a version-1 entry"
    );

    // The gated entries are a real, non-empty set — if a regeneration dropped
    // the gating this test would otherwise pass vacuously.
    let gated_count = oracle()
        .entries
        .keys()
        .filter(|raw| key(raw).0 != 0)
        .count();
    assert!(
        gated_count >= 10,
        "only {gated_count} version-gated entries in the oracle"
    );
}
