#!/usr/bin/env python3
"""Build the GRIB2 §3.150 (HEALPix) fixtures and their coordinate oracles.

eccodes ships no HEALPix sample, so the fixtures are hand-built here: take the
stock GRIB2 sample, switch `gridType` to `healpix`, and set `Nside`, `ordering`
and a ramp of values so each pixel is identifiable by its own number.

**Two oracles, deliberately.** eccodes 2.34.1 is the repo's pin and decodes
HEALPix metadata for both orderings, but its geoiterator refuses NESTED:

    ECCODES ERROR : HEALPix Geoiterator: Only ring ordering is supported

So RING pixel centres come from the pinned CLI, which is the convention, and
NESTED centres come from the newer `eccodes` PyPI wheel, which supports both.
Each `.coords.json` records which produced it. This is the same rule
`NOTICE.md` already applies where the pin predates a fix.

`longitudeOfFirstGridPoint` must be 45000000 (45 deg). The GRIB2 sample carries
0, and 2.34.1 accepts that silently while 2.48 rejects the message outright —
so it is set explicitly rather than left to the sample.

Usage:  python3 tools/build_grib2_healpix_fixtures.py
Needs:  the `eccodes` PyPI wheel (encoding + NESTED oracle) and eccodes 2.34.1
        on PATH (`grib_get_data`, the RING oracle).
"""

from __future__ import annotations

import json
import pathlib
import subprocess
import sys

import eccodes as ec

FIXTURES = pathlib.Path(__file__).resolve().parent.parent / (
    "crates/fieldglass-grib2/tests/fixtures"
)

# Two resolutions, so a test cannot pass by hard-coding one Nside, and both
# orderings. Nside 2 and 4 give 48 and 192 pixels: small enough to commit whole.
CASES = [(2, "ring"), (2, "nested"), (4, "ring"), (4, "nested")]
ORDERING_CODE = {"ring": 0, "nested": 1}

# HEALPix fixes this; see the module docstring.
LON_FIRST_MICRO_DEG = 45_000_000


def write_fixture(nside: int, ordering: str) -> pathlib.Path:
    path = FIXTURES / f"healpix_n{nside}_{ordering}.grib2"
    h = ec.codes_grib_new_from_samples("GRIB2")
    try:
        ec.codes_set(h, "gridType", "healpix")
        ec.codes_set(h, "Nside", nside)
        ec.codes_set(h, "longitudeOfFirstGridPoint", LON_FIRST_MICRO_DEG)
        ec.codes_set(h, "ordering", ORDERING_CODE[ordering])
        # A ramp: pixel k holds k, so a reindexing bug shows up as a value in
        # the wrong place rather than as plausible-looking noise.
        ec.codes_set_values(h, [float(k) for k in range(12 * nside * nside)])
        with path.open("wb") as f:
            ec.codes_write(h, f)
    finally:
        ec.codes_release(h)
    return path


def ring_coords_from_pin(path: pathlib.Path) -> list[list[float]]:
    """Pixel centres from eccodes 2.34.1 `grib_get_data` — the pinned oracle."""
    out = subprocess.run(
        ["grib_get_data", "-L", "%.9f %.9f", str(path)],
        capture_output=True,
        text=True,
        encoding="utf-8",
        check=True,
    ).stdout
    rows = []
    for line in out.strip().splitlines()[1:]:  # skip the header
        lat, lon, _value = line.split()
        rows.append([float(lat), float(lon)])
    return rows


def nested_coords_from_wheel(path: pathlib.Path) -> list[list[float]]:
    """Pixel centres from the newer wheel, which geolocates NESTED."""
    with path.open("rb") as f:
        h = ec.codes_grib_new_from_file(f)
    try:
        it = ec.codes_grib_iterator_new(h, 0)
        rows = []
        while True:
            r = ec.codes_grib_iterator_next(it)
            if not r:
                break
            rows.append([r[0], r[1]])
        ec.codes_grib_iterator_delete(it)
    finally:
        ec.codes_release(h)
    return rows


def pinned_cli_version() -> str:
    out = subprocess.run(
        ["grib_get", "-V"], capture_output=True, text=True, encoding="utf-8"
    )
    return (out.stdout + out.stderr).strip().split()[-1]


def main() -> int:
    cli = pinned_cli_version()
    wheel = ec.codes_get_api_version()
    for nside, ordering in CASES:
        path = write_fixture(nside, ordering)
        if ordering == "ring":
            coords, oracle = ring_coords_from_pin(path), f"eccodes {cli} grib_get_data"
        else:
            coords, oracle = (
                nested_coords_from_wheel(path),
                f"eccodes {wheel} geoiterator (the {cli} pin supports ring only)",
            )
        expected = 12 * nside * nside
        if len(coords) != expected:
            raise SystemExit(f"{path.name}: got {len(coords)} centres, want {expected}")
        (FIXTURES / f"{path.name}.coords.json").write_text(
            json.dumps(
                {
                    "_comment": (
                        "Generated by tools/build_grib2_healpix_fixtures.py. "
                        "Pixel centres in pixel order; do not hand-edit."
                    ),
                    "nside": nside,
                    "ordering": ordering,
                    "oracle": oracle,
                    "coords": coords,
                },
                indent=1,
            )
            + "\n",
            encoding="utf-8",
        )
        print(f"{path.name}: {len(coords)} centres from {oracle}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
