#!/usr/bin/env python3
"""Generate the short-name column for the WMO GRIB2 master parameter table.

Regenerate:

    python3 tools/gen_wmo_short_names.py && cargo fmt

# Why this file exists at all

WMO publishes names and units for Code Table 4.2 but **no short names**, so the
generated master table in `tables_wmo.rs` has only two of the three columns a
reader wants. Measured at `wmo-im/GRIB2` v37: of 1387 master parameters, 1346
showed an empty abbreviation and the 41 that did not were the curated entries
hand-written in `tables.rs`. The abbreviation is the column a forecaster scans,
and it was blank for 97% of standard parameters and full for the local ones,
which is backwards (#469).

The fix is already downloaded. `wgrib2/gribtables/ncep/gribtable.dat` — the file
`gen_ncep_tables.py` reads for the NCEP *local* table at centre 7 — carries
**1230 rows at centre 0**: WMO master triples with NCEP's abbreviations (`TMP`,
`UGRD`, `APCP`), the de facto universal short names for GRIB2 and the ones every
NCO product listing prints. This reads exactly those rows, through the sibling's
parser so there is one pin and one download.

# Why a separate module rather than a column in `tables_wmo.rs`

`tables_wmo.rs` is generated byte-for-byte from a pinned `wmo-im/GRIB2` tag, and
must stay that way: that is what lets a reviewer read its regeneration diff as
"WMO changed" rather than "something moved". Merging a second upstream into it
would destroy that property. So the short name lives in its own module, from its
own pin, and `tables::resolve_parameter` consults it only after the master table
has answered — which means a row here can never invent a parameter, only name
one that WMO already defines.

Measured at v37 / wgrib2 v3.8.0: **every one of the 1230 centre-0 triples is a
triple `tables_wmo.rs` also defines**, so no arm is unreachable. That is not
assumed — `tests/wmo_master_short_names.rs` asserts it exhaustively over all
2^24 triples, along with the resulting counts, so a future bump on either pin
that breaks the containment fails loudly instead of emitting dead arms.

# Precedence against the curated entries, and what measuring it found

The obvious rule — "the hand-curated abbreviation wins" — was checked rather
than adopted. Of the 41 curated triples, **39 already agree** with wgrib2. The
two that disagreed were both wrong, in the way #415 named: a GRIB1 ON388
abbreviation transcribed onto a GRIB2 triple.

| triple | was | is | NCO Code Table 4.2 |
|---|---|---|---|
| 0/1/22 | `CLWMR` | `CLMR` | 4.2-0-1: 22 = Cloud Mixing Ratio, **CLMR**. `CLWMR` is ON388 GRIB1 parameter 153, the same quantity under the older edition's name. |
| 10/0/3 | `WVHGT` | `HTSGW` | 4.2-10-0: 3 = Significant Height of Combined Wind Waves and Swell, **HTSGW**; `WVHGT` is number **5**, Significant Height of Wind Waves — a different parameter. The curated entry paired one parameter's abbreviation with another's name. |

So there is no runtime precedence rule, because after correcting those two there
is nothing to arbitrate: the curated abbreviations and this table agree
everywhere, and the test asserts that agreement over every triple. A future edit
that reintroduces a GRIB1 form on a GRIB2 triple fails the suite rather than
quietly shadowing the generated answer.

# What is dropped, and what is kept despite disagreeing

Ten centre-0 rows carry a wgrib2 *placeholder* rather than an abbreviation:
`var2s31` through `var2s40`, on discipline 3 category 2 (upper and lower layer
cloud optical depth, top pressure, effective radius, and their errors). NCO's
own Code Table 4.2-3-2 publishes **no abbreviation** for those parameters, so
the string is wgrib2 filling a hole in its fixed-width table, not a name anyone
uses. Emitting it would turn a clean blank into a confident, useless label —
the same reason `gen_wmo_grib2_tables.py` drops WMO's reserved rows. They are
filtered, and the filter is asserted rather than assumed: nothing matching the
placeholder shape may reach the generated table.

Three rows are kept even though they disagree with NCO, and are pinned as known
divergences by `tests/wmo_master_short_names.rs`:

| triple | wgrib2 | NCO 4.2-0-6 |
|---|---|---|
| 0/6/17 | `TCONDold` | `TCONDO` |
| 0/6/18 | `TCOLWold` | `TCOLWO` |
| 0/6/19 | `TCOLIold` | `TCOLIO` |

All three are deprecated parameters, and the two tables mark the deprecation
differently — NCO with a trailing `O`, wgrib2 by spelling out `old`. Unlike the
placeholders these name the right parameter and carry real information, so they
ship as wgrib2 writes them rather than being dropped or hand-edited into the
generated file. A fourth appearing is something to look at, not to absorb.

# What stays blank

167 master parameters get no short name here: 157 whose triple wgrib2's table
does not carry, plus the 10 placeholders above. 88 of the 157 are discipline 20
(health and socioeconomic impacts), a discipline WMO added after the snapshot
behind wgrib2's table; the rest are scattered late additions. They resolve to
name and units with an empty abbreviation, exactly as all 1346 did before.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

# The sibling owns the wgrib2 pin, the record parser, and the download, so this
# table can never be generated from a different release than the NCEP one.
sys.path.insert(0, str(Path(__file__).resolve().parent))

from gen_ncep_tables import (  # noqa: E402
    LOCAL_USE,
    SOURCE_URL,
    WGRIB2_TAG,
    fetch_table,
    parse,
    rs,
)

# WMO master entries are written at centre 0 by wgrib2's `get_gribtab.sh`.
MASTER_CENTRE = 0

OUT = Path("crates/fieldglass-grib2/src/tables_wmo_short.rs")

# wgrib2's stand-in for a parameter NCO publishes no abbreviation for. Ten rows
# at v3.8.0, all on discipline 3 category 2; see the module docs.
PLACEHOLDER = re.compile(r"var\d+s\d+")


def master(triple: tuple[int, int, int]) -> bool:
    """Keep only triples the WMO master table can define.

    A component in the local-use range or a 255 is not a master parameter, so a
    row carrying one would be unreachable through `tables_wmo::parameter`.
    wgrib2 v3.8.0 writes no such row at centre 0 — this is a guard against a
    future release that does, not a filter that drops anything today.
    """
    return 255 not in triple and not any(component in LOCAL_USE for component in triple)


def named(entries: dict[tuple[int, int, int], tuple[str, str, str]]) -> dict:
    """Drop the rows whose abbreviation is a placeholder, not a name."""
    return {
        triple: row
        for triple, row in entries.items()
        if row[0].strip() and not PLACEHOLDER.fullmatch(row[0])
    }


def render(entries: dict[tuple[int, int, int], tuple[str, str, str]]) -> str:
    arms = "\n".join(
        f"        ({t[0]}, {t[1]}, {t[2]}) => {rs(entries[t][0])}," for t in sorted(entries)
    )
    return f'''//! Short names for the WMO GRIB2 master parameters — generated, do not edit.
//!
//! Do not edit: regenerate with `python3 tools/gen_wmo_short_names.py`.
//! Source: wgrib2 {WGRIB2_TAG}, the centre-0 rows of
//! `wgrib2/gribtables/ncep/gribtable.dat`, itself produced by wgrib2's
//! `get_gribtab.sh` from the NCO GRIB2 documentation. Both are works of the
//! U.S. federal government and in the public domain.
//!
//! {len(entries)} abbreviations, placeholders dropped. WMO publishes none of
//! its own, so this is the
//! third column of [`crate::tables_wmo`] arriving from a second upstream rather
//! than a column of that table — which is what keeps `tables_wmo.rs`
//! byte-reproducible from its own pinned WMO tag. See the generator's module
//! docs for why these rows and not eccodes', and for the two curated
//! abbreviations measuring this table found to be wrong.

/// The NCEP-style abbreviation for a WMO master parameter, or `None` when
/// wgrib2's table does not carry the triple.
///
/// Consulted by `tables::resolve_parameter` **only after**
/// [`crate::tables_wmo::parameter`] has answered, so this can never name a
/// parameter WMO does not define. `tests/wmo_master_short_names.rs` asserts
/// that containment over every triple.
pub(crate) fn short_name(discipline: u8, category: u8, number: u8) -> Option<&'static str> {{
    Some(match (discipline, category, number) {{
{arms}
        _ => return None,
    }})
}}
'''


def main() -> int:
    rows = parse(fetch_table(), centre=MASTER_CENTRE, keep=master)
    if not rows:
        raise SystemExit(f"{SOURCE_URL}: no rows at centre {MASTER_CENTRE}; the table moved")
    entries = named(rows)
    OUT.write_text(render(entries), encoding="utf-8")
    print(
        f"wgrib2 {WGRIB2_TAG}: {len(entries)} WMO master short names "
        f"({len(rows) - len(entries)} placeholders dropped) -> {OUT}",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
