#!/usr/bin/env python3
"""Generate the colour-name table the CPT parser reads (#236).

A GMT colour palette table may name a colour instead of giving its RGB values
(`F white`, `0 green 1 blue`). GMT's names are the X11 colour database with the
spaces taken out and the case folded, so `ghost white`, `GhostWhite` and
`ghostwhite` are one colour. This writes that database, folded the same way,
to `crates/fieldglass-core/src/color_names.rs` as a sorted slice the parser
binary-searches.

Source: `rgb.txt` from the pinned `rgb-1.1.1` release of X.Org's `app/rgb`
(<https://gitlab.freedesktop.org/xorg/app/rgb>), under the MIT/X11 permission
notice in that repository's `COPYING`. Pinned rather than tracking `master`, so
regenerating is byte-identical and moving to a new tag is a reviewable diff.

Note that X11's `green` is `0/255/0` and its `gray` is `190/190/190`, where CSS
says `0/128/0` and `128/128/128`. GMT follows X11, so this table does too.

Regenerate:

    python3 tools/gen_color_names.py && cargo fmt
"""

from __future__ import annotations

import urllib.request
from pathlib import Path

SOURCE_URL = "https://gitlab.freedesktop.org/xorg/app/rgb/-/raw/rgb-1.1.1/rgb.txt"
OUT = Path(__file__).resolve().parent.parent / "crates" / "fieldglass-core" / "src" / "color_names.rs"


def parse(text: str) -> dict[str, tuple[int, int, int]]:
    """Fold every entry's name to lowercase without spaces, keeping the RGB.

    Two spellings of one colour must agree, or the folding would be choosing
    between them; the pinned file has no such conflict, and this checks that it
    still has none.
    """
    names: dict[str, tuple[int, int, int]] = {}
    for line in text.splitlines():
        if not line.strip() or line.startswith("!"):
            continue
        fields = line.split()
        rgb = (int(fields[0]), int(fields[1]), int(fields[2]))
        name = "".join(fields[3:]).lower()
        assert all(0 <= c <= 255 for c in rgb), line
        assert names.get(name, rgb) == rgb, f"{name}: {names[name]} vs {rgb}"
        names[name] = rgb
    return names


def render(names: dict[str, tuple[int, int, int]]) -> str:
    rows = "\n".join(f'    ("{n}", [{r}, {g}, {b}]),' for n, (r, g, b) in sorted(names.items()))
    return f"""//! X11 colour names for the CPT parser — GENERATED by `tools/gen_color_names.py`.
//!
//! Do not edit by hand: re-run the script instead. Names are folded to
//! lowercase with their spaces removed, which is how GMT reads them, and sorted
//! so a lookup can binary-search.
//!
//! Source: `rgb.txt` from X.Org `app/rgb` release `rgb-1.1.1`, under the MIT/X11
//! permission notice in that repository's `COPYING`.

/// Every colour name a CPT may use, sorted by name.
pub(crate) const COLOR_NAMES: &[(&str, [u8; 3])] = &[
{rows}
];
"""


def main() -> None:
    with urllib.request.urlopen(SOURCE_URL) as response:
        text = response.read().decode("utf-8")
    names = parse(text)
    OUT.write_text(render(names), encoding="utf-8")
    print(f"wrote {OUT.name}: {len(names)} names")


if __name__ == "__main__":
    main()
