//! Named colormaps + RGBA painting for the render pipeline.
//!
//! Mirrors the TS module that used to live at `extension/src/render-helpers.ts`,
//! moved server-side so the render pipeline can ship a paint-ready RGBA
//! buffer across napi rather than a value array that the webview has to
//! re-paint. The webview just blits the returned `Uint8ClampedArray` to a
//! canvas via `putImageData`.
//!
//! A colormap is a short list of RGB anchor stops, interpolated up to a
//! 256-entry lookup table. The tables live in [`crate::colormap_tables`] and are
//! generated by `tools/gen_colormaps.py` — see that file for each colormap's
//! provenance and licence. `viridis` is the default and keeps the exact anchors
//! it had before this registry existed, so its output is unchanged.
//!
//! The legend strip in the webview is drawn from [`Colormap::css_stops`], so the
//! colours in the panel and the colours in the painted grid come from this one
//! source. (They used to be duplicated as a hardcoded CSS `linear-gradient`,
//! which could — and did — drift.)
//!
//! Output format: RGBA bytes (`[r, g, b, a, r, g, b, a, …]`), one byte per
//! channel. Masked / non-finite pixels paint as fully transparent (alpha
//! = 0) so the editor background shows through.

use crate::colormap_tables::COLORMAPS;
use serde::{Deserialize, Serialize};

/// How a colormap is meant to be read: a sequential ramp runs low → high, a
/// diverging one runs from one hue through a neutral midpoint to another and
/// suits anomalies and differences.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ColormapKind {
    Sequential,
    Diverging,
}

impl ColormapKind {
    /// Stable lowercase tag for the napi / UI layer.
    pub fn as_str(&self) -> &'static str {
        match self {
            ColormapKind::Sequential => "sequential",
            ColormapKind::Diverging => "diverging",
        }
    }
}

/// How a value maps onto its `[0, 1]` colormap position: `Linear` spreads the
/// range evenly, `Log10` spreads `log10(value)` evenly so quantities spanning
/// orders of magnitude (precipitation, AOD, chlorophyll) get resolvable colour
/// across their whole range. Under `Log10` a non-positive value has no
/// logarithm and paints as missing (see [`scale_position`]).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ScaleMode {
    #[default]
    Linear,
    Log10,
}

impl ScaleMode {
    /// Stable lowercase tag for the napi / UI layer — the wire value.
    pub fn as_str(&self) -> &'static str {
        match self {
            ScaleMode::Linear => "linear",
            ScaleMode::Log10 => "log10",
        }
    }
}

/// Normalised colormap position in `[0, 1]` for `v` given the display range
/// `[min, max]` and the scaling mode, or `None` when `v` has no place on the
/// ramp and must paint as missing.
///
/// - `Linear`: `(v - min) / (max - min)`, clamped. A degenerate `min == max`
///   (constant field) maps everything to `0.0`, matching the renderer's
///   long-standing behaviour.
/// - `Log10`: `(log10(v) - log10(min)) / (log10(max) - log10(min))`, clamped.
///   `v <= 0` returns `None` (no logarithm → missing). The caller must pass a
///   positive `min`; the napi layer enforces this and errors otherwise, so a
///   non-positive `min` never reaches here in the render pipeline.
///
/// Always returns `None` for a non-finite `v`, in either mode.
pub fn scale_position(v: f64, min: f64, max: f64, scale: ScaleMode) -> Option<f64> {
    let (t0, t1) = transformed_domain(min, max, scale);
    position_in(v, t0, t1, scale)
}

/// The display range in the space the scale interpolates over: `[min, max]`
/// unchanged under [`ScaleMode::Linear`], `log10` of each bound under
/// [`ScaleMode::Log10`]. A [`Palette`] stores the result so the two logarithms
/// are taken once per grid rather than once per pixel.
///
/// A non-positive bound under `Log10` has no logarithm and yields `-inf` (for
/// `0.0`) or `NaN`; that is the same degenerate domain the per-pixel form
/// produced, and [`position_in`] treats it the same way. Callers that care
/// reject a non-positive minimum before they get here.
fn transformed_domain(min: f64, max: f64, scale: ScaleMode) -> (f64, f64) {
    match scale {
        ScaleMode::Linear => (min, max),
        ScaleMode::Log10 => (min.log10(), max.log10()),
    }
}

/// Position of `v` in an already-[`transformed_domain`] `[t0, t1]`, or `None`
/// when `v` has no place on the ramp.
///
/// The one place the normalisation rule is written: [`scale_position`] and
/// [`Palette::normalise`] both route through it, so the CPU painter and a host
/// that reads a `Palette` cannot disagree about where a value sits.
fn position_in(v: f64, t0: f64, t1: f64, scale: ScaleMode) -> Option<f64> {
    if !v.is_finite() {
        return None;
    }
    let tv = match scale {
        ScaleMode::Linear => v,
        ScaleMode::Log10 => {
            // No logarithm for non-positive values — they have no place on a
            // log ramp and paint as missing.
            if v <= 0.0 {
                return None;
            }
            v.log10()
        }
    };
    let span = t1 - t0;
    let t = if span > 0.0 { (tv - t0) / span } else { 0.0 };
    Some(t.clamp(0.0, 1.0))
}

/// One named colormap: a stable `name` (the wire value), a human `label` for
/// the picker, its `kind`, and the RGB anchor stops it interpolates.
#[derive(Debug, Clone, Copy)]
pub struct Colormap {
    pub(crate) name: &'static str,
    pub(crate) label: &'static str,
    pub(crate) kind: ColormapKind,
    pub(crate) anchors: &'static [[f64; 3]],
}

/// The colormap used when a caller names none — the first registry entry, and
/// the one the renderer has always used.
pub fn default_colormap() -> &'static Colormap {
    &COLORMAPS[0]
}

/// Every colormap the renderer offers, in picker order.
pub fn colormaps() -> &'static [Colormap] {
    COLORMAPS
}

impl Colormap {
    /// Look up a colormap by its wire name (`"viridis"`, `"rdbu"`, …).
    /// Unknown names return `None` so the caller can reject them rather than
    /// silently painting the wrong colours.
    pub fn by_name(name: &str) -> Option<&'static Colormap> {
        COLORMAPS.iter().find(|c| c.name == name)
    }

    /// The wire name.
    pub fn name(&self) -> &'static str {
        self.name
    }

    /// The label to show in a picker.
    pub fn label(&self) -> &'static str {
        self.label
    }

    /// Sequential or diverging.
    pub fn kind(&self) -> ColormapKind {
        self.kind
    }

    /// The RGB triple at lookup-table entry `i` (`0..=255`), interpolating
    /// linearly between the two anchors it falls between. The one place the
    /// ramp is actually evaluated — [`lut`](Self::lut) and
    /// [`sample`](Self::sample) both go through it, so they cannot disagree.
    fn entry(&self, i: usize) -> [u8; 3] {
        let segs = (self.anchors.len() - 1) as f64;
        let t = i.min(255) as f64 / 255.0;
        // The final entry sits exactly on the last anchor, which would index one
        // segment past the end; clamp it back onto the last segment's far end.
        let seg = ((t * segs).floor() as usize).min(self.anchors.len() - 2);
        let local_t = t * segs - seg as f64;
        let a = self.anchors[seg];
        let b = self.anchors[seg + 1];
        let mut rgb = [0u8; 3];
        for ch in 0..3 {
            let v = a[ch] + (b[ch] - a[ch]) * local_t;
            rgb[ch] = (v * 255.0).round().clamp(0.0, 255.0) as u8;
        }
        rgb
    }

    /// Build the 256-entry RGB lookup table. `reversed` mirrors the table
    /// end-for-end, which is exactly a reversal of the ramp and cannot
    /// introduce rounding of its own.
    pub fn lut(&self, reversed: bool) -> [u8; 256 * 3] {
        let mut lut = [0u8; 256 * 3];
        for i in 0..256 {
            let rgb = self.entry(i);
            // The destination entry: mirrored when reversed.
            let dst = if reversed { 255 - i } else { i };
            lut[dst * 3..dst * 3 + 3].copy_from_slice(&rgb);
        }
        lut
    }

    /// Look up an RGB triple for a value in `[0, 1]`; out-of-range inputs clamp.
    /// Evaluates the one entry rather than building the whole table, so a
    /// per-sample caller doesn't pay for 256 of them.
    pub fn sample(&self, t: f64, reversed: bool) -> [u8; 3] {
        let i = (t.clamp(0.0, 1.0) * 255.0).round() as usize;
        // Mirror the *index*, matching `lut(true)` exactly: that table puts
        // source entry `255 - i` at position `i`.
        self.entry(if reversed { 255 - i.min(255) } else { i })
    }

    /// `n` evenly spaced `#rrggbb` stops across the ramp, low → high, for the
    /// webview's legend gradient. The single source of truth for the legend
    /// colours: the panel no longer hardcodes them.
    pub fn css_stops(&self, n: usize, reversed: bool) -> Vec<String> {
        let lut = self.lut(reversed);
        (0..n)
            .map(|i| {
                // A single stop degenerates to the low end rather than dividing
                // by zero.
                let t = if n <= 1 {
                    0.0
                } else {
                    i as f64 / (n - 1) as f64
                };
                let idx = (t * 255.0).round() as usize;
                format!(
                    "#{:02x}{:02x}{:02x}",
                    lut[idx * 3],
                    lut[idx * 3 + 1],
                    lut[idx * 3 + 2]
                )
            })
            .collect()
    }
}

/// Look up a viridis RGB triple for a value in `[0, 1]`; out-of-range inputs
/// clamp. Retained as the shorthand for the default colormap.
pub fn viridis(t: f64) -> [u8; 3] {
    default_colormap().sample(t, false)
}

/// Compute `(min, max)` of a numeric grid, ignoring masked entries.
/// Returns `None` when every entry is masked or the grid is empty.
pub fn min_max_ignoring_mask<I: IntoIterator<Item = Option<f64>>>(values: I) -> Option<(f64, f64)> {
    let mut min = f64::INFINITY;
    let mut max = f64::NEG_INFINITY;
    let mut seen = false;
    for v in values {
        let Some(v) = v else { continue };
        if !v.is_finite() {
            continue;
        }
        if v < min {
            min = v;
        }
        if v > max {
            max = v;
        }
        seen = true;
    }
    if seen { Some((min, max)) } else { None }
}

/// Bytes in a [`Palette`] lookup table: 256 entries of RGBA.
pub const PALETTE_LUT_LEN: usize = 256 * 4;

/// Everything colour: the 256-entry RGBA lookup table, the domain values are
/// normalised against, and the pixel a masked cell paints as.
///
/// This is what the painter always built internally, promoted to a type so it
/// can leave the crate as *data*. A GPU host uploads [`lut`](Self::lut) as a
/// 256×1 RGBA texture and applies [`normalise`](Self::normalise)'s two lines in
/// a shader; the CPU painter reads the same struct, so it is the oracle the
/// shader is checked against rather than a second colour implementation
/// (ADR-0006 decision 3).
///
/// [`t0`](Self::t0) and [`t1`](Self::t1) are in the *transformed* domain — the
/// `log10` under [`ScaleMode::Log10`] is taken here, once per grid, not once
/// per value. They are therefore not the caller's display range: read that back
/// from wherever the range came from, not from a `Palette`.
///
/// Construct one with [`build`](Self::build); the struct is `#[non_exhaustive]`
/// so fields can be added without breaking a host.
///
/// A JSON round trip is bit-exact only where `serde_json` is built with its
/// `float_roundtrip` feature — the default parser is not correctly rounded and
/// reads [`t0`](Self::t0)/[`t1`](Self::t1) back up to one ULP away. This
/// workspace enables it; a downstream crate that serialises a `Palette` should
/// too.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct Palette {
    /// 256 RGBA entries, low → high, already mirrored when the caller asked for
    /// a reversed ramp. Every entry is opaque; transparency is
    /// [`masked_rgba`](Self::masked_rgba)'s job, not the table's.
    #[serde(with = "lut_bytes")]
    pub lut: [u8; PALETTE_LUT_LEN],
    /// Low end of the transformed domain.
    pub t0: f64,
    /// High end of the transformed domain.
    pub t1: f64,
    /// Which transform [`t0`](Self::t0)/[`t1`](Self::t1) are expressed in, and
    /// the one a value must be put through before it can be placed between
    /// them.
    pub scale: ScaleMode,
    /// The pixel a masked, non-finite, or (under `Log10`) non-positive cell
    /// paints as. Fully transparent, so the editor background shows through.
    pub masked_rgba: [u8; 4],
}

impl Palette {
    /// Build the table and domain for one grid: evaluate `colormap`'s ramp into
    /// 256 RGBA entries (mirrored when `reversed`) and transform the display
    /// range `[min, max]` once.
    ///
    /// `min`/`max` are always the true, unlogged display range, so a caller's
    /// colorbar labels stay in data units.
    pub fn build(
        colormap: &Colormap,
        reversed: bool,
        min: f64,
        max: f64,
        scale: ScaleMode,
    ) -> Self {
        // The ramp is evaluated in exactly one place — `Colormap::entry`, via
        // `lut` — and widened to RGBA here. `css_stops` and `sample` read that
        // same table, so the legend, a point sample, and the painted grid
        // cannot drift apart.
        let rgb = colormap.lut(reversed);
        let mut lut = [0u8; PALETTE_LUT_LEN];
        for i in 0..256 {
            lut[i * 4..i * 4 + 3].copy_from_slice(&rgb[i * 3..i * 3 + 3]);
            lut[i * 4 + 3] = 255;
        }
        let (t0, t1) = transformed_domain(min, max, scale);
        Self {
            lut,
            t0,
            t1,
            scale,
            masked_rgba: [0, 0, 0, 0],
        }
    }

    /// Where `v` sits on the ramp, in `[0, 1]`, or `None` when it has no place
    /// there (non-finite, or non-positive under `Log10`).
    ///
    /// `f32` because this is the shader-facing form. The arithmetic still
    /// happens in `f64` here and only the result is narrowed, so the answer is
    /// within one lookup-table entry of [`index`](Self::index) — for uniformly
    /// distributed positions about six in a million land on the other side of
    /// the rounding boundary, and never more than one entry away.
    /// `palette_golden.rs` pins that bound. Use `index` when you need the exact
    /// byte the CPU painter would emit.
    ///
    /// **That bound does not survive being moved into a shader.** A GPU that
    /// subtracts and divides in `f32` loses the domain, not just the result:
    /// once the `f32` gap at [`t0`](Self::t0) grows past one lookup step —
    /// roughly `t1 - t0 < 255 * t0.abs() * 2f64.powi(-23)` — the error is
    /// unbounded within the ramp. Measured at up to 127 entries, half the
    /// table, for a manual range of 1.0 over values near `1e7`; geopotential in
    /// m²/s², pressure in Pa, and radiances all reach that regime under a tight
    /// manual range. `t0`/`t1` are `f64` for this reason. A shader must be
    /// handed a rebased domain — upload `v - t0`, so the cancellation happens
    /// here in `f64` — rather than the raw values and the raw bounds.
    pub fn normalise(&self, v: f64) -> Option<f32> {
        self.position(v).map(|t| t as f32)
    }

    /// [`normalise`](Self::normalise) in the painter's own precision.
    fn position(&self, v: f64) -> Option<f64> {
        position_in(v, self.t0, self.t1, self.scale)
    }

    /// The lookup-table entry `v` paints from, or `None` when it has no colour.
    pub fn index(&self, v: f64) -> Option<u8> {
        // `t` is clamped to `[0, 1]`, so the product lands in `[0, 255]` and the
        // saturating float→int cast never truncates. A `NaN` `t` — reachable
        // only from a degenerate `log10` domain — casts to 0, which is the
        // entry the painter has always given it.
        self.position(v).map(|t| (t * 255.0).round() as u8)
    }

    /// The RGBA pixel for one value: its table entry, or
    /// [`masked_rgba`](Self::masked_rgba) when it has no colour.
    pub fn rgba(&self, v: f64) -> [u8; 4] {
        match self.index(v) {
            Some(i) => {
                let o = i as usize * 4;
                [
                    self.lut[o],
                    self.lut[o + 1],
                    self.lut[o + 2],
                    self.lut[o + 3],
                ]
            }
            None => self.masked_rgba,
        }
    }

    /// Paint a row-major grid into an RGBA byte buffer suitable for
    /// `ImageData`. Each pixel is 4 bytes (`r, g, b, a`); a cell that is masked
    /// (`mask[i] == 0`), non-finite, or non-positive under `Log10` paints as
    /// [`masked_rgba`](Self::masked_rgba).
    ///
    /// Output length is `width * height * 4`. When `flip_y` is true, rows are
    /// emitted bottom-to-top — useful when the source grid scans south-to-north
    /// but the canvas wants north-up.
    pub fn paint(
        &self,
        values: &[f64],
        mask: Option<&[u8]>,
        width: u32,
        height: u32,
        flip_y: bool,
    ) -> Vec<u8> {
        // `usize` is 32 bits on wasm32 — the host this type exists for — and
        // both dimensions can be a `u32` read straight out of a file's grid
        // description. Size the buffer in `u64` and refuse one this target
        // cannot address, rather than wrap into a short buffer and index off
        // the end of it.
        let Some(total) = u64::from(width)
            .checked_mul(u64::from(height))
            .and_then(|px| px.checked_mul(4))
            .and_then(|bytes| usize::try_from(bytes).ok())
            .map(|bytes| bytes / 4)
        else {
            return Vec::new();
        };
        if total == 0 {
            return Vec::new();
        }
        let w = width as usize;
        let h = height as usize;
        debug_assert_eq!(
            values.len(),
            total,
            "Palette::paint: values.len()={} != width*height={total}; trailing pixels would silently render as transparent",
            values.len(),
        );
        if let Some(m) = mask {
            debug_assert_eq!(
                m.len(),
                total,
                "Palette::paint: mask.len()={} != width*height={total}",
                m.len(),
            );
        }
        let mut out = vec![0u8; total * 4];

        for (i, &v) in values.iter().enumerate().take(total) {
            let row = i / w;
            let col = i - row * w;
            let out_idx = if flip_y { (h - 1 - row) * w + col } else { i };
            let o = out_idx * 4;

            let masked = mask.is_some_and(|m| m.get(i).copied().unwrap_or(0) == 0);
            let px = if masked {
                self.masked_rgba
            } else {
                self.rgba(v)
            };
            out[o..o + 4].copy_from_slice(&px);
        }
        out
    }
}

/// `[u8; 1024]` is past the 32-element ceiling serde derives array impls up to,
/// so the table serialises as a byte string (or a number sequence, in a
/// self-describing format like JSON) and reads back from either.
mod lut_bytes {
    use super::PALETTE_LUT_LEN;
    use serde::de::{Error as DeError, SeqAccess, Visitor};
    use serde::{Deserializer, Serializer};
    use std::fmt;

    pub fn serialize<S: Serializer>(
        lut: &[u8; PALETTE_LUT_LEN],
        serializer: S,
    ) -> Result<S::Ok, S::Error> {
        serializer.serialize_bytes(lut)
    }

    pub fn deserialize<'de, D: Deserializer<'de>>(
        deserializer: D,
    ) -> Result<[u8; PALETTE_LUT_LEN], D::Error> {
        struct LutVisitor;

        impl<'de> Visitor<'de> for LutVisitor {
            type Value = [u8; PALETTE_LUT_LEN];

            fn expecting(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                write!(f, "{PALETTE_LUT_LEN} colormap lookup-table bytes")
            }

            fn visit_bytes<E: DeError>(self, v: &[u8]) -> Result<Self::Value, E> {
                v.try_into().map_err(|_| E::invalid_length(v.len(), &self))
            }

            fn visit_seq<A: SeqAccess<'de>>(self, mut seq: A) -> Result<Self::Value, A::Error> {
                let mut lut = [0u8; PALETTE_LUT_LEN];
                for (i, slot) in lut.iter_mut().enumerate() {
                    *slot = seq
                        .next_element()?
                        .ok_or_else(|| A::Error::invalid_length(i, &self))?;
                }
                // A longer table is malformed, not a table with a tail to
                // ignore: silently truncating it would hand back colours the
                // sender did not mean.
                if seq.next_element::<u8>()?.is_some() {
                    return Err(A::Error::invalid_length(PALETTE_LUT_LEN + 1, &self));
                }
                Ok(lut)
            }
        }

        deserializer.deserialize_bytes(LutVisitor)
    }
}

/// Paint a row-major grid into an RGBA byte buffer suitable for
/// `ImageData`, colouring it with `colormap` (mirrored when `reversed`).
/// Each pixel is 4 bytes (`r, g, b, a`); masked or non-finite values render
/// as fully transparent (alpha = 0). When `min == max` (a constant field)
/// every present cell paints at LUT index 0.
///
/// `scale` selects linear or log10 value→colour mapping (see
/// [`scale_position`]); under [`ScaleMode::Log10`] a non-positive value has no
/// logarithm and paints transparent, exactly like a masked cell. `min`/`max`
/// are always the true (unlogged) display range, so the caller's colorbar
/// labels stay in data units.
///
/// Output length is `width * height * 4`. When `flip_y` is true, rows
/// are emitted bottom-to-top — useful when the source grid scans
/// south-to-north but the canvas wants north-up.
///
/// A thin wrapper over [`Palette::build`] + [`Palette::paint`], kept because
/// most callers paint one grid once and never need the table back. Reach for
/// `Palette` directly when the table itself is the point — a GPU upload, or a
/// restyle that must not re-decode.
#[allow(clippy::too_many_arguments)]
pub fn paint_grid_rgba(
    values: &[f64],
    mask: Option<&[u8]>,
    width: u32,
    height: u32,
    min: f64,
    max: f64,
    flip_y: bool,
    colormap: &Colormap,
    reversed: bool,
    scale: ScaleMode,
) -> Vec<u8> {
    Palette::build(colormap, reversed, min, max, scale).paint(values, mask, width, height, flip_y)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The exact viridis LUT the renderer produced before the colormap registry
    /// existed: 11 anchors, linearly interpolated to 256 entries. Reproduced
    /// here from the pre-registry implementation so the default colormap's
    /// output is pinned against *this* code, not against itself.
    fn legacy_viridis_lut() -> [u8; 256 * 3] {
        const ANCHORS: [[f64; 3]; 11] = [
            [0.267004, 0.004874, 0.329415],
            [0.282623, 0.140926, 0.457517],
            [0.253935, 0.265254, 0.529983],
            [0.206756, 0.371758, 0.553117],
            [0.163625, 0.471133, 0.558148],
            [0.127568, 0.566949, 0.550556],
            [0.134692, 0.658636, 0.517649],
            [0.266941, 0.748751, 0.440573],
            [0.477504, 0.821444, 0.318195],
            [0.741388, 0.873449, 0.149561],
            [0.993248, 0.906157, 0.143936],
        ];
        let mut lut = [0u8; 256 * 3];
        let segs = (ANCHORS.len() - 1) as f64;
        for i in 0..256 {
            let t = i as f64 / 255.0;
            let mut seg = (t * segs).floor() as usize;
            if seg >= ANCHORS.len() - 1 {
                seg = ANCHORS.len() - 2;
            }
            let local_t = t * segs - seg as f64;
            let a = ANCHORS[seg];
            let b = ANCHORS[seg + 1];
            let r = a[0] + (b[0] - a[0]) * local_t;
            let g = a[1] + (b[1] - a[1]) * local_t;
            let bl = a[2] + (b[2] - a[2]) * local_t;
            lut[i * 3] = (r * 255.0).round().clamp(0.0, 255.0) as u8;
            lut[i * 3 + 1] = (g * 255.0).round().clamp(0.0, 255.0) as u8;
            lut[i * 3 + 2] = (bl * 255.0).round().clamp(0.0, 255.0) as u8;
        }
        lut
    }

    #[test]
    fn default_colormap_is_byte_identical_to_the_pre_registry_viridis() {
        // The registry must not have changed a single pixel of the default
        // render. Any drift in the generated anchors or the LUT builder shows
        // up here.
        assert_eq!(default_colormap().name(), "viridis");
        assert_eq!(
            default_colormap().lut(false).as_slice(),
            legacy_viridis_lut().as_slice()
        );
    }

    #[test]
    fn viridis_lut_has_canonical_endpoints() {
        let lut = default_colormap().lut(false);
        // First entry is canonical viridis dark-purple, last is
        // bright-yellow. Loose bounds — anchor stops + linear interp.
        assert!(lut[0] < 100 && lut[1] < 50 && lut[2] > 50, "viridis[0]");
        assert!(
            lut[765] > 200 && lut[766] > 200 && lut[767] < 80,
            "viridis[255]"
        );
    }

    #[test]
    fn viridis_function_clamps_out_of_range() {
        let lo = viridis(-5.0);
        let hi = viridis(5.0);
        let lut = default_colormap().lut(false);
        assert_eq!(lo, [lut[0], lut[1], lut[2]]);
        assert_eq!(hi, [lut[765], lut[766], lut[767]]);
    }

    #[test]
    fn every_registered_colormap_is_usable_and_distinct() {
        let all = colormaps();
        assert!(
            all.len() >= 8,
            "expected the full registry, got {}",
            all.len()
        );
        for c in all {
            // Name/label are populated and the name round-trips through lookup.
            assert!(!c.name().is_empty() && !c.label().is_empty());
            assert_eq!(
                Colormap::by_name(c.name()).map(|f| f.name()),
                Some(c.name())
            );
            // A colormap needs at least two anchors to interpolate between.
            assert!(c.anchors.len() >= 2, "{} has too few anchors", c.name());
            // The ramp must actually go somewhere: ends differ.
            let lut = c.lut(false);
            assert_ne!(
                &lut[0..3],
                &lut[765..768],
                "{} has identical endpoints",
                c.name()
            );
        }
        // Every map paints a *different* ramp — a copy-paste slip in the
        // generated table would otherwise go unnoticed.
        for (i, a) in all.iter().enumerate() {
            for b in &all[i + 1..] {
                assert_ne!(
                    a.lut(false).as_slice(),
                    b.lut(false).as_slice(),
                    "{} and {} produce the same ramp",
                    a.name(),
                    b.name()
                );
            }
        }
    }

    #[test]
    fn reversing_mirrors_the_ramp_exactly() {
        for c in colormaps() {
            let fwd = c.lut(false);
            let rev = c.lut(true);
            for i in 0..256 {
                let j = 255 - i;
                assert_eq!(
                    &fwd[i * 3..i * 3 + 3],
                    &rev[j * 3..j * 3 + 3],
                    "{} reversed entry {i}",
                    c.name()
                );
            }
        }
    }

    #[test]
    fn sample_agrees_with_the_lut_it_replaces() {
        // `sample` evaluates one entry instead of building the whole table; it
        // must still land on exactly the entry the table would have held, in
        // both directions, or a one-off lookup would disagree with the render.
        for c in colormaps() {
            for reversed in [false, true] {
                let lut = c.lut(reversed);
                for i in 0..256 {
                    let t = i as f64 / 255.0;
                    assert_eq!(
                        c.sample(t, reversed),
                        [lut[i * 3], lut[i * 3 + 1], lut[i * 3 + 2]],
                        "{} entry {i} (reversed={reversed})",
                        c.name()
                    );
                }
            }
            // Out-of-range inputs clamp to the ends rather than panicking.
            assert_eq!(c.sample(-1.0, false), c.sample(0.0, false));
            assert_eq!(c.sample(2.0, false), c.sample(1.0, false));
        }
    }

    #[test]
    fn unknown_colormap_name_is_rejected() {
        assert!(Colormap::by_name("jet").is_none());
        assert!(Colormap::by_name("").is_none());
        assert!(Colormap::by_name("Viridis").is_none(), "names are exact");
    }

    #[test]
    fn grayscale_is_a_neutral_ramp() {
        // A property the data must satisfy: every grayscale entry has r == g == b
        // and the ramp climbs from black to white.
        let gs = Colormap::by_name("grayscale").expect("grayscale is registered");
        let lut = gs.lut(false);
        for i in 0..256 {
            let (r, g, b) = (lut[i * 3], lut[i * 3 + 1], lut[i * 3 + 2]);
            assert!(r == g && g == b, "grayscale entry {i} is not neutral");
        }
        assert_eq!(&lut[0..3], &[0, 0, 0]);
        assert_eq!(&lut[765..768], &[255, 255, 255]);
    }

    #[test]
    fn diverging_maps_are_light_in_the_middle_and_saturated_at_the_ends() {
        // What makes a diverging map diverging: a near-neutral midpoint with
        // two distinct, saturated ends. Pins the kind tag against the data.
        for c in colormaps()
            .iter()
            .filter(|c| c.kind() == ColormapKind::Diverging)
        {
            let lut = c.lut(false);
            let spread = |i: usize| {
                let (r, g, b) = (
                    lut[i * 3] as i32,
                    lut[i * 3 + 1] as i32,
                    lut[i * 3 + 2] as i32,
                );
                r.max(g).max(b) - r.min(g).min(b)
            };
            let mid = spread(128);
            assert!(
                mid < 40,
                "{} midpoint should be near-neutral, channel spread {mid}",
                c.name()
            );
            assert!(
                spread(0) > mid && spread(255) > mid,
                "{} ends should be more saturated than its midpoint",
                c.name()
            );
        }
    }

    #[test]
    fn css_stops_are_sampled_from_the_lut_that_paints_the_grid() {
        // The legend's whole job is to show the ramp the image was painted
        // with, so every stop must come from that exact LUT.
        let c = Colormap::by_name("plasma").expect("registered");
        for reversed in [false, true] {
            let stops = c.css_stops(33, reversed);
            let lut = c.lut(reversed);
            assert_eq!(stops.len(), 33);
            for (i, stop) in stops.iter().enumerate() {
                let idx = (i as f64 / 32.0 * 255.0).round() as usize;
                assert_eq!(
                    stop,
                    &format!(
                        "#{:02x}{:02x}{:02x}",
                        lut[idx * 3],
                        lut[idx * 3 + 1],
                        lut[idx * 3 + 2]
                    ),
                    "stop {i} (reversed={reversed})"
                );
            }
        }
        // Reversing swaps the ends of the legend, which is what the user sees.
        let fwd = c.css_stops(33, false);
        let rev = c.css_stops(33, true);
        assert_eq!(rev[0], fwd[32]);
        assert_eq!(rev[32], fwd[0]);
        // A degenerate request must not divide by zero.
        assert_eq!(c.css_stops(1, false).len(), 1);
    }

    #[test]
    fn min_max_skips_nulls_and_nonfinite() {
        let it = vec![
            None,
            Some(1.0),
            Some(2.0),
            None,
            Some(3.0),
            Some(f64::NAN),
            Some(-1.0),
        ];
        let out = min_max_ignoring_mask(it).expect("some present");
        assert_eq!(out.0, -1.0);
        assert_eq!(out.1, 3.0);
    }

    #[test]
    fn min_max_returns_none_when_all_masked() {
        let it: Vec<Option<f64>> = vec![None, None];
        assert!(min_max_ignoring_mask(it).is_none());
    }

    #[test]
    fn paint_grid_rgba_emits_transparent_for_masked() {
        let values = vec![10.0, 20.0, 30.0, 40.0];
        let mask = vec![1u8, 0, 1, 1];
        let out = paint_grid_rgba(
            &values,
            Some(&mask),
            2,
            2,
            10.0,
            40.0,
            false,
            default_colormap(),
            false,
            ScaleMode::Linear,
        );
        assert_eq!(out.len(), 16);
        // Pixel 1 is masked → fully transparent.
        assert_eq!(&out[4..8], &[0, 0, 0, 0]);
        // Pixel 0 should be the LUT[0] viridis color with alpha 255.
        assert_eq!(out[3], 255);
    }

    #[test]
    fn paint_grid_rgba_honours_the_chosen_colormap_and_reverse() {
        let values = vec![0.0, 1.0];
        let paint = |name: &str, reversed: bool| {
            let c = Colormap::by_name(name).expect("registered");
            paint_grid_rgba(
                &values,
                None,
                2,
                1,
                0.0,
                1.0,
                false,
                c,
                reversed,
                ScaleMode::Linear,
            )
        };
        let viridis = paint("viridis", false);
        let turbo = paint("turbo", false);
        assert_ne!(
            viridis, turbo,
            "a different colormap must paint differently"
        );

        // Reversed viridis paints the low cell with what the forward map paints
        // the high cell, and vice versa.
        let reversed = paint("viridis", true);
        assert_eq!(&reversed[0..3], &viridis[4..7]);
        assert_eq!(&reversed[4..7], &viridis[0..3]);
    }

    #[test]
    fn paint_grid_rgba_returns_empty_for_zero_dims() {
        let out = paint_grid_rgba(
            &[],
            None,
            0,
            10,
            0.0,
            1.0,
            false,
            default_colormap(),
            false,
            ScaleMode::Linear,
        );
        assert!(out.is_empty());
        let out = paint_grid_rgba(
            &[],
            None,
            10,
            0,
            0.0,
            1.0,
            false,
            default_colormap(),
            false,
            ScaleMode::Linear,
        );
        assert!(out.is_empty());
    }

    #[test]
    fn paint_grid_rgba_flip_y_inverts_rows() {
        let values = vec![1.0, 2.0, 3.0, 4.0];
        let unflipped = paint_grid_rgba(
            &values,
            None,
            2,
            2,
            1.0,
            4.0,
            false,
            default_colormap(),
            false,
            ScaleMode::Linear,
        );
        let flipped = paint_grid_rgba(
            &values,
            None,
            2,
            2,
            1.0,
            4.0,
            true,
            default_colormap(),
            false,
            ScaleMode::Linear,
        );
        // Top-left of flipped == row 1, col 0 of unflipped (= source pixel 2).
        // We can verify by checking that the bytes differ as expected.
        assert_ne!(unflipped, flipped);
        // Verify symmetry: flipping twice returns the original layout.
        // (Re-paint flipped values from `unflipped`-derived row-order.)
        // Simpler check: the alpha byte of the top-left flipped pixel is
        // still 255 (it's a present cell).
        assert_eq!(flipped[3], 255);
    }

    #[test]
    fn scale_position_linear_matches_the_old_formula() {
        // Linear must be byte-for-byte the mapping the renderer always used:
        // evenly spaced, clamped, constant field → 0.0, non-finite → None.
        assert_eq!(scale_position(0.0, 0.0, 10.0, ScaleMode::Linear), Some(0.0));
        assert_eq!(scale_position(5.0, 0.0, 10.0, ScaleMode::Linear), Some(0.5));
        assert_eq!(
            scale_position(10.0, 0.0, 10.0, ScaleMode::Linear),
            Some(1.0)
        );
        // Out of range clamps to the ends.
        assert_eq!(
            scale_position(-3.0, 0.0, 10.0, ScaleMode::Linear),
            Some(0.0)
        );
        assert_eq!(
            scale_position(99.0, 0.0, 10.0, ScaleMode::Linear),
            Some(1.0)
        );
        // Degenerate range → low end, never a divide-by-zero.
        assert_eq!(scale_position(7.0, 7.0, 7.0, ScaleMode::Linear), Some(0.0));
        // Non-finite has no place on the ramp.
        assert_eq!(scale_position(f64::NAN, 0.0, 10.0, ScaleMode::Linear), None);
    }

    #[test]
    fn scale_position_log10_spreads_decades_evenly() {
        // Over [1, 100] the midpoint in log space is 10 (one decade up), not 50.
        assert_eq!(scale_position(1.0, 1.0, 100.0, ScaleMode::Log10), Some(0.0));
        assert_eq!(
            scale_position(10.0, 1.0, 100.0, ScaleMode::Log10),
            Some(0.5)
        );
        assert_eq!(
            scale_position(100.0, 1.0, 100.0, ScaleMode::Log10),
            Some(1.0)
        );
        // A positive value below/above the range clamps, it does not vanish.
        assert_eq!(scale_position(0.1, 1.0, 100.0, ScaleMode::Log10), Some(0.0));
        assert_eq!(
            scale_position(1000.0, 1.0, 100.0, ScaleMode::Log10),
            Some(1.0)
        );
    }

    #[test]
    fn scale_position_log10_drops_non_positive_and_non_finite() {
        // No logarithm for zero or negatives → missing.
        assert_eq!(scale_position(0.0, 1.0, 100.0, ScaleMode::Log10), None);
        assert_eq!(scale_position(-5.0, 1.0, 100.0, ScaleMode::Log10), None);
        assert_eq!(scale_position(f64::NAN, 1.0, 100.0, ScaleMode::Log10), None);
        // Degenerate log range (min == max) → low end, no divide-by-zero.
        assert_eq!(scale_position(4.0, 4.0, 4.0, ScaleMode::Log10), Some(0.0));
    }

    #[test]
    fn paint_grid_rgba_log10_paints_known_indices() {
        // A row of exact decades over [1, 100] lands on LUT entries 0, 128, 255
        // under log10 — the acceptance case: known grid → expected colours.
        let values = vec![1.0, 10.0, 100.0];
        let out = paint_grid_rgba(
            &values,
            None,
            3,
            1,
            1.0,
            100.0,
            false,
            default_colormap(),
            false,
            ScaleMode::Log10,
        );
        let lut = default_colormap().lut(false);
        let expect = |idx: usize| [lut[idx * 3], lut[idx * 3 + 1], lut[idx * 3 + 2], 255];
        assert_eq!(&out[0..4], &expect(0));
        assert_eq!(&out[4..8], &expect(128));
        assert_eq!(&out[8..12], &expect(255));

        // The same grid under linear does *not* put 10 at the midpoint — proving
        // the mode actually changes the mapping rather than being a no-op.
        let linear = paint_grid_rgba(
            &values,
            None,
            3,
            1,
            1.0,
            100.0,
            false,
            default_colormap(),
            false,
            ScaleMode::Linear,
        );
        assert_ne!(&linear[4..8], &out[4..8], "10 maps differently under log10");
    }

    #[test]
    fn paint_grid_rgba_log10_paints_non_positive_transparent() {
        // Zero and negative cells have no logarithm and must paint fully
        // transparent, exactly like a masked cell — positives still colour.
        let values = vec![0.0, -3.0, 10.0];
        let out = paint_grid_rgba(
            &values,
            None,
            3,
            1,
            1.0,
            100.0,
            false,
            default_colormap(),
            false,
            ScaleMode::Log10,
        );
        assert_eq!(&out[0..4], &[0, 0, 0, 0], "zero → transparent");
        assert_eq!(&out[4..8], &[0, 0, 0, 0], "negative → transparent");
        assert_eq!(out[11], 255, "the positive cell is still painted");
    }

    #[test]
    fn scale_mode_wire_tags_round_trip() {
        assert_eq!(ScaleMode::Linear.as_str(), "linear");
        assert_eq!(ScaleMode::Log10.as_str(), "log10");
        assert_eq!(ScaleMode::default(), ScaleMode::Linear);
    }
}
