//! Named colormaps + RGBA painting for the render pipeline.
//!
//! Mirrors the TS module that used to live at `extension/src/render-helpers.ts`,
//! moved server-side so the render pipeline can ship a paint-ready RGBA
//! buffer across napi rather than a value array that the webview has to
//! re-paint. The webview just blits the returned `Uint8ClampedArray` to a
//! canvas via `putImageData`.
//!
//! A colormap is a short list of RGB anchor stops, interpolated up to a
//! 256-entry lookup table. The tables live in [`crate::colormap_tables`] and are
//! generated by `tools/gen_colormaps.py` — see that file for each colormap's
//! provenance and licence. `viridis` is the default and keeps the exact anchors
//! it had before this registry existed, so its output is unchanged.
//!
//! The legend strip in the webview is drawn from [`Colormap::css_stops`], so the
//! colours in the panel and the colours in the painted grid come from this one
//! source. (They used to be duplicated as a hardcoded CSS `linear-gradient`,
//! which could — and did — drift.)
//!
//! Output format: RGBA bytes (`[r, g, b, a, r, g, b, a, …]`), one byte per
//! channel. Masked / non-finite pixels paint as fully transparent (alpha
//! = 0) so the editor background shows through.

use crate::colormap_tables::COLORMAPS;

/// How a colormap is meant to be read: a sequential ramp runs low → high, a
/// diverging one runs from one hue through a neutral midpoint to another and
/// suits anomalies and differences.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ColormapKind {
    Sequential,
    Diverging,
}

impl ColormapKind {
    /// Stable lowercase tag for the napi / UI layer.
    pub fn as_str(&self) -> &'static str {
        match self {
            ColormapKind::Sequential => "sequential",
            ColormapKind::Diverging => "diverging",
        }
    }
}

/// How a value maps onto its `[0, 1]` colormap position: `Linear` spreads the
/// range evenly, `Log10` spreads `log10(value)` evenly so quantities spanning
/// orders of magnitude (precipitation, AOD, chlorophyll) get resolvable colour
/// across their whole range. Under `Log10` a non-positive value has no
/// logarithm and paints as missing (see [`scale_position`]).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum ScaleMode {
    #[default]
    Linear,
    Log10,
}

impl ScaleMode {
    /// Stable lowercase tag for the napi / UI layer — the wire value.
    pub fn as_str(&self) -> &'static str {
        match self {
            ScaleMode::Linear => "linear",
            ScaleMode::Log10 => "log10",
        }
    }
}

/// Normalised colormap position in `[0, 1]` for `v` given the display range
/// `[min, max]` and the scaling mode, or `None` when `v` has no place on the
/// ramp and must paint as missing.
///
/// - `Linear`: `(v - min) / (max - min)`, clamped. A degenerate `min == max`
///   (constant field) maps everything to `0.0`, matching the renderer's
///   long-standing behaviour.
/// - `Log10`: `(log10(v) - log10(min)) / (log10(max) - log10(min))`, clamped.
///   `v <= 0` returns `None` (no logarithm → missing). The caller must pass a
///   positive `min`; the napi layer enforces this and errors otherwise, so a
///   non-positive `min` never reaches here in the render pipeline.
///
/// Always returns `None` for a non-finite `v`, in either mode.
pub fn scale_position(v: f64, min: f64, max: f64, scale: ScaleMode) -> Option<f64> {
    if !v.is_finite() {
        return None;
    }
    match scale {
        ScaleMode::Linear => {
            let span = max - min;
            let t = if span > 0.0 { (v - min) / span } else { 0.0 };
            Some(t.clamp(0.0, 1.0))
        }
        ScaleMode::Log10 => {
            // No logarithm for non-positive values — they have no place on a
            // log ramp and paint as missing.
            if v <= 0.0 {
                return None;
            }
            let (lmin, lmax, lv) = (min.log10(), max.log10(), v.log10());
            let span = lmax - lmin;
            let t = if span > 0.0 { (lv - lmin) / span } else { 0.0 };
            Some(t.clamp(0.0, 1.0))
        }
    }
}

/// One named colormap: a stable `name` (the wire value), a human `label` for
/// the picker, its `kind`, and the RGB anchor stops it interpolates.
#[derive(Debug, Clone, Copy)]
pub struct Colormap {
    pub(crate) name: &'static str,
    pub(crate) label: &'static str,
    pub(crate) kind: ColormapKind,
    pub(crate) anchors: &'static [[f64; 3]],
}

/// The colormap used when a caller names none — the first registry entry, and
/// the one the renderer has always used.
pub fn default_colormap() -> &'static Colormap {
    &COLORMAPS[0]
}

/// Every colormap the renderer offers, in picker order.
pub fn colormaps() -> &'static [Colormap] {
    COLORMAPS
}

impl Colormap {
    /// Look up a colormap by its wire name (`"viridis"`, `"rdbu"`, …).
    /// Unknown names return `None` so the caller can reject them rather than
    /// silently painting the wrong colours.
    pub fn by_name(name: &str) -> Option<&'static Colormap> {
        COLORMAPS.iter().find(|c| c.name == name)
    }

    /// The wire name.
    pub fn name(&self) -> &'static str {
        self.name
    }

    /// The label to show in a picker.
    pub fn label(&self) -> &'static str {
        self.label
    }

    /// Sequential or diverging.
    pub fn kind(&self) -> ColormapKind {
        self.kind
    }

    /// The RGB triple at lookup-table entry `i` (`0..=255`), interpolating
    /// linearly between the two anchors it falls between. The one place the
    /// ramp is actually evaluated — [`lut`](Self::lut) and
    /// [`sample`](Self::sample) both go through it, so they cannot disagree.
    fn entry(&self, i: usize) -> [u8; 3] {
        let segs = (self.anchors.len() - 1) as f64;
        let t = i.min(255) as f64 / 255.0;
        // The final entry sits exactly on the last anchor, which would index one
        // segment past the end; clamp it back onto the last segment's far end.
        let seg = ((t * segs).floor() as usize).min(self.anchors.len() - 2);
        let local_t = t * segs - seg as f64;
        let a = self.anchors[seg];
        let b = self.anchors[seg + 1];
        let mut rgb = [0u8; 3];
        for ch in 0..3 {
            let v = a[ch] + (b[ch] - a[ch]) * local_t;
            rgb[ch] = (v * 255.0).round().clamp(0.0, 255.0) as u8;
        }
        rgb
    }

    /// Build the 256-entry RGB lookup table. `reversed` mirrors the table
    /// end-for-end, which is exactly a reversal of the ramp and cannot
    /// introduce rounding of its own.
    pub fn lut(&self, reversed: bool) -> [u8; 256 * 3] {
        let mut lut = [0u8; 256 * 3];
        for i in 0..256 {
            let rgb = self.entry(i);
            // The destination entry: mirrored when reversed.
            let dst = if reversed { 255 - i } else { i };
            lut[dst * 3..dst * 3 + 3].copy_from_slice(&rgb);
        }
        lut
    }

    /// Look up an RGB triple for a value in `[0, 1]`; out-of-range inputs clamp.
    /// Evaluates the one entry rather than building the whole table, so a
    /// per-sample caller doesn't pay for 256 of them.
    pub fn sample(&self, t: f64, reversed: bool) -> [u8; 3] {
        let i = (t.clamp(0.0, 1.0) * 255.0).round() as usize;
        // Mirror the *index*, matching `lut(true)` exactly: that table puts
        // source entry `255 - i` at position `i`.
        self.entry(if reversed { 255 - i.min(255) } else { i })
    }

    /// `n` evenly spaced `#rrggbb` stops across the ramp, low → high, for the
    /// webview's legend gradient. The single source of truth for the legend
    /// colours: the panel no longer hardcodes them.
    pub fn css_stops(&self, n: usize, reversed: bool) -> Vec<String> {
        let lut = self.lut(reversed);
        (0..n)
            .map(|i| {
                // A single stop degenerates to the low end rather than dividing
                // by zero.
                let t = if n <= 1 {
                    0.0
                } else {
                    i as f64 / (n - 1) as f64
                };
                let idx = (t * 255.0).round() as usize;
                format!(
                    "#{:02x}{:02x}{:02x}",
                    lut[idx * 3],
                    lut[idx * 3 + 1],
                    lut[idx * 3 + 2]
                )
            })
            .collect()
    }
}

/// Look up a viridis RGB triple for a value in `[0, 1]`; out-of-range inputs
/// clamp. Retained as the shorthand for the default colormap.
pub fn viridis(t: f64) -> [u8; 3] {
    default_colormap().sample(t, false)
}

/// Compute `(min, max)` of a numeric grid, ignoring masked entries.
/// Returns `None` when every entry is masked or the grid is empty.
pub fn min_max_ignoring_mask<I: IntoIterator<Item = Option<f64>>>(values: I) -> Option<(f64, f64)> {
    let mut min = f64::INFINITY;
    let mut max = f64::NEG_INFINITY;
    let mut seen = false;
    for v in values {
        let Some(v) = v else { continue };
        if !v.is_finite() {
            continue;
        }
        if v < min {
            min = v;
        }
        if v > max {
            max = v;
        }
        seen = true;
    }
    if seen { Some((min, max)) } else { None }
}

/// Paint a row-major grid into an RGBA byte buffer suitable for
/// `ImageData`, colouring it with `colormap` (mirrored when `reversed`).
/// Each pixel is 4 bytes (`r, g, b, a`); masked or non-finite values render
/// as fully transparent (alpha = 0). When `min == max` (a constant field)
/// every present cell paints at LUT index 0.
///
/// `scale` selects linear or log10 value→colour mapping (see
/// [`scale_position`]); under [`ScaleMode::Log10`] a non-positive value has no
/// logarithm and paints transparent, exactly like a masked cell. `min`/`max`
/// are always the true (unlogged) display range, so the caller's colorbar
/// labels stay in data units.
///
/// Output length is `width * height * 4`. When `flip_y` is true, rows
/// are emitted bottom-to-top — useful when the source grid scans
/// south-to-north but the canvas wants north-up.
#[allow(clippy::too_many_arguments)]
pub fn paint_grid_rgba(
    values: &[f64],
    mask: Option<&[u8]>,
    width: u32,
    height: u32,
    min: f64,
    max: f64,
    flip_y: bool,
    colormap: &Colormap,
    reversed: bool,
    scale: ScaleMode,
) -> Vec<u8> {
    let w = width as usize;
    let h = height as usize;
    let total = w * h;
    if total == 0 {
        return Vec::new();
    }
    debug_assert_eq!(
        values.len(),
        total,
        "paint_grid_rgba: values.len()={} != width*height={total}; trailing pixels would silently render as transparent",
        values.len(),
    );
    if let Some(m) = mask {
        debug_assert_eq!(
            m.len(),
            total,
            "paint_grid_rgba: mask.len()={} != width*height={total}",
            m.len(),
        );
    }
    let mut out = vec![0u8; total * 4];
    // Build the LUT once for the whole grid rather than per pixel.
    let lut = colormap.lut(reversed);

    for (i, &v) in values.iter().enumerate().take(total) {
        let row = i / w;
        let col = i - row * w;
        let out_idx = if flip_y { (h - 1 - row) * w + col } else { i };
        let o = out_idx * 4;

        let masked = mask.is_some_and(|m| m.get(i).copied().unwrap_or(0) == 0);
        // A masked cell, a non-finite value, or (under log10) a non-positive
        // value has no colour and paints transparent so the background shows
        // through.
        let position = if masked {
            None
        } else {
            scale_position(v, min, max, scale)
        };
        let Some(tt) = position else {
            out[o] = 0;
            out[o + 1] = 0;
            out[o + 2] = 0;
            out[o + 3] = 0;
            continue;
        };
        let idx = (tt * 255.0).round() as usize;
        out[o] = lut[idx * 3];
        out[o + 1] = lut[idx * 3 + 1];
        out[o + 2] = lut[idx * 3 + 2];
        out[o + 3] = 255;
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The exact viridis LUT the renderer produced before the colormap registry
    /// existed: 11 anchors, linearly interpolated to 256 entries. Reproduced
    /// here from the pre-registry implementation so the default colormap's
    /// output is pinned against *this* code, not against itself.
    fn legacy_viridis_lut() -> [u8; 256 * 3] {
        const ANCHORS: [[f64; 3]; 11] = [
            [0.267004, 0.004874, 0.329415],
            [0.282623, 0.140926, 0.457517],
            [0.253935, 0.265254, 0.529983],
            [0.206756, 0.371758, 0.553117],
            [0.163625, 0.471133, 0.558148],
            [0.127568, 0.566949, 0.550556],
            [0.134692, 0.658636, 0.517649],
            [0.266941, 0.748751, 0.440573],
            [0.477504, 0.821444, 0.318195],
            [0.741388, 0.873449, 0.149561],
            [0.993248, 0.906157, 0.143936],
        ];
        let mut lut = [0u8; 256 * 3];
        let segs = (ANCHORS.len() - 1) as f64;
        for i in 0..256 {
            let t = i as f64 / 255.0;
            let mut seg = (t * segs).floor() as usize;
            if seg >= ANCHORS.len() - 1 {
                seg = ANCHORS.len() - 2;
            }
            let local_t = t * segs - seg as f64;
            let a = ANCHORS[seg];
            let b = ANCHORS[seg + 1];
            let r = a[0] + (b[0] - a[0]) * local_t;
            let g = a[1] + (b[1] - a[1]) * local_t;
            let bl = a[2] + (b[2] - a[2]) * local_t;
            lut[i * 3] = (r * 255.0).round().clamp(0.0, 255.0) as u8;
            lut[i * 3 + 1] = (g * 255.0).round().clamp(0.0, 255.0) as u8;
            lut[i * 3 + 2] = (bl * 255.0).round().clamp(0.0, 255.0) as u8;
        }
        lut
    }

    #[test]
    fn default_colormap_is_byte_identical_to_the_pre_registry_viridis() {
        // The registry must not have changed a single pixel of the default
        // render. Any drift in the generated anchors or the LUT builder shows
        // up here.
        assert_eq!(default_colormap().name(), "viridis");
        assert_eq!(
            default_colormap().lut(false).as_slice(),
            legacy_viridis_lut().as_slice()
        );
    }

    #[test]
    fn viridis_lut_has_canonical_endpoints() {
        let lut = default_colormap().lut(false);
        // First entry is canonical viridis dark-purple, last is
        // bright-yellow. Loose bounds — anchor stops + linear interp.
        assert!(lut[0] < 100 && lut[1] < 50 && lut[2] > 50, "viridis[0]");
        assert!(
            lut[765] > 200 && lut[766] > 200 && lut[767] < 80,
            "viridis[255]"
        );
    }

    #[test]
    fn viridis_function_clamps_out_of_range() {
        let lo = viridis(-5.0);
        let hi = viridis(5.0);
        let lut = default_colormap().lut(false);
        assert_eq!(lo, [lut[0], lut[1], lut[2]]);
        assert_eq!(hi, [lut[765], lut[766], lut[767]]);
    }

    #[test]
    fn every_registered_colormap_is_usable_and_distinct() {
        let all = colormaps();
        assert!(
            all.len() >= 8,
            "expected the full registry, got {}",
            all.len()
        );
        for c in all {
            // Name/label are populated and the name round-trips through lookup.
            assert!(!c.name().is_empty() && !c.label().is_empty());
            assert_eq!(
                Colormap::by_name(c.name()).map(|f| f.name()),
                Some(c.name())
            );
            // A colormap needs at least two anchors to interpolate between.
            assert!(c.anchors.len() >= 2, "{} has too few anchors", c.name());
            // The ramp must actually go somewhere: ends differ.
            let lut = c.lut(false);
            assert_ne!(
                &lut[0..3],
                &lut[765..768],
                "{} has identical endpoints",
                c.name()
            );
        }
        // Every map paints a *different* ramp — a copy-paste slip in the
        // generated table would otherwise go unnoticed.
        for (i, a) in all.iter().enumerate() {
            for b in &all[i + 1..] {
                assert_ne!(
                    a.lut(false).as_slice(),
                    b.lut(false).as_slice(),
                    "{} and {} produce the same ramp",
                    a.name(),
                    b.name()
                );
            }
        }
    }

    #[test]
    fn reversing_mirrors_the_ramp_exactly() {
        for c in colormaps() {
            let fwd = c.lut(false);
            let rev = c.lut(true);
            for i in 0..256 {
                let j = 255 - i;
                assert_eq!(
                    &fwd[i * 3..i * 3 + 3],
                    &rev[j * 3..j * 3 + 3],
                    "{} reversed entry {i}",
                    c.name()
                );
            }
        }
    }

    #[test]
    fn sample_agrees_with_the_lut_it_replaces() {
        // `sample` evaluates one entry instead of building the whole table; it
        // must still land on exactly the entry the table would have held, in
        // both directions, or a one-off lookup would disagree with the render.
        for c in colormaps() {
            for reversed in [false, true] {
                let lut = c.lut(reversed);
                for i in 0..256 {
                    let t = i as f64 / 255.0;
                    assert_eq!(
                        c.sample(t, reversed),
                        [lut[i * 3], lut[i * 3 + 1], lut[i * 3 + 2]],
                        "{} entry {i} (reversed={reversed})",
                        c.name()
                    );
                }
            }
            // Out-of-range inputs clamp to the ends rather than panicking.
            assert_eq!(c.sample(-1.0, false), c.sample(0.0, false));
            assert_eq!(c.sample(2.0, false), c.sample(1.0, false));
        }
    }

    #[test]
    fn unknown_colormap_name_is_rejected() {
        assert!(Colormap::by_name("jet").is_none());
        assert!(Colormap::by_name("").is_none());
        assert!(Colormap::by_name("Viridis").is_none(), "names are exact");
    }

    #[test]
    fn grayscale_is_a_neutral_ramp() {
        // A property the data must satisfy: every grayscale entry has r == g == b
        // and the ramp climbs from black to white.
        let gs = Colormap::by_name("grayscale").expect("grayscale is registered");
        let lut = gs.lut(false);
        for i in 0..256 {
            let (r, g, b) = (lut[i * 3], lut[i * 3 + 1], lut[i * 3 + 2]);
            assert!(r == g && g == b, "grayscale entry {i} is not neutral");
        }
        assert_eq!(&lut[0..3], &[0, 0, 0]);
        assert_eq!(&lut[765..768], &[255, 255, 255]);
    }

    #[test]
    fn diverging_maps_are_light_in_the_middle_and_saturated_at_the_ends() {
        // What makes a diverging map diverging: a near-neutral midpoint with
        // two distinct, saturated ends. Pins the kind tag against the data.
        for c in colormaps()
            .iter()
            .filter(|c| c.kind() == ColormapKind::Diverging)
        {
            let lut = c.lut(false);
            let spread = |i: usize| {
                let (r, g, b) = (
                    lut[i * 3] as i32,
                    lut[i * 3 + 1] as i32,
                    lut[i * 3 + 2] as i32,
                );
                r.max(g).max(b) - r.min(g).min(b)
            };
            let mid = spread(128);
            assert!(
                mid < 40,
                "{} midpoint should be near-neutral, channel spread {mid}",
                c.name()
            );
            assert!(
                spread(0) > mid && spread(255) > mid,
                "{} ends should be more saturated than its midpoint",
                c.name()
            );
        }
    }

    #[test]
    fn css_stops_are_sampled_from_the_lut_that_paints_the_grid() {
        // The legend's whole job is to show the ramp the image was painted
        // with, so every stop must come from that exact LUT.
        let c = Colormap::by_name("plasma").expect("registered");
        for reversed in [false, true] {
            let stops = c.css_stops(33, reversed);
            let lut = c.lut(reversed);
            assert_eq!(stops.len(), 33);
            for (i, stop) in stops.iter().enumerate() {
                let idx = (i as f64 / 32.0 * 255.0).round() as usize;
                assert_eq!(
                    stop,
                    &format!(
                        "#{:02x}{:02x}{:02x}",
                        lut[idx * 3],
                        lut[idx * 3 + 1],
                        lut[idx * 3 + 2]
                    ),
                    "stop {i} (reversed={reversed})"
                );
            }
        }
        // Reversing swaps the ends of the legend, which is what the user sees.
        let fwd = c.css_stops(33, false);
        let rev = c.css_stops(33, true);
        assert_eq!(rev[0], fwd[32]);
        assert_eq!(rev[32], fwd[0]);
        // A degenerate request must not divide by zero.
        assert_eq!(c.css_stops(1, false).len(), 1);
    }

    #[test]
    fn min_max_skips_nulls_and_nonfinite() {
        let it = vec![
            None,
            Some(1.0),
            Some(2.0),
            None,
            Some(3.0),
            Some(f64::NAN),
            Some(-1.0),
        ];
        let out = min_max_ignoring_mask(it).expect("some present");
        assert_eq!(out.0, -1.0);
        assert_eq!(out.1, 3.0);
    }

    #[test]
    fn min_max_returns_none_when_all_masked() {
        let it: Vec<Option<f64>> = vec![None, None];
        assert!(min_max_ignoring_mask(it).is_none());
    }

    #[test]
    fn paint_grid_rgba_emits_transparent_for_masked() {
        let values = vec![10.0, 20.0, 30.0, 40.0];
        let mask = vec![1u8, 0, 1, 1];
        let out = paint_grid_rgba(
            &values,
            Some(&mask),
            2,
            2,
            10.0,
            40.0,
            false,
            default_colormap(),
            false,
            ScaleMode::Linear,
        );
        assert_eq!(out.len(), 16);
        // Pixel 1 is masked → fully transparent.
        assert_eq!(&out[4..8], &[0, 0, 0, 0]);
        // Pixel 0 should be the LUT[0] viridis color with alpha 255.
        assert_eq!(out[3], 255);
    }

    #[test]
    fn paint_grid_rgba_honours_the_chosen_colormap_and_reverse() {
        let values = vec![0.0, 1.0];
        let paint = |name: &str, reversed: bool| {
            let c = Colormap::by_name(name).expect("registered");
            paint_grid_rgba(
                &values,
                None,
                2,
                1,
                0.0,
                1.0,
                false,
                c,
                reversed,
                ScaleMode::Linear,
            )
        };
        let viridis = paint("viridis", false);
        let turbo = paint("turbo", false);
        assert_ne!(
            viridis, turbo,
            "a different colormap must paint differently"
        );

        // Reversed viridis paints the low cell with what the forward map paints
        // the high cell, and vice versa.
        let reversed = paint("viridis", true);
        assert_eq!(&reversed[0..3], &viridis[4..7]);
        assert_eq!(&reversed[4..7], &viridis[0..3]);
    }

    #[test]
    fn paint_grid_rgba_returns_empty_for_zero_dims() {
        let out = paint_grid_rgba(
            &[],
            None,
            0,
            10,
            0.0,
            1.0,
            false,
            default_colormap(),
            false,
            ScaleMode::Linear,
        );
        assert!(out.is_empty());
        let out = paint_grid_rgba(
            &[],
            None,
            10,
            0,
            0.0,
            1.0,
            false,
            default_colormap(),
            false,
            ScaleMode::Linear,
        );
        assert!(out.is_empty());
    }

    #[test]
    fn paint_grid_rgba_flip_y_inverts_rows() {
        let values = vec![1.0, 2.0, 3.0, 4.0];
        let unflipped = paint_grid_rgba(
            &values,
            None,
            2,
            2,
            1.0,
            4.0,
            false,
            default_colormap(),
            false,
            ScaleMode::Linear,
        );
        let flipped = paint_grid_rgba(
            &values,
            None,
            2,
            2,
            1.0,
            4.0,
            true,
            default_colormap(),
            false,
            ScaleMode::Linear,
        );
        // Top-left of flipped == row 1, col 0 of unflipped (= source pixel 2).
        // We can verify by checking that the bytes differ as expected.
        assert_ne!(unflipped, flipped);
        // Verify symmetry: flipping twice returns the original layout.
        // (Re-paint flipped values from `unflipped`-derived row-order.)
        // Simpler check: the alpha byte of the top-left flipped pixel is
        // still 255 (it's a present cell).
        assert_eq!(flipped[3], 255);
    }

    #[test]
    fn scale_position_linear_matches_the_old_formula() {
        // Linear must be byte-for-byte the mapping the renderer always used:
        // evenly spaced, clamped, constant field → 0.0, non-finite → None.
        assert_eq!(scale_position(0.0, 0.0, 10.0, ScaleMode::Linear), Some(0.0));
        assert_eq!(scale_position(5.0, 0.0, 10.0, ScaleMode::Linear), Some(0.5));
        assert_eq!(
            scale_position(10.0, 0.0, 10.0, ScaleMode::Linear),
            Some(1.0)
        );
        // Out of range clamps to the ends.
        assert_eq!(
            scale_position(-3.0, 0.0, 10.0, ScaleMode::Linear),
            Some(0.0)
        );
        assert_eq!(
            scale_position(99.0, 0.0, 10.0, ScaleMode::Linear),
            Some(1.0)
        );
        // Degenerate range → low end, never a divide-by-zero.
        assert_eq!(scale_position(7.0, 7.0, 7.0, ScaleMode::Linear), Some(0.0));
        // Non-finite has no place on the ramp.
        assert_eq!(scale_position(f64::NAN, 0.0, 10.0, ScaleMode::Linear), None);
    }

    #[test]
    fn scale_position_log10_spreads_decades_evenly() {
        // Over [1, 100] the midpoint in log space is 10 (one decade up), not 50.
        assert_eq!(scale_position(1.0, 1.0, 100.0, ScaleMode::Log10), Some(0.0));
        assert_eq!(
            scale_position(10.0, 1.0, 100.0, ScaleMode::Log10),
            Some(0.5)
        );
        assert_eq!(
            scale_position(100.0, 1.0, 100.0, ScaleMode::Log10),
            Some(1.0)
        );
        // A positive value below/above the range clamps, it does not vanish.
        assert_eq!(scale_position(0.1, 1.0, 100.0, ScaleMode::Log10), Some(0.0));
        assert_eq!(
            scale_position(1000.0, 1.0, 100.0, ScaleMode::Log10),
            Some(1.0)
        );
    }

    #[test]
    fn scale_position_log10_drops_non_positive_and_non_finite() {
        // No logarithm for zero or negatives → missing.
        assert_eq!(scale_position(0.0, 1.0, 100.0, ScaleMode::Log10), None);
        assert_eq!(scale_position(-5.0, 1.0, 100.0, ScaleMode::Log10), None);
        assert_eq!(scale_position(f64::NAN, 1.0, 100.0, ScaleMode::Log10), None);
        // Degenerate log range (min == max) → low end, no divide-by-zero.
        assert_eq!(scale_position(4.0, 4.0, 4.0, ScaleMode::Log10), Some(0.0));
    }

    #[test]
    fn paint_grid_rgba_log10_paints_known_indices() {
        // A row of exact decades over [1, 100] lands on LUT entries 0, 128, 255
        // under log10 — the acceptance case: known grid → expected colours.
        let values = vec![1.0, 10.0, 100.0];
        let out = paint_grid_rgba(
            &values,
            None,
            3,
            1,
            1.0,
            100.0,
            false,
            default_colormap(),
            false,
            ScaleMode::Log10,
        );
        let lut = default_colormap().lut(false);
        let expect = |idx: usize| [lut[idx * 3], lut[idx * 3 + 1], lut[idx * 3 + 2], 255];
        assert_eq!(&out[0..4], &expect(0));
        assert_eq!(&out[4..8], &expect(128));
        assert_eq!(&out[8..12], &expect(255));

        // The same grid under linear does *not* put 10 at the midpoint — proving
        // the mode actually changes the mapping rather than being a no-op.
        let linear = paint_grid_rgba(
            &values,
            None,
            3,
            1,
            1.0,
            100.0,
            false,
            default_colormap(),
            false,
            ScaleMode::Linear,
        );
        assert_ne!(&linear[4..8], &out[4..8], "10 maps differently under log10");
    }

    #[test]
    fn paint_grid_rgba_log10_paints_non_positive_transparent() {
        // Zero and negative cells have no logarithm and must paint fully
        // transparent, exactly like a masked cell — positives still colour.
        let values = vec![0.0, -3.0, 10.0];
        let out = paint_grid_rgba(
            &values,
            None,
            3,
            1,
            1.0,
            100.0,
            false,
            default_colormap(),
            false,
            ScaleMode::Log10,
        );
        assert_eq!(&out[0..4], &[0, 0, 0, 0], "zero → transparent");
        assert_eq!(&out[4..8], &[0, 0, 0, 0], "negative → transparent");
        assert_eq!(out[11], 255, "the positive cell is still painted");
    }

    #[test]
    fn scale_mode_wire_tags_round_trip() {
        assert_eq!(ScaleMode::Linear.as_str(), "linear");
        assert_eq!(ScaleMode::Log10.as_str(), "log10");
        assert_eq!(ScaleMode::default(), ScaleMode::Linear);
    }
}
